### PR TITLE
scroll view graduation part 2

### LINKED ISSUE #7449: Scroll View - Allow for interaction area buffer in both front and back of scroll view
## Overview

Interaction with a scroll view should account for area buffer in front (~3cm) and back of scroll view (~20cm) for pointer movement to avoid loosing scroll engagement

A Test for this behaviour should be added as part of ScrollingObjectCollection graduation.

This issue is part of #6637.

### LINKED ISSUE #8064: What is a right way to delete object from Scrolling Object Collection?
I want to add and remove objects inside Scrolling Object Collection.
Adding is not a problem, but when i am trying to remove object using this code:
`Destroy(ScrollBar.Find("Container").Find("test3")?.gameObject);
ScrollBar.GetComponent<ScrollingObjectCollection>().UpdateCollection()`
I get this:
image
and also exceptions:

> MissingReferenceException: The object of type 'BoxCollider' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
Microsoft.MixedReality.Toolkit.Experimental.UI.ScrollingObjectCollection.HideItems () (at Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs:1664)
Microsoft.MixedReality.Toolkit.Experimental.UI.ScrollingObjectCollection.LateUpdate () (at Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs:1038

Is there a better way to remove object?

Specs: Unity 2018.4, MRTK 2.4.0, Hololens 1st gen

### LINKED ISSUE #8148: Scroll Object collection should only engage if touch comes from front of scroll slate
Scroll Object collection should only engage in a drag if touch comes from the front of scroll slate. At the moment if user moves hand from the back or sides of scroll background the scroll engage will also be triggered. This does not match Shell behavior.

scroll_touch_from_back

### PR DESCRIPTION
**Pull request by vaoliva**
## Overview
This PR is part of Scroll View graduation and addresses the following issues / fixes:

 #8148 
- **Issue:** Scroll Object collection should only engage if touch comes from front of scroll slate but currently the user is able to trigger scroll even when hand comes from behind, top, bottom or sides of the scroll slate
- **Fix:** Checking for previous position of poke pointer when touch started is handled
scroll_touch_from_back

 #8064 
- **Issue:** Currently there is no safe way of deleting child items from scroll collection. Destroying an object throw errors on console.
- **Fix:** Added methods for safely for adding and deleting items.
image

MissingReferenceException: The object of type 'BoxCollider' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
Microsoft.MixedReality.Toolkit.Experimental.UI.ScrollingObjectCollection.HideItems () (at Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs:1664)
Microsoft.MixedReality.Toolkit.Experimental.UI.ScrollingObjectCollection.LateUpdate () (at Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs:1038

#7449 . 
- **Issue:** scroll view should allow for near interaction area buffer in front, back, top, bottom and sides of scroll slate boundary o match shell behaviour. Currently only front buffer exists. 
- **Fix:** Exposing near interaction releaseThreshoulds for different axis / sides
scroll_buffer

This PR is based on the Event Propagation feature branch.

- Fixes #8148
- Fixes #7449  
- Fixes #8064

### CODE REVIEW

File: Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs [hunk 1]
```diff
@@ -98,32 +98,63 @@ public float HandDeltaMagThreshold
         }
 
         [SerializeField]
-        [Tooltip("Seconds the user's pointer can intersect a controller item before it is considered a drag.")]
-        [Range(0.0f, 2.0f)]
-        private float dragTimeThreshold = 0.75f;
+        [Tooltip("Withdraw amount from the front of the scroll boundary needed to transition from touch engaged to released.")]
```
Comment (julenka) [inline Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs:101]: Is the units here meters?

File: Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs [hunk 2]
```diff
@@ -1686,6 +1687,13 @@ private void HideItems()
                     node = NodeList[i] as ScrollingObjectCollectionNode;
                 }
 
+                // Node object was not properly removed
+                if (node.Transform == null)
```
Comment (julenka) [inline Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs:1691]: extra code?

File: Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs (hunk 1 above)
Comment (vaoliva) [reply Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs:101]: Adding " , in meters,".

File: Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs (hunk 2 above)
Comment (vaoliva) [reply Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs]: removed

File: Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs [hunk 3]
```diff
@@ -2098,6 +2117,39 @@ public static bool TryGetObjectAlignedBoundsSize(Transform obj, out Vector3 alig
             return (canGetSize) ? true : false;
         }
 
+        /// <summary>
+        /// Safely adds a child game object to scroll collection.
+        /// </summary>
+        public bool AddItem(GameObject item)
```
Comment (thalbern) [inline Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs:2123]: i'm wondering if it would make sense to have a AddItem with a list of gameobjects as well - just so if several elemetns were added (or removed) we wouldn't call Reset all the time.

Comment (vaoliva) [reply Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs:2123]: I think it would Bernie. This method is only covering a very unlikely situation of objects being added on runtime with interactions happening at the same time.... so yeah... adding a collection of objects make sense

Comment (vaoliva) [reply Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs:2123]: > Did you think about splitting releaseThresholdLeftRight and TopBottom like you did with back and front? would be more consistent but not sure if it's needed. 

Yeah I was unsure, as at least in the shell top and bottom always match, same as left and right. But front is how the click happens so this will always be different from back. But we could separate them.

> Also what we could consider for future work (can be after graduation) is to expose these thresholds as planes so users can easier visualize them in the editor when setting them up - have a look at the debug planes in PressableButton. if you think it would make sense we could ask a task for that for later

Second that. This one was on my list as well
