### PR TITLE
Port TextToSpeech to MRTK

### LINKED ISSUE #3569: Text To Speech is missing in MRTK-v2.0.0-Beta2
##MRTK-v2.0.0-Beta2 (Unity package) doesn't port over "Text to speech" feature that exist in the holotoolkit. I don't see an example or tutorial how to implement this in this new toolkit. In the previous holotoolkit we do have TextToSpeechManager.cs to use.

## Expected Behavior
Developer can just do text to speech using a port-over class TextToSpeechManager.cs
## Actual Behavior
Can't find anything similar to do text to speech
## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2018.3
## Mixed Reality Toolkit Release Version
v2.0.0-Beta2

### PR DESCRIPTION
**Pull request by MaxWang-MS**
## Overview
This PR ports the Text To Speech feature from HTK to MRTK. Sample scene and script are also included. Note this feature/demo scene is only supported on Windows device (i.e. not in editor).

## Changes
- Fixes #3569

### CODE REVIEW

File: Assets/MRTK/SDK/Features/Audio/TextToSpeech.cs [hunk 1]
```diff
@@ -0,0 +1,380 @@
...
+    /// <remarks>
+    /// <para>SpeechSynthesizer generates speech as a SpeechSynthesisStream.</para>
+    /// <para>This class converts that stream into a Unity AudioClip and plays the clip using 
+    /// the <see cref="AudioSource"/> you supply in the inspector. This allows you to position the voice 
+    /// as desired in 3D space. One recommended approach is to place the AudioSource on an empty 
+    /// GameObject that is a child of Main Camera and position it approximately 0.6 units above the 
+    /// camera. This orientation will sound similar to Cortana's speech in the OS.</para>
+    /// </remarks>
+    [RequireComponent(typeof(AudioSource))]
+    [AddComponentMenu("Scripts/MRTK/SDK/AudioInfluencerController")]
```
Comment (keveleigh) [inline Assets/MRTK/SDK/Features/Audio/TextToSpeech.cs:55]:
```suggestion
    [AddComponentMenu("Scripts/MRTK/SDK/TextToSpeech")]
```

**Review by keveleigh — APPROVED** [review]
