### PR TITLE
Fix Command line build / ar foundation uwp workaround

### LINKED ISSUE #6416: Unity 2018: Unable to build AR Foundation (UWP, .NET) via the command line
The AR Foundation and AR Subystems asmdef files, in Unity 2018 do not define any include or exclude platforms. This means that they should be able to build regardless of build target settings.

Unfortunately, there are compile issues when targeting UWP using the .NET backend.

MRTK has worked around this by, on project load, modifying the excluded platforms list to add "WSA". This works well in the editor, but fails when using batch mode.

This has caused us to disable .NET backend validation in CI in order to unblock the AR Foundation support feature (#6344).

### PR DESCRIPTION
**Pull request by davidkline-ms**
The reason the command line build was failing for the .net backed was that when Unity generates c# projects for the uwp solution, it includes all projects. When a project does not support a specific platform, it is expected that the necessary #if / #endif fences are in place. Unfortunately, ar foundation projects do not have the fencing.

This change instructs the command line build to _not_ generate c# projects and re-enables the .net backend build in pr validation.

Fixes #6416

### CODE REVIEW

File: Assets/MixedRealityToolkit/Utilities/Editor/EditorProjectUtilities.cs [hunk 1]
```diff
@@ -246,7 +256,6 @@ private static DirectoryInfo GetPackageCache()
             DirectoryInfo[] folders = root.GetDirectories(folderName);
             if (folders.Length == 0) 
             {
-                Debug.Log($"Failed to locate a folder fitting the {folderName} pattern.");
```
Comment (keveleigh) [inline Assets/MixedRealityToolkit/Utilities/Editor/EditorProjectUtilities.cs]: Why remove this?

File: pipelines/pr.yaml [hunk 2]
```diff
@@ -22,5 +22,5 @@ jobs:
       # the ongoing rolling CI build. This build in particular is highly correlated
       # the .NET x86 build and ARM IL2CPP build.
       buildUWPX86: false
-      buildUWPDotNet: false
+      buildUWPDotNet: true
```
Comment (keveleigh) [inline pipelines/pr.yaml]: This can just be removed, since it defaults to `true` in the template

File: Assets/MixedRealityToolkit/Utilities/Editor/EditorProjectUtilities.cs (hunk 1 above)
Comment (davidkline-ms) [reply Assets/MixedRealityToolkit/Utilities/Editor/EditorProjectUtilities.cs]: It lead to confusion and concern when customers chose to _not_ include ar foundation in their project.

File: pipelines/pr.yaml (hunk 2 above)
Comment (davidkline-ms) [reply pipelines/pr.yaml]: sounds good

File: Assets/MixedRealityToolkit/Utilities/Editor/EditorProjectUtilities.cs (hunk 1 above)
Comment (davidkline-ms) [reply Assets/MixedRealityToolkit/Utilities/Editor/EditorProjectUtilities.cs]: i got a question about that line this morning, in fact.
