### PR TITLE
Fix GLTF related deserialization issues

### LINKED ISSUE #8748: GLTF Enums Imported Incorrectly
## Describe the bug

Deserialization of enums represented as strings in GLTF JSON are not imported correctly and default to the first option.

## To reproduce

1. Import the [example animated box](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoxAnimated).
2. Check the resulting GltfObject.animations[0].channels[0].target.path, which is "rotation" in the file, but is imported as GltfAnimationChannelPath.translation.

## Expected behavior

Target path should be imported as a string, or properly as the correct GltfAnimationChannelPath.

## Your setup (please complete the following information)

- Unity Version 2019.2.19f1
- MRTK Version v2.4.0

## Target platform (please complete the following information)

- HoloLens 2

### PR DESCRIPTION
**Pull request by MaxWang-MS**
## Overview
Due to the restrictions of Unity's built-in JsonUtility.FromJson, Enum fields in GLTF files cannot be correctly converted during import. This PR fixes the issue by calling Enum.Parse after deserialization to make sure Enums are correctly imported.

## Changes
- Fixes #8748

### CODE REVIEW

File: Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAccessor.cs [hunk 1]
```diff
@@ -31,7 +32,11 @@ public class GltfAccessor : GltfChildOfRootProperty
         /// 5125 (UNSIGNED_INT) is only allowed when the accessor contains indices
         /// i.e., the accessor is only referenced by `primitive.indices`.
         /// </summary>
-        public GltfComponentType componentType;
+        [NonSerialized]
+        public GltfComponentType ComponentType;
```
Comment (keveleigh) [inline Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAccessor.cs:36]: Can we make this a property, to try to reduce the number of `public` fields we have and so we won't need the `NonSerialized` tag?

File: Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAccessor.cs [hunk 2]
```diff
@@ -100,5 +105,22 @@ public class GltfAccessor : GltfChildOfRootProperty
...
+            }
+            else
+            {
+                ComponentType = default;
+            }
+        }
+
+        public void OnBeforeSerialize()
+        {
+
```
Comment (keveleigh) [inline Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAccessor.cs:123]: Should these be implemented?

File: Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAccessor.cs [hunk 3]
```diff
@@ -100,5 +105,22 @@ public class GltfAccessor : GltfChildOfRootProperty
         /// https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/bufferView.schema.json
         /// </summary>
         public GltfBufferView BufferView { get; internal set; }
+
+        public void OnAfterDeserialize()
```
Comment (keveleigh) [inline Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAccessor.cs:109]: Also, nit, but since these aren't methods we expect to be called manually, could these be [implemented explicitly](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation)? That way the methods are hidden from our docs and intellisense, but still callable by Unity.

File: Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAccessor.cs (hunk 2 above)
Comment (MaxWang-MS) [reply Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAccessor.cs:122]: I do not think so as we are not doing serialization with GLTF objects at the moment.

Comment (keveleigh) [reply Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAccessor.cs:122]: Oh, true!

File: Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAccessorSparseIndices.cs [hunk 4]
```diff
@@ -30,6 +31,26 @@ public class GltfAccessorSparseIndices : GltfProperty
...
+
+        void ISerializationCallbackReceiver.OnAfterDeserialize()
+        {
+            if (Enum.TryParse(componentType, out GltfComponentType result))
+            {
+                ComponentType = result;
+            }
+            else
+            {
+                ComponentType = default;
```
Comment (keveleigh) [inline Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAccessorSparseIndices.cs:47]: Does this work in the UWP build? For some reason I feel like I remember `default` vs `default(GltfComponentType)` isn't allowed in the versions of things Unity uses

File: Assets/MRTK/Core/Utilities/Gltf/Serialization/GltfConversions.cs [hunk 5]
```diff
@@ -218,7 +218,7 @@ public static int[] GetIntArray(this GltfAccessor accessor, bool flipFaces = tru
 
             var array = new int[accessor.count];
 
-            GetTypeDetails(accessor.componentType, out int componentSize, out float _);
+            GetTypeDetails(accessor.ComponentType, out int componentSize, out float _);
```
Comment (keveleigh) [inline Assets/MRTK/Core/Utilities/Gltf/Serialization/GltfConversions.cs:221]: Can you think of any way to make this a non-breaking change? I'm not coming up with anything at the moment, since the (newly private) backing fields have to match the file's field name (unless there's a tag or something to say "this field is serialized with this name even though it's named differently"?)

Comment (MaxWang-MS) [reply Assets/MRTK/Core/Utilities/Gltf/Serialization/GltfConversions.cs:221]: I tried but noting came to mind (I even remembering trying FormerlySerializedAs with no luck)

File: Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAccessorSparseIndices.cs (hunk 4 above)
Comment (MaxWang-MS) [reply Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAccessorSparseIndices.cs:47]: I have confirmed that it indeed works on HL2.

**Review by keveleigh — APPROVED** [review]

File: Assets/MRTK/Core/Utilities/Gltf/Schema/GltfSampler.cs [hunk 6]
```diff
@@ -10,27 +11,80 @@ namespace Microsoft.MixedReality.Toolkit.Utilities.Gltf.Schema
...
-        public GltfMagnificationFilterMode magFilter = GltfMagnificationFilterMode.Linear;
+        public GltfMagnificationFilterMode MagFilter { get; set; }
+
+        [SerializeField]
+        private string magFilter = null;
 
         /// <summary>
         /// Minification filter. All valid values correspond to WebGL enums.
         /// </summary>
-        public GltfMinFilterMode GltfMinFilter = GltfMinFilterMode.NearestMipmapLinear;
```
[the remark this answers is not in the document]
Comment (MaxWang-MS) [reply Assets/MRTK/Core/Utilities/Gltf/Schema/GltfSampler.cs:24]: Yes

File: Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAccessorSparseIndices.cs [hunk 7]
```diff
@@ -30,6 +31,26 @@ public class GltfAccessorSparseIndices : GltfProperty
         /// `5123` (UNSIGNED_SHORT)
         /// `5125` (UNSIGNED_INT)
         /// </summary>
-        public GltfComponentType ComponentType;
```
[the remark this answers is not in the document]
Comment (MaxWang-MS) [reply Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAccessorSparseIndices.cs:33]: The latter is the case.

File: Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAccessor.cs [hunk 8]
```diff
@@ -31,7 +32,10 @@ public class GltfAccessor : GltfChildOfRootProperty
         /// 5125 (UNSIGNED_INT) is only allowed when the accessor contains indices
         /// i.e., the accessor is only referenced by `primitive.indices`.
         /// </summary>
-        public GltfComponentType componentType;
+        public GltfComponentType ComponentType { get; set; }
```
Comment (SimonDarksideJ) [inline Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAccessor.cs:35]: The Private and public fields do not seem connected.  Was this intentional or has something been missed?

File: Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAnimationSampler.cs [hunk 9]
```diff
@@ -27,13 +28,33 @@ public class GltfAnimationSampler : GltfProperty
...
+
+        [SerializeField]
+        private string interpolation = null;
 
         /// <summary>
         /// The index of an accessor, containing keyframe output values. Output and input
         /// accessors must have the same `count`. When sampler is used with TRS target,
         /// output accessors componentType must be `FLOAT`.
         /// </summary>
         public int output;
```
Comment (SimonDarksideJ) [inline Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAnimationSampler.cs:41]: There seem to be many other instances of the proper casing that have not been touched.  Considering the change is to fix serialisation, are these others not affected?

File: Assets/MRTK/Core/Utilities/Gltf/Schema/GltfBufferView.cs [hunk 10]
```diff
@@ -42,11 +43,31 @@ public class GltfBufferView : GltfChildOfRootProperty
         /// All valid values correspond to WebGL enums.
         /// When this is not provided, the bufferView contains animation or skin data.
         /// </summary>
-        public GltfBufferViewTarget target = GltfBufferViewTarget.None;
+        public GltfBufferViewTarget Target { get; set; }
+
+        [SerializeField]
+        private string target = null;
```
Comment (SimonDarksideJ) [inline Assets/MRTK/Core/Utilities/Gltf/Schema/GltfBufferView.cs:49]: We seem to be removing the fixed defaults that Khronos has implemented, was this intentional?

Comment (SimonDarksideJ) [inline Assets/MRTK/Core/Utilities/Gltf/Schema/GltfBufferView.cs:49]: Additionally, a string CANNOT have a default of None, the correct "empty" default for a string is String.Empty.

File: Assets/MRTK/Core/Utilities/Gltf/Schema/GltfMeshPrimitive.cs [hunk 11]
```diff
@@ -12,10 +12,8 @@ namespace Microsoft.MixedReality.Toolkit.Utilities.Gltf.Schema
     /// https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/mesh.primitive.schema.json
     /// </summary>
     [Serializable]
-    public class GltfMeshPrimitive : GltfProperty
+    public class GltfMeshPrimitive : GltfProperty, ISerializationCallbackReceiver
     {
-        #region Serialized Fields
```
Comment (SimonDarksideJ) [inline Assets/MRTK/Core/Utilities/Gltf/Schema/GltfMeshPrimitive.cs:17]: Why have you removed the Region?  These are there to help organize the code, please revert.

File: Assets/MRTK/Core/Utilities/Gltf/Schema/GltfSampler.cs [hunk 12]
```diff
@@ -10,27 +11,83 @@ namespace Microsoft.MixedReality.Toolkit.Utilities.Gltf.Schema
...
+            {
+                WrapT = GltfWrapMode.Repeat;
+            }
+            if (Enum.TryParse(wrapS, out GltfWrapMode result4))
+            {
+                WrapS = result4;
+            }
+            else
+            {
+                WrapS = GltfWrapMode.Repeat;
```
Comment (SimonDarksideJ) [inline Assets/MRTK/Core/Utilities/Gltf/Schema/GltfSampler.cs:81]: In this class, you have correctly reset the value to the default specified by Khronos, but in other classes you haven't.  
Can we ensure the change is consistent and either preserves the default or does not.

**Review by SimonDarksideJ — CHANGES_REQUESTED** [review]

File: Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAccessor.cs (hunk 8 above)
Comment (SimonDarksideJ) [reply Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAccessor.cs:35]: Ok, I think I see your reasoning, separating the serialization from the access via enum.

**Comment by SimonDarksideJ** [comment]
I have a concern over the use of Strings for these enums, especially as the data type that the Khronos spec uses is "int"
```json
                {
                    "type": "integer"
                }
```

Is there a specific reason you chose string over int @MaxWang-MS ?

**Comment by SimonDarksideJ** [comment]
On further investigation, MOST of the enums are an Int.  But frustratingly, SOME are a string, (and some are an Enum but not implemented as an Enum in the Khronos spec).

Rather frustrating, but the standards head in me says we should implement types as defined in the Khronos spec.

File: Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAccessor.cs (hunk 8 above)
Comment (keveleigh) [reply Assets/MRTK/Core/Utilities/Gltf/Schema/GltfAccessor.cs:35]: Unity's deserializer doesn't handle enums the same way the glTF spec does. The spec serializes them by string, while Unity serializes them by int value, so this has been broken since it was first contributed.

These are connected via the `ISerializationCallbackReceiver` events below.

File: Assets/MRTK/Core/Utilities/Gltf/Schema/GltfBufferView.cs (hunk 10 above)
Comment (keveleigh) [inline Assets/MRTK/Core/Utilities/Gltf/Schema/GltfBufferView.cs:49]: Much of this is moved to the `ISerializationCallbackReceiver` handlers below. The default is still there.

Comment (keveleigh) [reply Assets/MRTK/Core/Utilities/Gltf/Schema/GltfBufferView.cs:49]: Why can't it be null? It's a reference type.

File: Assets/MRTK/Core/Utilities/Gltf/Schema/GltfSampler.cs (hunk 12 above)
Comment (keveleigh) [reply Assets/MRTK/Core/Utilities/Gltf/Schema/GltfSampler.cs:81]: Can you point out cases where the default is dropped? I can't find any.

**Review by keveleigh — APPROVED** [review]
