### PR TITLE
[June18] App bar positioning bug fix #2042 

### LINKED ISSUE #2042: Bounding Box and App Bar not working as expected for Rectangular Holograms
## Overview
The Bounding box for hololens works very well for squared holograms like a chair, cube, small toy but for something like truck which length is very large compared to it's breadth, the app bar is far away from the hologram, as it takes the maximum scale side as start.
When Scaling up or scaling down the truck, the app bar goes in to the truck when scaled town very small, and moves very far from hologram when scaled up.
It would be really helpful if i get a solution for this quick, I'm short on time, please respond quickly, Thank you!
## Expected Behavior
When Scaling up or down a hologram , the app bar should adjust according to that so that the bar doesn't goes in to hologram or don't more far way.
## Actual Behavior
when the Bounding box Rig is attached to hologram which is of rectangular shape like a big truck, while scaling up or down or while rotating the hologram with sphere handles, the app bar gets into hologram or moves too far away from hologram
## Steps to reproduce
Import a truck like model which is of rectangular shape whose length is relatively very large to it's breadth , add bounding box rig to it and you can experience the above mentioned issues
## Unity Editor Version
Unity2017.2.1f1

### PR DESCRIPTION
**Pull request by johnppella**
Overview
This PR addresses Issue #2042 
"Bounding Box and App Bar not working as expected for Rectangular Holograms"
The fix causes the appbar to move to a cleaner location on objects that are very long in one dimension.

Changes
The non-axis-aligned bounding box (NAABB)  helper functions are now broken out into a separate file: BoundingBoxHelper.cs.

This script contains a function to update the location of the appbar in its Update() loop: 
GetNonAABoundingBoxCornerPositions()
This function finds the face of the non-axis aligned bounding cube of an object that is facing a target point. (this point is the headPosition in the example scene.)

This script also contains a static function which finds the same info if it is only needed once. 
Included are additional helper functions for getting the edges of a face of the NAABB, the centroid of a face, the midpoint of the edges, the bottom of a face etc.

the Serialized Field AppBarHoverOffsetZ is now exposed at design time to allow the user to set a distance along the face normal that the appbar sits offset from the actual face.

- Fixes: # 2042

### CODE REVIEW

File: Assets/HoloToolkit/UX/Scripts/AppBar/AppBar.cs [hunk 1]
```diff
@@ -35,6 +35,11 @@ public class AppBar : InteractionReceiver
         /// </summary>
         public float HoverOffsetZ = 0f;
 
+        /// <summary>
+        /// Uses an alternate follow style that works better for very oblong objects
+        /// </summary>
+        public bool UseTightFollow = false;
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/UX/Scripts/AppBar/AppBar.cs]: should probably be a property

File: Assets/HoloToolkit/UX/Scripts/AppBar/AppBar.cs [hunk 2]
```diff
@@ -108,6 +113,8 @@ public BoundingBox BoundingBox
             }
         }
 
+        public BoundingBoxRig BoundingRig;
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/UX/Scripts/AppBar/AppBar.cs]: same here.

**Comment by johnppella** [comment]
changed the two public variables to Properties

File: Assets/HoloToolkit/UX/Scripts/AppBar/AppBar.cs [hunk 3]
```diff
@@ -150,6 +186,8 @@ public ButtonTemplate[] DefaultButtons
             }
         }
 
+
+
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/UX/Scripts/AppBar/AppBar.cs]: extra lines?

File: Assets/HoloToolkit/UX/Scripts/BoundingBoxes/BoundingBox.cs [hunk 4]
```diff
@@ -601,6 +614,27 @@ public static void GetMeshFilterBoundsPoints(GameObject target, List<Vector3> bo
...
         }
 
+        public static void GetNonAxisAlignedBB_Corners(GameObject target, List<Vector3> boundsPoints)
+        {
+            LayerMask mask = new LayerMask();
+
+            GameObject clone = GameObject.Instantiate(target);
+            clone.transform.localRotation = Quaternion.identity;
+            clone.transform.position = Vector3.zero;
+            clone.transform.localScale = new Vector3(1,1,1);
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/UX/Scripts/BoundingBoxes/BoundingBox.cs]: nit: vector3.one

**Comment by johnppella** [comment]
2 more changes- extra space and static call

File: Assets/HoloToolkit/UX/Scripts/BoundingBoxes/BoundingBox.cs [hunk 5]
```diff
@@ -601,6 +614,27 @@ public static void GetMeshFilterBoundsPoints(GameObject target, List<Vector3> bo
...
+            clone.transform.localScale = Vector3.one;
+            BoundingBox.GetMeshFilterBoundsPoints(clone, boundsPoints, mask);
+            Vector3 centroid = target.transform.position;
+            GameObject.Destroy(clone);
+
+#if UNITY_2017_1_OR_NEWER
+            for (int i = 0; i < boundsPoints.Count; ++i)
+            {
+                boundsPoints[i] = target.transform.localToWorldMatrix.MultiplyPoint(boundsPoints[i]);
+                //boundsPoints[i] += centroid;
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/UX/Scripts/BoundingBoxes/BoundingBox.cs]: will we use this later?

File: Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs [hunk 6]
```diff
@@ -0,0 +1,327 @@
...
+    /// <param name="target"></param>
+    /// <param name="ignoreLayers"></param>
+    public void GetRawBBCorners(GameObject target, LayerMask ignoreLayers)
+    {
+        targetObject = target;
+
+        GameObject clone = GameObject.Instantiate(targetObject);
+        clone.transform.localRotation = Quaternion.identity;
+        clone.transform.position = Vector3.zero;
+        clone.transform.localScale = new Vector3(1, 1, 1);
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs]: nit `Vector3.one`

File: Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs [hunk 7]
```diff
@@ -0,0 +1,327 @@
...
+    /// this function gets the indices of the bounding cube corners that make up a face.
+    /// </summary>
+    /// <param name="index">the face index of the bounding cube 0-5</param>
+    /// <returns>an array of four integer indices</returns>
+    public int[] GetFaceIndices(int index)
+    {
+        switch (index)
+        {
+            case 0:
+                return new int[] { 0, 1, 3, 2 };
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs]: we could make these readonly fields so we don't have to allocate new arrays each time.

File: Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs [hunk 8]
```diff
@@ -0,0 +1,327 @@
...
+                return new int[] { 5, 4, 6, 7 };
+            case 3:
+                return new int[] { 4, 0, 2, 6 };
+            case 4:
+                return new int[] { 6, 2, 3, 7 };
+            case 5:
+                return new int[] { 1, 0, 4, 5};
+        }
+
+        return new int[0];
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs]: same here.

File: Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs [hunk 9]
```diff
@@ -0,0 +1,327 @@
...
+
+    /// <summary>
+    /// This function returns the midpoints of each of the edges of the face of the bounding box
+    /// </summary>
+    /// <param name="index">the index of the face of the bounding cube- 0-5</param>
+    /// <returns>four Vector3 points</returns>
+    public Vector3[] GetFaceEdgeMidpoints(int index)
+    {
+        Vector3[] corners = GetFaceCorners(index);
+        Vector3[] midpoints = new Vector3[4];
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs]: this could also be a readonly field if we're only ever updating the same 4 array values.

File: Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs [hunk 10]
```diff
@@ -0,0 +1,327 @@
...
+        {
+            Vector3[] face = new Vector3[4];
+            face[0] = worldBoundingCorners[faceIndices[0]];
+            face[1] = worldBoundingCorners[faceIndices[1]];
+            face[2] = worldBoundingCorners[faceIndices[2]];
+            face[3] = worldBoundingCorners[faceIndices[3]];
+            return face;
+        }
+
+        return new Vector3[0];
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs]: could be a cached readonly array

File: Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs [hunk 11]
```diff
@@ -0,0 +1,327 @@
...
+    /// </summary>
+    /// <param name="lookAtPoint">the world coordinate to test which face is desired</param>
+    /// <returns>an integer representing the index of the bounding box faces</returns>
+    public int GetIndexOfForwardFace(Vector3 lookAtPoint)
+    {
+        int highestDotIndex = -1;
+        float hightestDotValue = float.MinValue;
+        for (int i = 0; i < 6; ++i)
+        {
+            Vector3 a = (lookAtPoint - GetFaceCentroid(i) ).normalized;
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs]: some strange formatting on this line.

File: Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs [hunk 12]
```diff
@@ -0,0 +1,327 @@
...
+    /// </summary>
+    /// <param name="target">The gameObject whose bounding box is desired</param>
+    /// <param name="boundsPoints">the array of 8 points that will be filled</param>
+    /// <param name="ignoreLayers">a LayerMask variable</param>
+    public static void GetNonAABoundingBoxCornerPositions(GameObject target, List<Vector3> boundsPoints, LayerMask ignoreLayers)
+    {
+        GameObject clone = GameObject.Instantiate(target);
+        clone.transform.localRotation = Quaternion.identity;
+        clone.transform.position = Vector3.zero;
+        clone.transform.localScale = new Vector3(1, 1, 1);
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs]: nit: `vector3.one`

File: Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs [hunk 13]
```diff
@@ -0,0 +1,327 @@
...
+
+    /// <summary>
+    /// This is the static function to call to get the non-Axis-aligned bounding box corners one time only.
+    /// Use this function if the calling object only needs the info once. To get an updated boundingbox use the
+    /// function above---UpdateNonAABoundingBoxCornerPositions(...);
+    /// </summary>
+    /// <param name="target">The gameObject whose bounding box is desired</param>
+    /// <param name="boundsPoints">the array of 8 points that will be filled</param>
+    /// <param name="ignoreLayers">a LayerMask variable</param>
+    public static void GetNonAABoundingBoxCornerPositions(GameObject target, List<Vector3> boundsPoints, LayerMask ignoreLayers)
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs]: It seems like we have a lot of duplicated code that does almost identical things.

Could consolidate these?

Comment (johnppella) [reply Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs]: yes- great idea! both the main functions can share a new static function that does the bulk of the calculations.

**Comment by johnppella** [comment]
pushed more changes- including moving duplicated code into static function

File: Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs [hunk 14]
```diff
@@ -0,0 +1,332 @@
...
+
+/// <summary>
+/// The BoundingBoxHelper class contains functions for getting geometric info from the non-axis-aligned 
+/// bounding box of a GameObject. These functions can be used to align another object to the center of
+/// a certain face or the center of an edge of a face... etc.
+/// The BoundingBoxHelper static function can be used for a one time calculation.
+/// The dynamic functions can be used to obtain boundingcube info on an object's Update loop. Operations
+/// are minimized in the dynamic use scenario.
+/// </summary>
+public class BoundingBoxHelper : MonoBehaviour
```
Comment (keveleigh) [inline Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs]: Does this need to be a MonoBehaviour? Its [only use](https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2212/files#diff-cca878975ff11b2420bc1b4d7e52b8baR249) is with the 'new' keyword, which causes a Unity warning.

image

**Comment by ThomasAstrakhan** [comment]
I tried to use this fix (#2042) in my project. 

It seems I can't scale an object with the appbar moving along when the mesh is chlidren of the BoundingBoxRig anymore.

Project 1 : 
I have the old BoundingBoxRig on an object named "Model_Icosa". I am scaling the children "Platonic".

oldbbchild

This is the result :

oldbb


Project 2 : I have the fixed BoundingBoxRig on an object named "GameObject". I am scaling the children "Cube".

newbbchild


this is the result : 

newbb

File: Assets/HoloToolkit/UX/Scripts/AppBar/AppBar.cs [hunk 15]
```diff
@@ -35,6 +35,24 @@ public class AppBar : InteractionReceiver
         /// </summary>
         public float HoverOffsetZ = 0f;
 
+        private bool useTightFollow = false;
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/UX/Scripts/AppBar/AppBar.cs]: missing tooltip with summary description.

File: Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs (hunk 14 above)
Comment (StephenHodgson) [inline Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs]: Why isn't this class in a namespace?

Comment (keveleigh) [reply Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs]: It's also in Utilities, while the rest of bounding box is in UX.

Comment (davidkline-ms) [reply Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs]: This was merged a month ago.... Please open a new issue so we can track the needed change(s)
