### PR TITLE
MRTK Xbox Controller & Motion Controller reconciliation

### LINKED ISSUE #1199: XboxControllerInputSource throwing IndexOutOfRangeException/ NullReferenceException
The XboxControllerInputSource throws IndexOutOfRangeException because the default for the mapping array seems to be 0 items. Interestingly enough, the array is initialized to 20 entrys in the XBoxControllerExample scene, so it works. But it fails with a NullReferenceException after calling reset on the script in the inspector. When checking the "Use Custom mapping" button to show the entries, they're all there, based on the number of elements of the serialized mapping array. The serialized info seems to be not propagated to the actual array.

### LINKED ISSUE #1414: Removing GamepadInput.cs from InputManager.prefab breaks Xbox gamepad support
## Overview
I understand new events were added for Xbox gamepad but GamepadInput.cs maps A to InputManager air tap. This is now all broken unless I write special code.

## Expected Behavior
Gamepad just works with HTK input manager.

## Actual Behavior
Its broken.

## Steps to reproduce
Use GamepadTest.unity and it does not work.

FIX:
Re-add GamepadInput.cs to GesturesInput under InputManager prefab.

### PR DESCRIPTION
**Pull request by StephenHodgson**
Overview
---
So after some thought and consideration, I thought it best to just not use the Editor Axis mappings for the Motion Controllers at all.  Instead we will always get our Motion Controller data from the `UnityEngine.XR.WSA.Input.IneractionManager` and only handle Xbox Controller input via axis/button mappings.

I decided to leave the axis mappings as is for now, in case Unity ever gets around to fixing it and users decide that's what they'd rather use.

I've cleaned up and refactored the Xbox input source to be easier to extend and get button/axis data out of.  I also included a handler base class that users can extend from to handle game pad input exactly like the old `GamepadInput.cs` class did.

Changes
---
- Fixes: #1078
- Fixes #1414 
- Fixes #1199

Breaking Changes
---
- Removed `GamePadEventData` from `InputManager` and marked it Obsolete.
- `XboxControllerEventData` now inherits from `SourceStateEventData`.

### CODE REVIEW

File: Assets/HoloToolkit/Input/Scripts/InputSources/GamepadInput.cs [hunk 1]
```diff
@@ -15,12 +15,12 @@
...
 {
     /// <summary>
-    /// GamepadInput class maps Xbox gamepad buttons to the GestureRecognizer.
+    /// GamepadInput class maps Xbox GamePad buttons to the GestureRecognizer.
     /// Gamepad button A press and release maps to tap gesture.
     /// Gamepad button A pressed maps to hold started, completed, canceled gesture.
     /// Gamepad button A pressed plus left joystick rotate maps to navigation gesture.
     /// </summary>
-    [Obsolete("Please use GamePadInputSource or XboxControllerInputSource")]
+    [Obsolete("Please use XboxControllerHandlerBase")]
```
Comment (NeerajW) [inline Assets/HoloToolkit/Input/Scripts/InputSources/GamepadInput.cs]: I frankly don't understand why the complicated new class for something simple like this. So I need to now implement interfaces to handle GamePad which previously just worked?

Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/InputSources/GamepadInput.cs]: Yes, because if you weren't implementing the interfaces you were not handling the input correctly.

This new class isn't intended to complicate, and this isn't just something trivial to add onto the `InputManager.prefab` that doesn't follow the appropriate implementation patterns.

Comment (NeerajW) [reply Assets/HoloToolkit/Input/Scripts/InputSources/GamepadInput.cs]: Then GamepadInput.cs cannot be marked obsolete. We have to keep the simple implementation working for everyone.

Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/InputSources/GamepadInput.cs]: The new, simple implementation is `XboxControllerHandlerBase`

Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/InputSources/GamepadInput.cs]: For the most part the underlying logic is the same, with the difference here being that we're handling the input properly though the interface.

image

The important thing here is customization of the `Select` and `Horizontal Navigation Axis` that were hard coded previously.  Now users can map their own with easy dropdowns.  Because of the updated code structure, devs can now inherit directly from this class and implement their own additional logic on top of the standard inputs.

**Comment by StephenHodgson** [comment]
@NeerajW Adding a note here to add default `XboxControllerInputSource` to `InputManager.prefab` as we discussed in the Shiproom Meeting.

**Comment by NeerajW** [comment]
Wait what happened here? I thought I approved this?

**Comment by StephenHodgson** [comment]
I had some conflicts and updated the InputManager.prefab like requested.

File: Assets/HoloToolkit/Input/Scripts/GamePad/XboxController/XboxControllerMapping.cs [hunk 2]
```diff
@@ -84,67 +104,187 @@ public static void SetMapping(XboxControllerMappingTypes type, string value)
...
-                    XboxView = string.IsNullOrEmpty(value) ? "CONTROLLER_LEFT_MENU" : value;
+                    XboxView = string.IsNullOrEmpty(value) ? CONTROLLER_LEFT_MENU : value;
                     break;
                 case XboxControllerMappingTypes.XboxMenu:
-                    XboxMenu = string.IsNullOrEmpty(value) ? "CONTROLLER_RIGHT_MENU" : value;
+                    XboxMenu = string.IsNullOrEmpty(value) ? CONTROLLER_RIGHT_MENU : value;
                     break;
                 case XboxControllerMappingTypes.XboxLeftBumper:
-                    XboxLeftBumper = string.IsNullOrEmpty(value) ? "XBOX_LEFT_BUMPER" : value;
+                    XboxLeftBumper = string.IsNullOrEmpty(value) ? CONTROLLER_LEFT_BUMPER_OR_GRIP : value;
```
Comment (keveleigh) [inline Assets/HoloToolkit/Input/Scripts/GamePad/XboxController/XboxControllerMapping.cs]: I'm getting an ArgumentException with this change, since it doesn't look like these axes were updated in InputManager.asset as well.

File: Assets/HoloToolkit/Input/Scripts/GamePad/XboxController/XboxControllerHandlerBase.cs [hunk 3]
```diff
@@ -2,131 +2,187 @@
 // Licensed under the MIT License. See LICENSE in the project root for license information.
 
 using System;
+using System.Collections;
 using UnityEngine;
 
 namespace HoloToolkit.Unity.InputModule
 {
-    public class XboxControllerHandlerBase : MonoBehaviour, IXboxControllerHandler
+    public class XboxControllerHandlerBase : GamePadHandlerBase, IXboxControllerHandler
```
Comment (keveleigh) [inline Assets/HoloToolkit/Input/Scripts/GamePad/XboxController/XboxControllerHandlerBase.cs]: Was this supposed to be added to the InputManager, to replace GamepadInput.cs? I don't see it.

File: Assets/HoloToolkit/Input/Scripts/GamePad/XboxController/XboxControllerMapping.cs (hunk 2 above)
Comment (keveleigh) [reply Assets/HoloToolkit/Input/Scripts/GamePad/XboxController/XboxControllerMapping.cs]: Which also means they should be updated in the Add Input Manager Axes menu

File: Assets/HoloToolkit/Input/Scripts/GamePad/XboxController/XboxControllerHandlerBase.cs (hunk 3 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/GamePad/XboxController/XboxControllerHandlerBase.cs]: `GamePadHandlerBase` itself wasn't, but the `XboxControllerHandlerBase` was and it inherits from this class

File: Assets/HoloToolkit-Examples/Input/Scenes/XboxControllerExample.unity [hunk 4]
```diff
@@ -180,9 +180,8 @@ Transform:
   m_LocalScale: {x: 1, y: 1, z: 1}
```
Comment (keveleigh) [inline Assets/HoloToolkit-Examples/Input/Scenes/XboxControllerExample.unity]: Should this scene work when running in the editor? Hitting play and having a controller connected (I'm using it via USB) always shows `No Controller Connected`, even when I can teleport and such with the controller.

Comment (StephenHodgson) [reply Assets/HoloToolkit-Examples/Input/Scenes/XboxControllerExample.unity]: Are you using an older Xbox or the Xbox one S?

File: Assets/HoloToolkit/Input/Scripts/GamePad/XboxController/XboxControllerMapping.cs (hunk 2 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/GamePad/XboxController/XboxControllerMapping.cs]: Good catch.

I was trying to keep in sync with your axis manager, but these must have gotten past me.

File: Assets/HoloToolkit-Examples/Input/Scenes/XboxControllerExample.unity (hunk 4 above)
Comment (keveleigh) [reply Assets/HoloToolkit-Examples/Input/Scenes/XboxControllerExample.unity]: Xbox One S

File: Assets/HoloToolkit/Input/Scripts/GamePad/XboxController/XboxControllerHandlerBase.cs (hunk 3 above)
Comment (keveleigh) [reply Assets/HoloToolkit/Input/Scripts/GamePad/XboxController/XboxControllerHandlerBase.cs]: Hmm, I don't see `XboxControllerHandlerBase` in the prefab, just `XboxControllerInputSource`.

File: Assets/HoloToolkit-Examples/Input/Scenes/XboxControllerExample.unity (hunk 4 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit-Examples/Input/Scenes/XboxControllerExample.unity]: So the input still works even though it says no controller connected?

File: Assets/HoloToolkit/Input/Scripts/GamePad/XboxController/XboxControllerHandlerBase.cs (hunk 3 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/GamePad/XboxController/XboxControllerHandlerBase.cs]: I'll double check.

File: Assets/HoloToolkit-Examples/Input/Scenes/XboxControllerExample.unity (hunk 4 above)
Comment (keveleigh) [reply Assets/HoloToolkit-Examples/Input/Scenes/XboxControllerExample.unity]: I'm able to teleport, but I'm not able to do anything with the cube (should I be?)

Comment (keveleigh) [reply Assets/HoloToolkit-Examples/Input/Scenes/XboxControllerExample.unity]: Interestingly, I do get a debug statement
image

Comment (StephenHodgson) [reply Assets/HoloToolkit-Examples/Input/Scenes/XboxControllerExample.unity]: Seems like the scene may have gotten messed up in a merge. I'll double check this stuff later today.

Comment (StephenHodgson) [reply Assets/HoloToolkit-Examples/Input/Scenes/XboxControllerExample.unity]: Should be fixed now.

File: Assets/HoloToolkit/Input/Scripts/GamePad/XboxController/XboxControllerHandlerBase.cs (hunk 3 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/GamePad/XboxController/XboxControllerHandlerBase.cs]: Fixed.

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs [hunk 5]
```diff
@@ -27,16 +27,28 @@ namespace HoloToolkit.Unity.InputModule
...
-        public string LeftThumbstickY = "CONTROLLER_LEFT_STICK_VERTICAL";
+        public XboxControllerMappingTypes VerticalStrafe = XboxControllerMappingTypes.XboxLeftStickVertical;
 
         [Tooltip("Name of the thumbstick axis to check for rotation.")]
-        public string RightThumbstickX = "CONTROLLER_RIGHT_STICK_HORIZONTAL";
+        public XboxControllerMappingTypes HorizontalRotation = XboxControllerMappingTypes.XboxRightStickHorizontal;
 
         [Tooltip("Name of the thumbstick axis to check for rotation.")]
-        public string RightThumbstickY = "CONTROLLER_RIGHT_STICK_VERTICAL";
+        public XboxControllerMappingTypes VerticalRotation = XboxControllerMappingTypes.XboxRightStickVertical;
```
Comment (keveleigh) [inline Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: We don't have vertical rotation set up. The right stick's Y is used for intent checking when the right stick's X is within range to trigger a rotation, that it's mostly in a right/left direction.

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs [hunk 6]
```diff
@@ -27,16 +27,28 @@ namespace HoloToolkit.Unity.InputModule
     public class MixedRealityTeleport : Singleton<MixedRealityTeleport>, IControllerInputHandler
     {
         [Tooltip("Name of the thumbstick axis to check for teleport and strafe.")]
-        public string LeftThumbstickX = "CONTROLLER_LEFT_STICK_HORIZONTAL";
+        public XboxControllerMappingTypes HorizontalStrafe = XboxControllerMappingTypes.XboxLeftStickHorizontal;
 
         [Tooltip("Name of the thumbstick axis to check for teleport and strafe.")]
-        public string LeftThumbstickY = "CONTROLLER_LEFT_STICK_VERTICAL";
+        public XboxControllerMappingTypes VerticalStrafe = XboxControllerMappingTypes.XboxLeftStickVertical;
```
Comment (keveleigh) [inline Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: "Vertical strafe" makes me think of going upwards, but the left stick is only used for side to side and backwards strafing.

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs [hunk 7]
```diff
@@ -27,16 +27,28 @@ namespace HoloToolkit.Unity.InputModule
...
         [Tooltip("Name of the thumbstick axis to check for rotation.")]
-        public string RightThumbstickX = "CONTROLLER_RIGHT_STICK_HORIZONTAL";
+        public XboxControllerMappingTypes HorizontalRotation = XboxControllerMappingTypes.XboxRightStickHorizontal;
 
         [Tooltip("Name of the thumbstick axis to check for rotation.")]
-        public string RightThumbstickY = "CONTROLLER_RIGHT_STICK_VERTICAL";
+        public XboxControllerMappingTypes VerticalRotation = XboxControllerMappingTypes.XboxRightStickVertical;
+
+        [Tooltip("Custom Input Mapping for horizontal teleport and strafe")]
+        public string LeftThumbstickX = InputMappingAxisUtility.CONTROLLER_LEFT_STICK_HORIZONTAL;
```
Comment (keveleigh) [inline Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: Do we need all these things seemingly mapped twice? HorizontalStrafe <-> LeftThumbstickX, HorizontalRotation <-> RightThumbstickX etc.

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs [hunk 8]
```diff
@@ -27,16 +27,28 @@ namespace HoloToolkit.Unity.InputModule
...
+
+        [Tooltip("Custom Input Mapping for vertical teleport and strafe")]
+        public string LeftThumbstickY = InputMappingAxisUtility.CONTROLLER_LEFT_STICK_VERTICAL;
+
+        [Tooltip("Custom Input Mapping for horizontal rotation")]
+        public string RightThumbstickX = InputMappingAxisUtility.CONTROLLER_RIGHT_STICK_VERTICAL;
```
Comment (keveleigh) [inline Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: This should be `InputMappingAxisUtility.CONTROLLER_RIGHT_STICK_HORIZONTAL`

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs [hunk 9]
```diff
@@ -27,16 +27,28 @@ namespace HoloToolkit.Unity.InputModule
...
+
+        [Tooltip("Custom Input Mapping for vertical rotation")]
+        public string RightThumbstickY = InputMappingAxisUtility.CONTROLLER_RIGHT_STICK_HORIZONTAL;
```
Comment (keveleigh) [inline Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: This should be `InputMappingAxisUtility.CONTROLLER_RIGHT_STICK_VERTICAL`

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs [hunk 10]
```diff
@@ -49,6 +61,9 @@ public class MixedRealityTeleport : Singleton<MixedRealityTeleport>, IController
         private GameObject teleportMarker;
         private Animator animationController;
 
+        [SerializeField]
+        private bool useCustomMapping;
```
Comment (keveleigh) [inline Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: What does this do? I don't see it used anywhere.

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 6 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: Forward better?

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 5 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: If it wasn't setup then why was it mapped?

Should we remove it/implement it?

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 7 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: It's for custom mappings.

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 8 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: Great catch!

Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: So it's backwards?  I used the mapping from prev version.

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 9 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: So it's backwards? I used the mapping from prev version.

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 10 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: Its for custom input mappings. Similar to the `XboxControllerInputSource`.

It keeps this component backwards capable in case people don't want to use the new input mappings.

Comment (keveleigh) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: Where is it used?

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 8 above)
Comment (keveleigh) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: Yeah, it's backwards from the previous version.

image

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 9 above)
Comment (keveleigh) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: Yeah, it's backwards from the previous version.

image

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 5 above)
Comment (keveleigh) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: > The right stick's Y is used for intent checking when the right stick's X is within range to trigger a rotation, that it's mostly in a right/left direction.

It's used to make sure the stick isn't too high or low when pressed to the left or right, to try to filter out false positives.

https://github.com/StephenHodgson/MixedRealityToolkit-Unity/blob/49133ed42330ec96674caaa7e5ce6a8fc2901c6e/Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs#L171

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 6 above)
Comment (keveleigh) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: Yeah, forward sounds better to me

**Comment by StephenHodgson** [comment]
@keveleigh I now properly use `useCustomMapping` in the class.

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 10 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: It's now properly used in the last update.

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 5 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: So what should the proper name be?

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 7 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: Also so there's not any breaking changes.

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 10 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: Oh I also somehow forgot to add the new editor inspector script for this class.  One sec.

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 7 above)
Comment (keveleigh) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: Should `useCustomMapping` be true by default to prevent the breaking change? Otherwise it uses the new mappings by default, if I'm understanding correctly.

Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: No, it's not a breaking change because the string value isn't different, and the value serialized in the prefab isn't any different either.

Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: image
image

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 5 above)
Comment (keveleigh) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: Good question. I'm not completely convinced the drop-downs here will work, since they're used for more than just one thing.

Thumbstick X is used for both teleporting forward and preventing false positives on the Thumbstick Y strafing.

Thumbstick Y is used for horizontal strafing and preventing false positives on the Thumbstick X teleporting forward. 

If I set the new Horizontal Strafe to `Xbox Left Stick Horizontal` and Forward Movement to `Xbox Dpad Vertical`, the false positive detection becomes useless.
Of course, maybe we don't really need it! If the horizontal strafe values are set to values that physically can't be returned once the thumbstick is at a certain vertical value, those checks aren't needed anyway.

Additionally, if I map `Horizontal Strafe` to something that isn't a (-1,1) axis, like `Xbox A`, it strafes me to the right on every press, with no way to go left, but hopefully that's something the dev will be able to figure out isn't supported.

Hmm, also using `Xbox Dpad Vertical` in my scenario above would break teleporting with motion controllers, since they don't have a Dpad. That's why we defaulted to only using thumbsticks (and that it matches the shell).

One last thought I had is that all of these options start with "Xbox", which might be misleading, since they're used for the motion controller teleporting as well.

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 7 above)
Comment (keveleigh) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: If I've changed the string axes to my own custom values already, this will break me.

File: Assets/HoloToolkit/Input/Scripts/Editor/MixedRealityTeleportEditor.cs [hunk 11]
```diff
@@ -0,0 +1,67 @@
...
+            {
+                EditorGUILayout.TextField("Horizontal Strafe", mixedRealityTeleport.LeftThumbstickX);
+                EditorGUILayout.TextField("Forward Movement", mixedRealityTeleport.LeftThumbstickY);
+                EditorGUILayout.TextField("Horizontal Rotation", mixedRealityTeleport.RightThumbstickX);
+                EditorGUILayout.TextField("Rotation", mixedRealityTeleport.RightThumbstickY);
+            }
+            else
+            {
+                EditorGUILayout.EnumPopup("Horizontal Strafe", mixedRealityTeleport.HorizontalStrafe);
+                EditorGUILayout.EnumPopup("Forward Movement", mixedRealityTeleport.HorizontalStrafe);
```
Comment (keveleigh) [inline Assets/HoloToolkit/Input/Scripts/Editor/MixedRealityTeleportEditor.cs]: These are all set to `mixedRealityTeleport.HorizontalStrafe`

Comment (keveleigh) [reply Assets/HoloToolkit/Input/Scripts/Editor/MixedRealityTeleportEditor.cs]: Looks like you fixed already :)

Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Editor/MixedRealityTeleportEditor.cs]: Haha yeah, I forgot to stage it somehow.

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 5 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: I thought about renaming the Enum but I didn't want to introduce another breaking change.

Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: Essentially I'm trying to add customization to the component.

Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: Do you think these values should be hard coded?

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 7 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: Shouldn't if your serialization is saved in the scene and not your prefab

File: Assets/HoloToolkit/Input/Scripts/Editor/MixedRealityTeleportEditor.cs [hunk 12]
```diff
@@ -0,0 +1,67 @@
...
+                mixedRealityTeleport.LeftThumbstickX = EditorGUILayout.TextField("Horizontal Strafe", mixedRealityTeleport.LeftThumbstickX);
+                mixedRealityTeleport.LeftThumbstickY = EditorGUILayout.TextField("Forward Movement", mixedRealityTeleport.LeftThumbstickY);
+                mixedRealityTeleport.RightThumbstickX = EditorGUILayout.TextField("Horizontal Rotation", mixedRealityTeleport.RightThumbstickX);
+                mixedRealityTeleport.RightThumbstickY = EditorGUILayout.TextField("Rotation", mixedRealityTeleport.RightThumbstickY);
+            }
+            else
+            {
+                mixedRealityTeleport.HorizontalStrafe = (XboxControllerMappingTypes)EditorGUILayout.EnumPopup("Horizontal Strafe", mixedRealityTeleport.HorizontalStrafe);
+                mixedRealityTeleport.ForwardMovement = (XboxControllerMappingTypes)EditorGUILayout.EnumPopup("Forward Movement", mixedRealityTeleport.ForwardMovement);
+                mixedRealityTeleport.VerticalRotation = (XboxControllerMappingTypes)EditorGUILayout.EnumPopup("Horizontal Rotation", mixedRealityTeleport.VerticalRotation);
```
Comment (keveleigh) [inline Assets/HoloToolkit/Input/Scripts/Editor/MixedRealityTeleportEditor.cs]: Looks like the `mixedRealityTeleport.VerticalRotation` and `mixedRealityTeleport.HorizontalRotation` labels are swapped.

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 7 above)
Comment (keveleigh) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: But the `useCustomMappings` flag being set to false by default will ignore that serialization and instead use the drop-downs by default.

Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: I've got an idea about how to fix this. One Sec.

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 10 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: Checkout 8ed07d0

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 7 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: Checkout 8ed07d0

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 5 above)
Comment (keveleigh) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: Hmm, good point. In this case, we tailored the experience to match the shell, but it's possible devs would want to use buttons or other inputs instead of the thumbstick. I'm not sure they'd want to use different values though, since they're basically "is the thumbstick pushed forward/left/right/etc".

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 7 above)
Comment (keveleigh) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: That seems overly complicated vs setting `useCustomMappings` to true by default. Is there a reason we shouldn't do that?

If I've previously used the custom mappings, but want to switch to using the drop-downs, I'll have to reset my custom mappings exactly or this will switch me over every time I load the project.

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 5 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: I think any mapped input that is an Axis should be valid for this type of input.

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 7 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: It's better for users to see the enum.  Simpler and more straight forward.

Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: Trying to keep the newb in mind

Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: >If I've previously used the custom mappings, but want to switch to using the drop-downs, I'll have to reset my custom mappings exactly or this will switch me over every time I load the project.

If you reset the prefab or remove the custom mapping completely and leave an empty field it will not do this.

Comment (keveleigh) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: Yeah. Needing to reset the axes exactly is a minor inconvenience for those benefits

**Comment by keveleigh** [comment]
One final thing: it might be worth disabling teleport and strafe in the XboxControllerExample scene, since those axes are also used for manipulating the cube. Otherwise, looks good!

File: Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs (hunk 7 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: I could also add a simple reset button that will fix that too

Comment (keveleigh) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: > But it's essentially the same as just resetting the component.

Agreed. Could be a good addition later, but I don't consider that blocking. There are definitely other ways to reset.

Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: I thought about making it so when you switch to the drop downs it would reset the string values, but I thought that was too intrusive, in case you wanted to switch back.

Comment (keveleigh) [reply Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs]: Agreed, if I'm just unchecking the box to see what it does.

**Comment by StephenHodgson** [comment]
If you're just playing in the editor without a headset it's a problem, but I didn't notice that right away!
