### PR TITLE
Enhanced Keyboard, fixed dictation, feedback on dictation actually doing something

### LINKED ISSUE #976: Keyboard OnDictationResult not updating InputField
When attempting to use voice commands to input text with the new Keyboard, the InputField does not appear to update with the text.

I put breakpoints in the function:

```
 private void OnDictationResult(string text, ConfidenceLevel confidence)
        {
            if (text != null)
            {
                m_InputField.text.Insert(m_InputField.caretPosition, text);
                m_InputField.caretPosition += text.Length;
            }
        }

```

and verified it is making these calls without exceptions, the text string is correctly populated, but the text never appears in the input field. The input field is properly mapped in the inspector.

I am using Unity 2017.1.0f3

### PR DESCRIPTION
**Pull request by LocalJoost**
Overview
Fixed keyboard dictation button - now actually shows some feedback, and recognized text is properly inserted. Some UI enhancements as well

Changes
- Dictation now works
- Dictation button is red when dictation is active
- Keyboard automatically closes after a set time of inactivity
- Includes method to set scaling from the outside by code
- Includes method to set scaling from the outside by code
- Text inside text field is bigger so it's actually readable
- Remove ray cast hit from input field and prevent activation, as this brings up the SYSTEM keyboard in MR (not in HL)

This code is successfully deployed in Walk the World for both HoloLens and Immersive headsets

Fixes #976

### CODE REVIEW

**Comment by LocalJoost** [comment]
That is exactly what I am doing but OUTSIDE of this class. As this class doesn't automatically can start phrase recognition, shutting it DOWN automatically is wrong as well. That could go in a sample scene. Not in this class.

Joost van Schaik

Windows Development MVP

"The world as I envision it in my head is such a more interesting place"

________________________________

**Comment by StephenHodgson** [comment]
That's what I'm trying to say.  We should using the IDictationHandler.

**Comment by LocalJoost** [comment]
You completely lost me here

Joost van Schaik

Windows Development MVP
Sent from mail for Windows 10

"The world as I envision it in my head is such a more interesting place"

________________________________

**Comment by StephenHodgson** [comment]
No worries, I'll open a PR on your branch with the requested changes.

Btw, thank you for doing this! It was sorely needed!

**Comment by LocalJoost** [comment]
Stephen, since you apparently were occupied elsewhere I took a look at the PR myself and added improvements as per your remarks

File: Assets/HoloToolkit/UX/Scripts/Keyboard.cs [hunk 1]
```diff
@@ -682,7 +687,7 @@ public void FunctionKey(KeyboardKeyFunc functionKey)
                 case KeyboardKeyFunc.Function.Dictate:
                     {
 #if UNITY_WSA || UNITY_STANDALONE_WIN
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/UX/Scripts/Keyboard.cs]: Do we still need these symbol declarations?

**Comment by LocalJoost** [comment]
We don't. Deleted those, as well as some other superfluous stuff I noticed when combing the code again

File: Assets/HoloToolkit/UX/Scripts/Keyboard.cs [hunk 2]
```diff
@@ -21,7 +18,7 @@ namespace HoloToolkit.UI.Keyboard
     ///       To retrieve the input from the Keyboard, subscribe to the textEntered event. Note that
     ///       tapping 'Close' on the Keyboard will not fire the textEntered event. You must tap 'Enter' to
     ///       get the textEntered event.
-    public class Keyboard : Singleton<Keyboard>
+    public class Keyboard : Singleton<Keyboard>, IDictationHandler
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/UX/Scripts/Keyboard.cs]: Since this is a Singleton, does it makes sense to rename this to `VirtualKeyboardManager`?
The name also implies that it would handle regular keyboard input as well, when it doesn't.

Thoughts?

File: Assets/HoloToolkit/UX/Scripts/Keyboard.cs [hunk 3]
```diff
@@ -218,10 +234,48 @@ protected override void Awake()
...
+
+
             // Keep keyboard deactivated until needed
             gameObject.SetActive(false);
         }
 
+        /// <summary>
+        /// Recursive find. Potentially move to a child class.
+        /// </summary>
+        GameObject RecursiveFindChild(Transform parent, string childName)
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/UX/Scripts/Keyboard.cs]: This could be a GameObject Extension method.  I wonder if something similar already exists?
I'll take a look.

File: Assets/HoloToolkit/UX/Scripts/Keyboard.cs [hunk 4]
```diff
@@ -218,10 +234,48 @@ protected override void Awake()
             RectTransform rect = GetComponent<RectTransform>();
             m_ObjectBounds = new Vector3(canvasBounds.size.x * rect.localScale.x, canvasBounds.size.y * rect.localScale.y, canvasBounds.size.z * rect.localScale.z);
 
+            // Actually find microphone key in the keyboard
+            var dicationButton = RecursiveFindChild(gameObject.transform, "Dictation");
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/UX/Scripts/Keyboard.cs]: Why not assign this object in the inspector, so we don't have to look it up each time?

File: Assets/HoloToolkit/UX/Scripts/Keyboard.cs [hunk 5]
```diff
@@ -807,6 +907,23 @@ public void Clear()
...
+        /// <summary>
+        /// Method to set the sizes by code, as the properties are private. 
+        /// Useful for scaling 'from the outside', for instance taking care of differences between
+        /// immersive headsets and HoloLens
+        /// </summary>
+        /// <param name="minScale">Min scale factor</param>
+        /// <param name="maxScale">Max scale factor</param>
+        /// <param name="minDistance">Min distance from camera</param>
+        /// <param name="maxDistance">Max distance from camera</param>
+        public void SetScaleSizeValues( float minScale, float maxScale, float minDistance, float maxDistance)
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/UX/Scripts/Keyboard.cs]: Should we also move this to a utility class?  Seems pretty handy.

File: Assets/HoloToolkit/UX/Scripts/Keyboard.cs [hunk 6]
```diff
@@ -901,5 +1018,42 @@ private void ResetKeyboardState()
...
+
+        /// <summary>
+        /// Respond to keyboard activity: reset timeout timer, play sound
+        /// </summary>
+        private void IndicateActivty()
+        {
+            ResetClosingTime();
+            if (_audioSource == null)
+            {
+                _audioSource = GetComponent<AudioSource>();
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/UX/Scripts/Keyboard.cs]: We should probably add the class attribute that requires the AudioSource component.

File: Assets/HoloToolkit/UX/Scripts/Keyboard.cs (hunk 4 above)
Comment (LocalJoost) [reply Assets/HoloToolkit/UX/Scripts/Keyboard.cs]: Lookup is only used at Awake, so once in every time it starts

File: Assets/HoloToolkit/UX/Scripts/Keyboard.cs (hunk 2 above)
Comment (LocalJoost) [reply Assets/HoloToolkit/UX/Scripts/Keyboard.cs]: Possibly. I personally am not very much in favor of name changes as they brake code

File: Assets/HoloToolkit/UX/Scripts/Keyboard.cs (hunk 6 above)
Comment (LocalJoost) [reply Assets/HoloToolkit/UX/Scripts/Keyboard.cs]: I do not agree. The audio source could be attached to the keyboard and spatialized so clicking actually comes *FROM* the keyboard. That is how I use it.

File: Assets/HoloToolkit/UX/Scripts/Keyboard.cs (hunk 2 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/UX/Scripts/Keyboard.cs]: Shouldn't be an issue here since we use a prefab, and the GUID will map the updated component.

We could also add another class definition above that uses the old name and mark the old name obsolete in case someone was referencing it before.

Comment (LocalJoost) [reply Assets/HoloToolkit/UX/Scripts/Keyboard.cs]: True that. I am using some of the new public methods I introduced, so renaming will break only one application - mine ;) . But I can live with that

File: Assets/HoloToolkit/UX/Scripts/Keyboard.cs (hunk 3 above)
Comment (LocalJoost) [reply Assets/HoloToolkit/UX/Scripts/Keyboard.cs]: You are right. There is a Utils.GetChildRecursive. Apparently I did not search well enough when I added this. Updated the PR to use that method and removed mine from Keyboard.cs

File: Assets/HoloToolkit/UX/Scripts/Keyboard.cs [hunk 7]
```diff
@@ -901,5 +995,42 @@ private void ResetKeyboardState()
         }
 
         #endregion Keyboard Layout Modes
+
+        /// <summary>
+        /// Respond to keyboard activity: reset timeout timer, play sound
+        /// </summary>
+        private void IndicateActivty()
```
Comment (keveleigh) [inline Assets/HoloToolkit/UX/Scripts/Keyboard.cs]: typo in method name: `Activty` -> `Activity`

File: Assets/HoloToolkit/UX/Scripts/Keyboard.cs [hunk 8]
```diff
@@ -272,35 +304,61 @@ private void OnDisable()
...
+        /// Called when dictation hypothesis is found. Not used here
+        /// </summary>
+        /// <param name="eventData">Dictation event data</param>
+        public void OnDictationHypothesis(DictationEventData eventData)
+        {
+        }
+
         /// <summary>
-        /// Event fired when dictation completed.
+        /// Called when dication result is obtained
```
Comment (keveleigh) [inline Assets/HoloToolkit/UX/Scripts/Keyboard.cs]: nit typo: `dication` -> `dictation`

File: Assets/HoloToolkit/UX/Scripts/Keyboard.cs [hunk 9]
```diff
@@ -218,10 +234,25 @@ protected override void Awake()
             RectTransform rect = GetComponent<RectTransform>();
             m_ObjectBounds = new Vector3(canvasBounds.size.x * rect.localScale.x, canvasBounds.size.y * rect.localScale.y, canvasBounds.size.z * rect.localScale.z);
 
+            // Actually find microphone key in the keyboard
+            var dicationButton = Utils.GetChildRecursive(gameObject.transform, "Dictation");
```
Comment (keveleigh) [inline Assets/HoloToolkit/UX/Scripts/Keyboard.cs]: typo in variable name: `dication` -> `dictation`

File: Assets/HoloToolkit/UX/Scripts/Keyboard.cs [hunk 10]
```diff
@@ -218,10 +234,25 @@ protected override void Awake()
...
+            if (dicationButton != null)
+            {
+                var dicationIcon = dicationButton.Find("keyboard_closeIcon");
```
Comment (keveleigh) [inline Assets/HoloToolkit/UX/Scripts/Keyboard.cs]: typo in variable name: `dication` -> `dictation`

File: Assets/HoloToolkit/UX/Scripts/Keyboard.cs [hunk 11]
```diff
@@ -151,6 +148,16 @@ public enum LayoutType
         [SerializeField]
         private float m_MinDistance = 0.25f;
 
+        /// <summary>
+        /// Inactivity time that makes the keyboard disappear automatically.
+        /// </summary>
+        public float CloseOnInactivityTime = 15;
```
Comment (keveleigh) [inline Assets/HoloToolkit/UX/Scripts/Keyboard.cs]: Should this feature be locked behind a `bool` setting, in case I don't want the keyboard to close automatically?

**Comment by LocalJoost** [comment]
I am not entirely sure what happened here. I hope the PR is still okay to you now I fixed the isssues

**Comment by LocalJoost** [comment]
All right, apologies for that last one. Have no idea what happened there. I am not exactly your Git guru ;)

File: Assets/HoloToolkit/UX/Scripts/Keyboard.cs (hunk 3 above)
Comment (keveleigh) [reply Assets/HoloToolkit/UX/Scripts/Keyboard.cs]: Looks like this was removed in https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1496/commits/9fc3bade2abdc74c119d72240bff10f86fbf3ff9 but re-added in https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1496/commits/b4e89803adf6b46c6770a8df869e5e590dc262d2. That second commit seems to have reverted both the first commit I linked and https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1496/commits/0c6e01c1ebc877f93ea52585318ae6b0c02e777b. Was that intended?

**Comment by LocalJoost** [comment]
Please look further down the commits. Something went wrong with a merge, I think

Joost van Schaik

Windows Development MVP

"The world as I envision it in my head is such a more interesting place"

________________________________

**Comment by keveleigh** [comment]
@LocalJoost That comment was as of the latest commit, https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/b4e89803adf6b46c6770a8df869e5e590dc262d2, which re-added some things you previously removed, like `RecursiveFindChild` in favor of `Utils.GetChildRecursive`.

**Comment by LocalJoost** [comment]
@keveleigh You were right, of course, and I really wonder how this all came about. I guess it has something to do with my remote branch getting accidentally deleted. Anyway. I think I have now brought back everything that is supposed to be there

**Comment by keveleigh** [comment]
Looks good to me! Thanks for these fixes!

File: Assets/HoloToolkit/UX/Scripts/Keyboard.cs [hunk 12]
```diff
@@ -272,35 +307,61 @@ private void OnDisable()
...
+            ResetClosingTime();
+            SetMicrophoneDefault();
+        }
+
+        /// <summary>
+        /// Called on dictation error. Not used here.
+        /// </summary>
+        /// <param name="eventData">Dictation event data</param>
+        public void OnDictationError(DictationEventData eventData)
+        {
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/UX/Scripts/Keyboard.cs]: Should we do anything here?

File: Assets/HoloToolkit/UX/Scripts/Keyboard.cs [hunk 13]
```diff
@@ -272,35 +307,61 @@ private void OnDisable()
...
         }
 
-#if UNITY_WSA || UNITY_STANDALONE_WIN
+
+        /// <summary>
+        /// Called when dictation hypothesis is found. Not used here
+        /// </summary>
+        /// <param name="eventData">Dictation event data</param>
+        public void OnDictationHypothesis(DictationEventData eventData)
+        {
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/UX/Scripts/Keyboard.cs]: Should we be doing anything here?

Comment (keveleigh) [reply Assets/HoloToolkit/UX/Scripts/Keyboard.cs]: It might be good to display the hypothesis in the text field as we get them, [like 212 does](https://github.com/Microsoft/HolographicAcademy/blob/Holograms-212-Voice/Completed/ModelExplorer/Assets/Scripts/MicrophoneManager.cs#L119).

File: Assets/HoloToolkit/UX/Scripts/Keyboard.cs (hunk 12 above)
Comment (LocalJoost) [reply Assets/HoloToolkit/UX/Scripts/Keyboard.cs]: Well, what are you suggesting?
