### PR TITLE
Fix some AsyncCoroutineRunner related issues

### LINKED ISSUE #9863: AsyncCoroutineRunner Callable without Instance
## Describe the bug

It is possible to `Post` actions to [AsyncCoroutineRunner](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/main/Assets/MRTK/Core/Utilities/Async/Internal/AsyncCoroutineRunner.cs) that will never get executed. This is because it's possible to `Post` actions without an instance of `AsyncCoroutineRunner` ever getting created. If the instance is never created, actions will sit in the queue and never be executed. 

This issue affects any code that calls:

- [AsyncCoroutineRunner](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/main/Assets/MRTK/Core/Utilities/Async/Internal/AsyncCoroutineRunner.cs).Post
- [AwaiterExtensions](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/main/Assets/MRTK/Core/Utilities/Async/AwaiterExtensions.cs).RunOnUnityScheduler
- [AwaiterExtensions](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/main/Assets/MRTK/Core/Utilities/Async/AwaiterExtensions.cs).GetAwaiterReturnVoid
- [AwaiterExtensions](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/main/Assets/MRTK/Core/Utilities/Async/AwaiterExtensions.cs).GetAwaiter*

And possibly more.

## To reproduce

1. Setup a regular MRTK scene
2. Do NOT add `AsyncCoroutineRunner` anywhere in the scene
3. Add a script that calls any of the methods listed above
4. Note that the action gets posted to the `AsyncCoroutineRunner` but never gets executed

## Expected behavior

In my opinion, developers shouldn't need to be aware this class exists. I believe it should automatically get created, probably using `[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]`. For an example of this pattern, please see my own [CoroutineRunner](https://github.com/jbienzms/ThreadUtils/blob/main/CoroutineRunner.cs) class in my [ThreadUtils](https://github.com/jbienzms/ThreadUtils) project.

If the team doesn't agree with auto-creating this instance, that's OK. But we do need to make sure that posts can't happen indefinitely and never get executed. If `AsyncCoroutineRunner` doesn't get auto-created, we should probably log a warning at a minimum each time `AsyncCoroutineRunner.Post` is called and there is no `AsyncCoroutineRunner.Instance`.

## Your setup (please complete the following information)

- Unity Version: 2019.4.17f1
- MRTK Version: v2.6.1

## Target platform (please complete the following information)

- HoloLens 2

### PR DESCRIPTION
**Pull request by MaxWang-MS**
## Overview
This PR ensures users receive warning if AsyncCoroutineRunner is not properly set up in the scene when it is required.

## Changes
- Fixes #9863

### CODE REVIEW

File: Assets/MRTK/Core/Utilities/Async/Internal/AsyncCoroutineRunner.cs [hunk 1]
```diff
@@ -56,30 +56,19 @@ internal static AsyncCoroutineRunner Instance
...
-                        }
+                        Debug.LogError($"GameObject {instance.gameObject.name} has an inactive AsyncCoroutineRunner attached and " +
+                        "there is no active AsyncCoroutineRunner in the scene. There must be an active AsyncCoroutineRunner attached to a GameObject at the root of the scene.");
+                        return instance;
                     }
                 }
 
                 if (instance == null)
                 {
+                    Debug.LogWarning("There is no AsyncCoroutineRunner in the scene. Adding a GameObject with AsyncCoroutineRunner attached at the root of the scene.");
```
Comment (davidkline-ms) [inline Assets/MRTK/Core/Utilities/Async/Internal/AsyncCoroutineRunner.cs:71]: Does this need to be a warning if the toolkit is adding it on the user's behalf?

Comment (jbienzms) [reply Assets/MRTK/Core/Utilities/Async/Internal/AsyncCoroutineRunner.cs:71]: @davidkline-ms the Instance creation in AwaiterExtensions.cs only causes AsyncCoroutineRunner to be created when you're using AwaiterExtensions. It is still possible to call AsyncCoroutineRunner.Post directly without using AwaiterExtensions.

**Review by jbienzms — COMMENTED** [review]
My biggest question is: 

Can we come up with any time where we want to be able to call `AsyncCoroutineRunner.Post` _without_ that creating the instance?

If we can come up with a good reason why this should happen, then I'm OK with the warning. If we can't come up with a good reason for that to happen, then I think we should just make `Post` create the instance if it wasn't already created.

File: Assets/MRTK/Core/Utilities/Async/Internal/AsyncCoroutineRunner.cs (hunk 1 above)
Comment (keveleigh) [reply Assets/MRTK/Core/Utilities/Async/Internal/AsyncCoroutineRunner.cs:71]: > It is still possible to call AsyncCoroutineRunner.Post directly without using AwaiterExtensions.

@jbienzms Can you expand on this? I guess we could write additional MRTK code, but `Post` itself is `internal`. I'm fine leaving `internal` implementations in a specific known state.

Comment (jbienzms) [reply Assets/MRTK/Core/Utilities/Async/Internal/AsyncCoroutineRunner.cs:71]: Well, I may be wrong about this. But the way I found this bug was that [WindowsSceneUnderstandingObserver](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/main/Assets/MRTK/Providers/Experimental/WindowsSceneUnderstanding/WindowsSceneUnderstandingObserver.cs) calls `RunObserverAsync` on line 157. This in turn calls `WaitForUpdate` on line 663. This eventually ends up in `AsyncCoroutineRunner.Post`. What I don't know is what happens between `CustomYieldInstruction.WaitForUpdate` and `AsyncCoroutineRunner.Post`, because I can't seem to find the code for `CustomYieldInstruction` using Github search in the MRTK repo. This may mean that `CustomYieldInstruction` is in a binary library. 

Please verify that the path between `CustomYieldInstruction.WaitForUpdate` and `AsyncCoroutineRunner.Post` will guarantee that the `AsyncCoroutineRunner` instance gets created.

Comment (MaxWang-MS) [reply Assets/MRTK/Core/Utilities/Async/Internal/AsyncCoroutineRunner.cs:71]: Under this PR `WaitForUpdate` will properly trigger a call to get the instance (and warn user if it fails) as `WaitForUpdate` eventually calls `RunOnUnityScheduler` where the new call to get the instance is added. You can perform a find all references in VS on `WaitForUpdate` and trace the result in `AwaiterExtensions` if you want to see the call hierarchy. So `AsyncCoroutineRunner.Post` does not guarantee the existence of the instance but the only caller to `AsyncCoroutineRunner.Post`, namely `RunOnUnityScheduler`, does.

Comment (keveleigh) [reply Assets/MRTK/Core/Utilities/Async/Internal/AsyncCoroutineRunner.cs:71]: Yep! From `await new WaitForUpdate()`, we get into AwaiterExtensions at

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/ae93bae2bf9ac6cbb0cc70678e41a37e4dc05b92/Assets/MRTK/Core/Utilities/Async/AwaiterExtensions.cs#L49-L52

then https://github.com/microsoft/MixedRealityToolkit-Unity/blob/ae93bae2bf9ac6cbb0cc70678e41a37e4dc05b92/Assets/MRTK/Core/Utilities/Async/AwaiterExtensions.cs#L124-L130

which calls RunOnUnityScheduler, which is the method being updated in this PR

**Review by davidkline-ms — DISMISSED** [review]
Thanks for adding the comment. Looks good pending validation :)

**Comment by davidkline-ms** [comment]
This is currently blocked by test failures.

**Comment by davidkline-ms** [comment]
Here is an example failure, from TestGltfLoads

Error message
```
System.AggregateException : One or more errors occurred.
----> UnityEngine.UnityException : get_gameObject can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
```

Stack trace
```
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) [0x0002b] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at System.Threading.Tasks.Task`1[TResult].get_Result () [0x0000f] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at Microsoft.MixedReality.Toolkit.Tests.GltfTests+<TestGltfLoads>d__6.MoveNext () [0x00073] in F:\AIPMRHosted\_work\7\s\Assets\MRTK\Tests\PlayModeTests\GltfTests.cs:65 
  at UnityEngine.TestTools.TestEnumerator+<Execute>c__Iterator0.MoveNext () [0x0004b] in C:\buildslave\unity\build\Extensions\TestRunner\UnityEngine.TestRunner\NUnitExtensions\Attributes\TestEnumerator.cs:31 
--UnityException
  at (wrapper managed-to-native) UnityEngine.Component.get_gameObject(UnityEngine.Component)
  at Microsoft.MixedReality.Toolkit.Utilities.AsyncCoroutineRunner.get_Instance () [0x00105] in F:\AIPMRHosted\_work\7\s\Assets\MRTK\Core\Utilities\Async\Internal\AsyncCoroutineRunner.cs:94 
  at Microsoft.MixedReality.Toolkit.Utilities.AwaiterExtensions.RunOnUnityScheduler (System.Action action) [0x0001d] in F:\AIPMRHosted\_work\7\s\Assets\MRTK\Core\Utilities\Async\AwaiterExtensions.cs:149 
  at Microsoft.MixedReality.Toolkit.Utilities.AwaiterExtensions.GetAwaiterReturnVoid (System.Object instruction) [0x00019] in F:\AIPMRHosted\_work\7\s\Assets\MRTK\Core\Utilities\Async\AwaiterExtensions.cs:127 
  at Microsoft.MixedReality.Toolkit.Utilities.AwaiterExtensions.GetAwaiter (Microsoft.MixedReality.Toolkit.Utilities.WaitForUpdate instruction) [0x00001] in F:\AIPMRHosted\_work\7\s\Assets\MRTK\Core\Utilities\Async\AwaiterExtensions.cs:51 
  at Microsoft.MixedReality.Toolkit.Utilities.Gltf.Serialization.ConstructGltf+<ConstructAsync>d__19.MoveNext () [0x0009f] in F:\AIPMRHosted\_work\7\s\Assets\MRTK\Core\Utilities\Gltf\Serialization\ConstructGltf.cs:62 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at Microsoft.MixedReality.Toolkit.Utilities.Gltf.Serialization.GltfUtility+<ImportGltfObjectFromPathAsync>d__4.MoveNext () [0x0033d] in F:\AIPMRHosted\_work\7\s\Assets\MRTK\Core\Utilities\Gltf\Serialization\GltfUtility.cs:149 
```

**Comment by MaxWang-MS** [comment]
Turns out due to Unity does not like its functions to be called on the non-Unity thread we cannot easily guarantee that an active `AsyncCoroutineRunner` exists. I added some mechanism to allow for checking whether there is an active runner when on a non-Unity thread and warn the user if there isn't. Unless we want to come up with a utility that enables calling function on Unity thread when on another thread I do not see a way for fully automating the creation of the runner. @keveleigh @davidkline-ms @jbienzms

**Comment by jbienzms** [comment]
> Turns out due to Unity does not like its functions to be called on the non-Unity thread we cannot easily guarantee that an active `AsyncCoroutineRunner` exists. I added some mechanism to allow for checking whether there is an active runner when on a non-Unity thread and warn the user if there isn't. Unless we want to come up with a utility that enables calling function on Unity thread when on another thread I do not see a way for fully automating the creation of the runner. @keveleigh @davidkline-ms @jbienzms

This is why I recommended considering the use of [RuntimeInitializeOnLoadMethod](https://docs.unity3d.com/ScriptReference/RuntimeInitializeOnLoadMethodAttribute.html). This is how I worked around this limitation in my own [CoroutineRunner](https://github.com/jbienzms/ThreadUtils/blob/main/CoroutineRunner.cs) class. The main downside is that it will get created even if not used. It does seem this gets used quite a lot. And I think the balance we have to decide between is whether this should already be in the scene, or if we should provide warnings when someone uses something that requires it but hasn't added it to the scene.

The code @keveleigh updated may greatly reduce the chances of it being called without getting added to the scene. If you're now able to start using `WindowsSceneUnderstandingObserver` without manually adding `AsyncCoroutineRunner` to the scene, I'm happy.

File: Assets/MRTK/Core/Utilities/Async/AwaiterExtensions.cs [hunk 2]
```diff
@@ -141,12 +141,23 @@ private static void RunOnUnityScheduler(Action action)
         {
             if (SynchronizationContext.Current == SyncContextUtility.UnitySynchronizationContext)
             {
+                // Take the opportunity to ensure AsyncCoroutineRunner is running when we are on the Unity thread
+                if (!AsyncCoroutineRunner.IsInstanceRunning)
+                {
+                    var _ = AsyncCoroutineRunner.Instance;
+                }
```
Comment (keveleigh) [inline Assets/MRTK/Core/Utilities/Async/AwaiterExtensions.cs:148]: Do you think we need this? As far as I see, all the `action`s contain `AsyncCoroutineRunner.Instance`, which should ensure an instance in the scene, which will happen on line 149 when `action()` is called.

File: Assets/MRTK/Core/Utilities/Async/Internal/AsyncCoroutineRunner.cs [hunk 3]
```diff
@@ -140,5 +152,19 @@ private void Update()
...
+
+        private void OnDisable()
+        {
+            if (instance == this)
+            {
+                isInstanceRunning = false;
+            }
+        }
+
+        private void Awake()
```
Comment (keveleigh) [inline Assets/MRTK/Core/Utilities/Async/Internal/AsyncCoroutineRunner.cs:164]: Should this be `OnEnable` to match `OnDisable`?

File: Assets/MRTK/Core/Utilities/Async/Internal/AsyncCoroutineRunner.cs [hunk 4]
```diff
@@ -133,5 +152,19 @@ private void Update()
                 next();
             }
         }
+
+        private void OnDisable()
+        {
+            if (instance == this)
+            {
+                isInstanceRunning = false;
+            }
```
Comment (RogPodge) [inline Assets/MRTK/Core/Utilities/Async/Internal/AsyncCoroutineRunner.cs:161]: We should log a a message if the OnDisabled is called on a AsyncRunner that is not the default instance. Currently, OnDisable will just run silently and not raise any indicators that no action was taken

**Review by RogPodge — APPROVED** [review]

File: Assets/MRTK/Core/Utilities/Async/Internal/AsyncCoroutineRunner.cs (hunk 4 above)
Comment (MaxWang-MS) [reply Assets/MRTK/Core/Utilities/Async/Internal/AsyncCoroutineRunner.cs:161]: Could you explain why would that be necessary? Disabling an "extra" instance of the runner seems the right thing to me and thus I don't think we should warn user about that. Also we do not disable runner in our code so that is very likely to be the user's action.

Comment (RogPodge) [reply Assets/MRTK/Core/Utilities/Async/Internal/AsyncCoroutineRunner.cs:161]: Didn't realize that this was on top of the existing Monobehavior behavior. Looks good to me

**Review by keveleigh — APPROVED** [review]

**Comment by MaxWang-MS** [comment]
@jbienzms Due to the time constraint we are facing for the 2.7 release we decided to merge this PR (warns user when the runner should be active when not) and plan to make a larger-impact change (e.g. take the route you mentioned) that aims to automate the process of creating/activating the runner. We are keeping the issue open and hope to address it in the next release. Thanks for bringing this up and contributing your ideas!

**Comment by jbienzms** [comment]
Thanks @MaxWang-MS. Totally understand about the deadline and appreciate the efforts so far. Thank you for keeping this one open for future improvement, and best of luck with 2.7!
