### PR TITLE
Async Building and Windows Device Portal Commands

### LINKED ISSUE #2119: Dev branch Compile Issues
## Overview
When targeting IL2CPP and .NET Standard 2.0 the editor fails to build a solution.
```
Assets\MixedRealityToolkit-Examples\SharingWithUNET\Scripts\GenericNetworkTransmitter.cs(129,33): error CS1545: Property, indexer, or event 'StreamSocketListener.ConnectionReceived' is not supported by the language; try directly calling accessor methods 'StreamSocketListener.add_ConnectionReceived(TypedEventHandler<StreamSocketListener, StreamSocketListenerConnectionReceivedEventArgs>)' or 'StreamSocketListener.remove_ConnectionReceived(EventRegistrationToken)'
Assets\MixedRealityToolkit\Sharing\Scripts\SDK\SharingClientPINVOKE.cs(87,51): warning CS0436: The type 'SystemException' in 'Assets\MixedRealityToolkit\Common\Scripts\CrossPlatform\SystemException.cs' conflicts with the imported type 'SystemException' in 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Using the type defined in 'Assets\MixedRealityToolkit\Common\Scripts\CrossPlatform\SystemException.cs'.
Assets\MixedRealityToolkit\Utilities\Scripts\ApplicationViewManager.cs(98,36): error CS1545: Property, indexer, or event 'CoreWindow.VisibilityChanged' is not supported by the language; try directly calling accessor methods 'CoreWindow.add_VisibilityChanged(TypedEventHandler<CoreWindow, VisibilityChangedEventArgs>)' or 'CoreWindow.remove_VisibilityChanged(EventRegistrationToken)'
Error building Player because scripts had compiler errors
Exception: Build Result: Failed
```

## Steps to reproduce
https://github.com/StephenHodgson/MixedRealityToolkit-Unity/tree/MRTK-BuildPortalUpdate

UWP SDK: 10.0.17134.0
Scripting Runtime Verison: 4.x Equivalent
Scripting Backend: IL2CPP
API Compatibility: .NET Standard 2.0
Build Config: Debug
Build Platform: x86

## Unity Editor Version
2018.1.0f2

## Mixed Reality Toolkit Release Version
Dev_Working Branch

### LINKED ISSUE #2124: Master Build warnings with IL2CPP in 2017+
## Overview
The `MetroHandleRef.cs` class conflicts with the imported type 'HandleRef" in mscorlib when using the IL2CPP scripting backend.

## Unity Editor Versions
- 2017.4.3f1
- 2018.1.0f2

## Mixed Reality Toolkit Release Version
84493c975fbf0fe0f3541303ce1758ca11dfe44a

### PR DESCRIPTION
**Pull request by StephenHodgson**
Overview
---
- Added a heavily edited version of the [Unity Async/Await Utilities](https://github.com/svermeulen/Unity3dAsyncAwaitUtil) by @svermeulen.  It has the same license type as the project (MIT)
- Fixed an issue where users were unable to build without either specifying a wsa certificate, or building through the normal Unity Editor Build window because the certificate had not been generated yet.  (Unity Build will generate one for you if one doesn't exist.)
- Adds async building of appx project. Typical Unity Player Building still blocks the editor, but APPX building and installing happens asynchronously.
- Did a bit of cleanup for coding guidelines and renamed a few classes for clarity.
- Added ability to build appx from command line argument.
- Added `EditorAssemblyReloadManager` to control reloading assemblies in the editor so running async tasks don't get cancelled prematurely.
- Added StartAsyncProcess extension methods.
- Added Rest Utililities.
- Updated data structures for Windows Device Portal.
- Fixes #1904 
- Moved the windows device portal classes out of the editor so any application can use it at runtime.
- Fixes #2124 and other conflicts with IL2CPP builds where the toolkit has implemented some apis from mscorlib.

TODO
---
- [x] Update Device Portal with new async Rest calls.
- [x] A bit of cleanup and renaming a few async methods with Async suffix.
- [x] Fix a issue with device connections when prev paired device is unreachable the string name is lost and it's impossible to select it again in the drop down.
- [x] Add all the documentation to the public PME's in the PR.
- [x] Fix an issue with CSRF Token refreshing.
- [x] Fix an issue with incrementing versions.
- [x] Compatibility with 2018.1
- [x] Make quick options HoloLens target make sure to target HoloLens only. #1959
- [x] Fixes #2119 

Breaking Changes
---
- Removed backwards compatibility to Visual Studio 2015.
- Changed command line tool hook for VSO build task.
- Removed unused `XDEGuestLocator.cs`

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@jwittner just wanted to bring this to your attention that I updated the Command Line build method name. Not sure if that impacts the NuGet Package generation.

**Comment by jwittner** [comment]
Hey @StephenHodgson, thanks for bringing this up. Right now the build script doesn't build an application from the project, just the packages for distributing the library. I do think it's a reasonable next step to hook up builds for supported platforms to better verify the functionality.

**Comment by davidkline-ms** [comment]
Is removing VS 2015 support going to break anyone? 5.6.x users?

File: Assets/MixedRealityToolkit/BuildAndDeploy/Editor/BuildDeployPreferences.cs [hunk 1]
```diff
@@ -0,0 +1,100 @@
+﻿// Copyright (c) Microsoft Corporation. All rights reserved.
+// Licensed under the MIT License. See LICENSE in the project root for license information.
+
+using MixedRealityToolkit.Build.WindowsDevicePortal.DataStructures;
```
Comment (davidkline-ms) [inline Assets/MixedRealityToolkit/BuildAndDeploy/Editor/BuildDeployPreferences.cs]: Does us moving to requiring .net 4.6 allow us to use the existing Windows Device Portal Wrapper instead of having to clone the functionality?

https://github.com/Microsoft/windowsdeviceportalwrapper

File: Assets/MixedRealityToolkit/Common/Scripts/AsyncUtility/AwaitYeildInstructions/WaitForBackgroundThread.cs [hunk 2]
```diff
@@ -0,0 +1,35 @@
+// MIT License
```
Comment (davidkline-ms) [inline Assets/MixedRealityToolkit/Common/Scripts/AsyncUtility/AwaitYeildInstructions/WaitForBackgroundThread.cs]: Blocking this unitl I hear back from my PM regarding whether or not we are allowed to include this.

Comment (riverar) [reply Assets/MixedRealityToolkit/Common/Scripts/AsyncUtility/AwaitYeildInstructions/WaitForBackgroundThread.cs]: And its subfolder is spelled incorrectly ("AwaitYeildInstructions")

File: Assets/MixedRealityToolkit/BuildAndDeploy/Editor/BuildDeployPreferences.cs (hunk 1 above)
Comment (riverar) [reply Assets/MixedRealityToolkit/BuildAndDeploy/Editor/BuildDeployPreferences.cs]: Might not be worth it, seems that project is full of problems (https://github.com/Microsoft/WindowsDevicePortalWrapper/issues?utf8=✓&q=is%3Aissue+is%3Aopen+hololens)

File: Assets/MixedRealityToolkit/Common/Scripts/Rest/Rest.cs [hunk 3]
```diff
@@ -0,0 +1,232 @@
...
+
+        /// <summary>
+        /// Gets the Basic auth header.
+        /// </summary>
+        /// <param name="username"></param>
+        /// <param name="password"></param>
+        /// <returns></returns>
+        public static string GetBasicAuthentication(string username, string password)
+        {
+            return $"Basic {Convert.ToBase64String(Encoding.GetEncoding("ISO-8859-1").GetBytes(string.Format("{0}:{1}", username, password)))}";
```
Comment (riverar) [inline Assets/MixedRealityToolkit/Common/Scripts/Rest/Rest.cs]: Be aware of non UTF-8 support here; see rfc2617. Impact: Users typing 儿童游戏 as a password will fail here.

File: Assets/MixedRealityToolkit/BuildAndDeploy/Editor/BuildDeployPreferences.cs (hunk 1 above)
Comment (StephenHodgson) [reply Assets/MixedRealityToolkit/BuildAndDeploy/Editor/BuildDeployPreferences.cs]: I thought about using it, but didn't want to put another external dependency on this repository.

File: Assets/MixedRealityToolkit/Common/Scripts/Rest/Rest.cs (hunk 3 above)
Comment (StephenHodgson) [reply Assets/MixedRealityToolkit/Common/Scripts/Rest/Rest.cs]: @riverar what would be a valid fix?

File: Assets/MixedRealityToolkit/Common/Scripts/AsyncUtility/AwaitYeildInstructions/WaitForBackgroundThread.cs (hunk 2 above)
Comment (StephenHodgson) [reply Assets/MixedRealityToolkit/Common/Scripts/AsyncUtility/AwaitYeildInstructions/WaitForBackgroundThread.cs]: Of course, I also want clarification on including it, but it was heavily modified and includes support for editor async/await that wasn't part of the original.

File: Assets/MixedRealityToolkit/Common/Scripts/Rest/Rest.cs (hunk 3 above)
Comment (riverar) [reply Assets/MixedRealityToolkit/Common/Scripts/Rest/Rest.cs]: Unsure if WDP supports UTF-8 basic auth, maybe we need to try that first. If that fails, well, this problem goes away 😄

File: Assets/MixedRealityToolkit/BuildAndDeploy/Editor/BuildDeployPreferences.cs (hunk 1 above)
Comment (StephenHodgson) [reply Assets/MixedRealityToolkit/BuildAndDeploy/Editor/BuildDeployPreferences.cs]: I'd rather see a Unity specific solution to the Windows Device Portal.

**Comment by StephenHodgson** [comment]
> Is removing VS 2015 support going to break anyone? 5.6.x users?

Doesn't matter the dev branch is supposed to be staging for vNEXT, correct?

**Comment by davidkline-ms** [comment]
Right.... just noticed that :)

File: Assets/MixedRealityToolkit/BuildAndDeploy/Editor/BuildDeployPreferences.cs (hunk 1 above)
Comment (riverar) [reply Assets/MixedRealityToolkit/BuildAndDeploy/Editor/BuildDeployPreferences.cs]: @davidkline-ms These issues date almost 2 years back, with no resolution, and afflict fundamentals such as deployment and app launching. That's a giant red flag, in my opinion. Just my observation, you guys are the experts and know better.

File: Assets/MixedRealityToolkit/BuildAndDeploy/Editor/BuildDeployWindow.cs [hunk 4]
```diff
@@ -1,19 +1,22 @@
-﻿// Copyright (c) Microsoft Corporation.
-// Copyright (c) Rafael Rivera.
```
Comment (StephenHodgson) [inline Assets/MixedRealityToolkit/BuildAndDeploy/Editor/BuildDeployWindow.cs]: Here's the original file headers for this file: https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/98daf02edf891291adbe33746900513df7ee5c6a#diff-82bf36d076c9b3905af808f0405ca9fdR1

Here's the changes that @riverar made when he added his header https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/e4dcc9b7cb36b5d18a344bda5547b2fb7748bdee.

I can say definitively that those contributions are no longer being used. The XDAGuestLocator was not being used  and it has been removed.

Just for clarification about the rest of the commits to this file made by Rafael, just in case there's any issue:
- https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/271b5bda8af6ebcc40b2be00a67cdd5e13fef662
- https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/e4dcc9b7cb36b5d18a344bda5547b2fb7748bdee
- https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/21ea193afef910920e32d1dc7e762280dc8b787a

I can say definitively that none of the changes are in this file today.  The BuildDeployWindow has made may changes to both it's GUI and underlying logic.

That being said, Rafael if you'd like to re-implement the XDAGuestLocator please feel free to do so and attribute yourself according to any licensing rules set forth my Microsoft.

CC: @davidkline-ms, @keveleigh

Comment (StephenHodgson) [reply Assets/MixedRealityToolkit/BuildAndDeploy/Editor/BuildDeployWindow.cs]: It wasn't working last time I checked. If you'd like to do a quick test on the master branch, it'll give a definitive answer.

Comment (riverar) [reply Assets/MixedRealityToolkit/BuildAndDeploy/Editor/BuildDeployWindow.cs]: OK, will reimplement after BUILD week. Thanks for the heads up!

Comment (StephenHodgson) [reply Assets/MixedRealityToolkit/BuildAndDeploy/Editor/BuildDeployWindow.cs]: Awesome, I'm looking forward to seeing it, and you at build. 😊

**Comment by StephenHodgson** [comment]
Accidentally deleted branch.

**Comment by StephenHodgson** [comment]
@davidkline-ms can we please merge this into dev it we're locking it?

**Comment by StephenHodgson** [comment]
Most of these changes already made it into vNEXT anyway
