### PR TITLE
Fixed GLTF build errors

### LINKED ISSUE #1139: Build error: namespace GLTF could not be found (MotionControllerVisualizer.cs)
Referenced here: #1129 , but it affects the master branch.

I'm using the most recent version of the master branch, I'm using Unity 2017.1.1f1, and Visual studio 15.3.3.

Build window:

image

I've tried with 10.0.14393 SDK and the 10.0.10563 SDK as well, although with 10.0.14393 I get an error about Haptics not existing in the windows.devices namespace.

I've tried all this with Unity 5.6.3f1 as well, which produces even more errors.

I'm able to build after going back to this commit: https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/49b9bf3dff230b19c2fd2d2c06fb31386d13613d

### PR DESCRIPTION
**Pull request by StephenHodgson**
Fixes #1139

### CODE REVIEW

**Comment by StephenHodgson** [comment]
@HattMarris1 can you test and approve this for me please. Thanks.

**Comment by HattMarris1** [comment]
Will do

**Comment by StephenHodgson** [comment]
@HattMarris1 do you approve?

File: Assets/HoloToolkit/Input/Scripts/Utilities/MotionControllerVisualizer.cs [hunk 1]
```diff
@@ -38,18 +38,16 @@ public class MotionControllerVisualizer : MonoBehaviour
 
         [Tooltip("This material will be used on the loaded glTF controller model. This does not affect the above overrides.")]
         [SerializeField]
-        protected UnityEngine.Material GLTFMaterial;
+        protected Material GLTFMaterial;
```
Comment (keveleigh) [inline Assets/HoloToolkit/Input/Scripts/Utilities/MotionControllerVisualizer.cs]: This will break 2017.2 building when this change is merged back into the dev branch (or when master i updated to work with 2017.2) because there's a Material in the GLTF namespace as well. Likely, renaming it to GLTFMaterial is the best fix.

Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/MotionControllerVisualizer.cs]: I'll look into it and double check. Thanks for the heads up!
