### PR TITLE
App Bar highlighted state bug fix #1877

### LINKED ISSUE #1877: AppBar button stays focused
## Overview
Leftmost button in the AppBar for BoundingBoxRig never becomes unfocused after adjustment.

## Expected Behavior
oelizc7

## Actual Behavior
https://i.imgur.com/LY2RCdu.gifv

## Steps to reproduce
* Create scene with "defaults" (project settings, scene settings, etc.)
* Create cube in scene
* Attach `TwoHandManipulatable` and `BoundingBoxRig` to the cube
* Add a `BoundingBoxBasic` to the `BoundingBoxPrefab` field
* Play

Or simply play the BoundingBoxGizmoExample scene.

## Unity Editor Version
2017.3.1f1

## Mixed Reality Toolkit Release Version
Dev_Working_Branch

### PR DESCRIPTION
**Pull request by cre8ivepark**
Overview
---
App Bar's Done/Hide menu button stays highlighted once you enter/exit the adjust mode.
In Show() and Hide(), added code for disabling/enabling the render of the highlighting mesh.

Changes
---
- Fixes: #1877 

2018-03-29 16_37_36-unity 2017 2 1p2 64bit - boundingboxgizmoexample unity - mrtk-original - unive

2018-03-29 16_37_53-unity 2017 2 1p2 64bit - boundingboxgizmoexample unity - mrtk-original - unive

### CODE REVIEW

File: Assets/MixedRealityToolkit/UX/Scripts/AppBar/AppBarButton.cs [hunk 1]
```diff
@@ -137,6 +137,7 @@ private void Hide()
             icon.Alpha = 0f;
             text.DisableText = true;
             cButton.enabled = false;
+            cButton.transform.Find("FrontPlate").GetComponent<MeshRenderer>().enabled = false;
```
Comment (StephenHodgson) [inline Assets/MixedRealityToolkit/UX/Scripts/AppBar/AppBarButton.cs]: Let's cache this `FrontPlate`'s mesh renderer so we don't have to get the mesh renderer each time we Show/Hide

**Comment by cre8ivepark** [comment]
@StephenHodgson Added private MeshRenderer highlightMesh

File: Assets/MixedRealityToolkit/UX/Scripts/AppBar/AppBarButton.cs [hunk 2]
```diff
@@ -39,6 +40,8 @@ public void Initialize(AppBar newParentToolBar, AppBar.ButtonTemplate newTemplat
             text = GetComponent<CompoundButtonText>();
             text.Text = template.Text;
             icon = GetComponent<CompoundButtonIcon>();
+            highlightMesh = cButton.transform.Find("FrontPlate").GetComponent<MeshRenderer>();
```
Comment (StephenHodgson) [inline Assets/MixedRealityToolkit/UX/Scripts/AppBar/AppBarButton.cs]: Where in the hierarchy is the `FrontPlate` in relation to the GameObject this `AppBarButton` is attached to?

Comment (cre8ivepark) [reply Assets/MixedRealityToolkit/UX/Scripts/AppBar/AppBarButton.cs]: AppBarButton uses HolographicButton prefab as a template, and it looks like this:
2018-04-02 09_29_35-unity 2017 2 1p2 64bit - boundingboxgizmoexample unity - mrtk-original - unive

Comment (StephenHodgson) [reply Assets/MixedRealityToolkit/UX/Scripts/AppBar/AppBarButton.cs]: So it's dynamicly generated?

Or do we have a game object in the scene to reference?

Comment (cre8ivepark) [reply Assets/MixedRealityToolkit/UX/Scripts/AppBar/AppBarButton.cs]: Yes, it is dynamically generated.

Comment (StephenHodgson) [reply Assets/MixedRealityToolkit/UX/Scripts/AppBar/AppBarButton.cs]: I don't like that we're using `cButton.transform.Find("FrontPlate")`.  Is there a way we can do this using a `GameObject` reference instead of a string lookup?

Comment (Jarodshow) [reply Assets/MixedRealityToolkit/UX/Scripts/AppBar/AppBarButton.cs]: Wouldn't `GetComponent<CompoundButtonMesh>().Renderer` work?

**Comment by cre8ivepark** [comment]
@StephenHodgson Updated to access FrontPlate mesh renderer through CompoundButtonMesh component. Thanks!

**Comment by davidkline-ms** [comment]
Does this need to go into Patch/Master as well?

**Comment by StephenHodgson** [comment]
There's already a PR for that. #1914
