### PR TITLE
Fixing BC Scale Handles

### LINKED ISSUE #9946: BoundsControl Translation Handles have wrong colliders for some HandlePrefabs
## Describe the bug

The grabbable colliders for the Translation Handles of the BoundsControl component are positioned wrong with some handle Prefabs.  As a result the handles cannot be grabbed as expected. 

As seen in the following Image the generated colliders are offcenter or even fully inside the object.

BoundsControle

## To reproduce

1. Create new Cube  and ad  the BoundsControl component 
2. Configure as seen in Image ( show Translation Handles for all axes; increase Handle size for better visibility) 
3. Set a Handle Prefab:   it only occurs for some prefabs. The simples one i found is the default cone create with the unity ProBuilder.

## Expected behavior
The translation handle colliders are center over the handles and can be adjusted with the Collider padding to fully contain them.
Alternatively colliders that are already attached to the handle Prefabs could be used for the translation. 

## Your setup (please complete the following information)

- Unity Version [2020.3Lts]
- MRTK Version [2.7]

## Target platform (please complete the following information)
- WMR immersive

### PR DESCRIPTION
**Pull request by Zee2**
## Overview

This is a _non-breaking_ fix for the collider alignment behavior of the scale handles on BoundsControl-equipped objects. This change brings many of the calculations and behaviors of the scale handles inline with what the newer rotation and translation handles are already doing; i.e., instead of using a two-stage container-scale-visual hierarchy, it uses a single container-visual structure, exactly the same as the rotation and translation handles. This also moves the job of realigning the collider to the container, instead of the visual. Part of this is reworking the scale handles to use _rotation_ realignment, instead of _scaling_ realignment. Previously, the scale handles realigned the colliders by simply flipping the scale of an intermediary object ("visualsScale"), but this causes issues with oblong handles, collider alignment, etc. Now, "visualsScale" is completely removed, and all of the handle alignment behavior is implemented with rotations, exactly like the other handles. Now, all of the handle colliders (translate, rotate, scale) are perfectly aligned and coherent with any collider mesh/shape/rotation/etc.

### Old

In this diagram, you can see how the scale colliders were not correctly aligned to the handles. The collider padding was applied inconsistently across the different handles, as the collider was not able to be rotated/realigned properly to the underlying handle visual. 

### New

Now that the scale handles have been refactored to use proper rotation-based realignment, all the collider padding and spacing is applied coherently across all handles, with the proper spacing/padding/alignment applied regardless of the rotation of the underlying visual.

Several of the functions and mechanisms for scale handles have been reworked to function identically to the rotation/translation handles, i.e. the `GetRotationRealignment` function that returns a quaternion to align the handle, and moving from the `UpdateHandles(ref boundsCorners)` pattern to the `CalculateHandlePositions(ref boundscorners)` pattern. Scale handles now also use an internal cache of the bounds corners, to bring the calculation of handle positions inline with how all other handles perform the same task.

`CreateVisual` is slightly reworked to be functionally identical in calling pattern/behavior to the other handles' `CreateVisual`. 

Very important: the handle collider alignment test that was introduced in a previous PR for rigorously checking the exact collider dimensions and alignments of the handles has been expanded/generalized to cover all three handle types.

**This is a intermediate PR to fix handle alignment in a non-breaking way.  This _does not fix the code copypasta issue,_ the scale handles still reuse a lot of code without proper DRY techniques. ** A future PR will refactor scale handles and the entire handle class hierarchy to properly DRY-ly reuse code and be far more generalized. This is a much larger refactor and may introduce a couple of breaking changes. _This_ PR is safe to merge for 2.x. The future PR may need to be merged in 3.x due to breaking changes.

## Changes
- `visualsScale` intermediary hierarchy transform is removed. Scale handles now use a single container transform and single visuals transform.
- Scale handle alignment is now achieved through rotations/quats, same as all other handles, instead of wonky scaling
- Scale handle alignment is now performed at the container transform level, instead of the visual level, same as the other handles
- Scale handle code has been slightly refactored to more closely match the behavior/structure/mechanisms of other handles
- Tests for exact/precise collider alignment have been generalized to include scale handles, utilizing the `HandleTestData` data provider pattern
- Tests have been updated to match the new hierarchy pattern (aka, don't look for `visualsScale`)
- Should finally completely fix #9946 ! Woohoo.

## Verification
Test for exact collider alignment has been expanded to include scale handles. Full and precise test coverage of this issue.

### CODE REVIEW

File: Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ScaleHandles.cs [hunk 1]
```diff
@@ -16,8 +16,17 @@ public class ScaleHandles : HandlesBase
         protected override HandlesBaseConfiguration BaseConfig => config;
         private ScaleHandlesConfiguration config;
         private bool areHandlesFlattened = false;
+
+        /// <summary>
+        /// Cached handle positions - we keep track of handle positions in this array
+        /// in case we have to reload the handles due to configuration changes.
+        /// </summary>
+        protected Vector3[] HandlePositions { get; private set; }
+        private int NumHandles => 8;
```
Comment (keveleigh) [inline Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ScaleHandles.cs:25]: does this need to be a property? or could it be a const field?

```suggestion
        private const int NumHandles = 8;
```

File: Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ScaleHandles.cs [hunk 2]
```diff
@@ -85,93 +97,115 @@ protected override void RecreateVisuals()
...
-                    Bounds cornerBounds = CreateVisual(visualsScaleParent.gameObject, areHandlesFlattened);
-
-                    // update handle collider bounds
-                    UpdateColliderBounds(handles[i], cornerBounds.size);
+                    obsoleteChild.parent = null;
+                    Object.Destroy(obsoleteChild.gameObject);
                 }
+                else
+                {
+                    Debug.LogError("couldn't find corner visual on recreating visuals");
```
Comment (keveleigh) [inline Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ScaleHandles.cs:109]:
```suggestion
                    Debug.LogError("Couldn't find corner visual on recreating visuals");
```

File: Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ScaleHandles.cs [hunk 3]
```diff
@@ -85,93 +97,115 @@ protected override void RecreateVisuals()
...
 
             if (isFlattened)
             {
                 // Rotate 2D slate handle asset for proper orientation
-                cornerVisual.transform.Rotate(0, 0, -90);
+                parent.transform.Rotate(0, 0, -90);
+            } else {
+                Quaternion realignment = GetRotationRealignment(handleIndex);
+                parent.transform.localRotation = realignment;
+            }
```
Comment (keveleigh) [inline Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ScaleHandles.cs:181]: nit on the formatting for consistency:

```suggestion
            }
            else
            {
                Quaternion realignment = GetRotationRealignment(handleIndex);
                parent.transform.localRotation = realignment;
            }
```

File: Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ScaleHandles.cs (hunk 1 above)
Comment (Zee2) [reply Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ScaleHandles.cs:25]: @keveleigh I did this, sort of cargo-culting the way that the per-axis handles do it. The reason the per-axis handles do this is because they define the `NumHandles` as the length of the axis array:

```
private int NumHandles => handleAxes.Length;
```

But I don't see much of a reason for this to be done the same way in ScaleHandles. I'll do this change, but I need to make sure that it won't cause any weird side effects.

File: Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ScaleHandles.cs (hunk 3 above)
Comment (Zee2) [reply Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ScaleHandles.cs:181]: Do we really not do same-line elses for readability? I'll accept this suggestion, but IMO same-line elses are a god-send for readability and compactness.

Comment (keveleigh) [reply Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ScaleHandles.cs]: Happy for this to be something we revisit with the coding guidelines! But yeah, so far, we've kept with the full multi-line brace syntax:

https://docs.microsoft.com/windows/mixed-reality/mrtk-unity/contributing/coding-guidelines?view=mrtkunity-2021-05#use-braces

Largely inspired by https://docs.microsoft.com/dotnet/csharp/fundamentals/coding-style/coding-conventions#layout-conventions and the samples formatting.

**Review by davidkline-ms — APPROVED** [review]
Looks good, pending resolution of https://github.com/microsoft/MixedRealityToolkit-Unity/pull/10007/files#r655695587

**Comment by Zee2** [comment]
Found a regression in flattening behavior that is not caught by tests. Marked Do Not Merge until I resolve this regression.

File: Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ScaleHandles.cs (hunk 1 above)
Comment (Zee2) [reply Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ScaleHandles.cs:25]: No ill effects from this change. Committing.

**Comment by Zee2** [comment]
The regression is actually a large bug in the mainline release, present in 2.6.x and 2.7.x releases. Separate PR will be issued to fix and test.
