### PR TITLE
Clipping primitive now removes OnPreRender event upon deletion

### LINKED ISSUE #9450: Clipping Primitive Raises MissingReferenceExceptions when removed during runtime
## Describe the bug

A MissingReferenceException is raised when the Clipping Primitive is removed from the scene during runtime. These exceptions persist throughout the lifetime of the application

## To reproduce

1. Go to the ScrollingObjectCollection Example scene.
2. Start the scene
3. Delete the ScrollingObjectCollection GameObject, including it's children.
4. See the MissingReferenceExceptions pile up in the Console

## Expected behavior

No exceptions are raised

## Your setup (please complete the following information)

- Unity Version 2019.4
- MRTK Version 2.5+

## Target platform (please complete the following information)
-All

### PR DESCRIPTION
**Pull request by RogPodge**
## Overview
Clipping primitive now unregisters its event upon deletion, which fixes a series of null reference exceptions that would get raised otherwise.

## Changes
Fixes #9450

### CODE REVIEW

File: Assets/MRTK/Core/Utilities/StandardShader/ClippingPrimitive.cs [hunk 1]
```diff
@@ -195,6 +195,8 @@ public void ClearRenderers()
                     RemoveRenderer(renderers.Count - 1);
                 }
             }
+
+            UseOnPreRender = false;
```
Comment (keveleigh) [inline Assets/MRTK/Core/Utilities/StandardShader/ClippingPrimitive.cs:199]: Interesting. Does this mean `OnDisable` isn't getting called when the monobehaviour is destroyed?

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/a69eceee3e248b41f48f2e036bdce92839c933b6/Assets/MRTK/Core/Utilities/StandardShader/ClippingPrimitive.cs#L234-L247

Comment (keveleigh) [reply Assets/MRTK/Core/Utilities/StandardShader/ClippingPrimitive.cs:199]: I also feel like this approach _could_ create a CameraEventRouter at shutdown just to remove a not-already-registered event. 

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/a69eceee3e248b41f48f2e036bdce92839c933b6/Assets/MRTK/Core/Utilities/StandardShader/ClippingPrimitive.cs#L77-L98

maybe we should also check that `useOnPreRender != value`? Or only set `UseOnPreRender` to false here if it's true?

Comment (RogPodge) [reply Assets/MRTK/Core/Utilities/StandardShader/ClippingPrimitive.cs:199]: Oh yeah I guess OnDisable != OnDestroy? Or maybe it's a specific scenario where when you delete it in editor rather than via the Destroy() call that things get weird.

Comment (RogPodge) [reply Assets/MRTK/Core/Utilities/StandardShader/ClippingPrimitive.cs:199]: I'll take another pass to ensure we aren't messing anything up here

Comment (RogPodge) [reply Assets/MRTK/Core/Utilities/StandardShader/ClippingPrimitive.cs]: Turns out the event was getting added to the handler multiple times. Doing a useOnPreRenderer != value check to the setter alleviated this issue.

File: Assets/MRTK/Core/Utilities/StandardShader/ClippingPrimitive.cs [hunk 2]
```diff
@@ -84,16 +84,19 @@ public bool UseOnPreRender
                     cameraMethods = CameraCache.Main.gameObject.EnsureComponent<CameraEventRouter>();
                 }
 
-                if (value)
+                if(useOnPreRender != value)
```
Comment (keveleigh) [inline Assets/MRTK/Core/Utilities/StandardShader/ClippingPrimitive.cs:87]:
```suggestion
                if (useOnPreRender != value)
```

**Review by keveleigh — APPROVED** [review]
