### PR TITLE
Fix for hidden members in AttachToController

### LINKED ISSUE #1661: Missing Script References in SolverExamples
## Overview
Missing Script references in the SolverExamples scene.

## Mixed Reality Toolkit Release Version
48a9ac506c430325340e248c8421604e54de1804

### PR DESCRIPTION
**Pull request by StephenHodgson**
Overview
---
Fix for hidden members in AttachToController.  Second attempt.

This time I simply made ControllerFinder Abstract so no one could use it directly on a GameObject.  I couldn't think of any reason to really have it unless you needed to inherit anyway. (Mostly a helper).

Added a industry standard editor for SolverHandler to make sure we don't show the fields we didn't need to change.

Also added editors for the Controller Finder and Attach To Controller classes for aesthetics.

image

Changes
---
Fixes #1661

### CODE REVIEW

**Comment by StephenHodgson** [comment]
>any classes inheriting from ControllerFinder will need a new custom inspector or else the most important fields will be hidden by default.

Yeah, I thought about that for a bit, and figured the same would have also been true if I went and made a custom inspector for the solver handlers instead. That was a lose, lose situation.  I decided to go with controller finder because these fields seem to be optional.

>the logic exposing them will be hidden from developers in an editor class which many will not even realize exists

I disagree. Developers who are familiar with unity will be able to tell right away that it's a custom inspector because there's no script object field at the top of the inspector.

I've also been thinking about how to make the editor scripts more accessible be mirroring the editor folder to match the scripts folder.  @DDReaper, could we address that change in your refactoring? (I think you did, but just wanted to check)

>If MRTKEditors were used that logic would be visible within the class as attributes on the fields.

I don't really see the advantage here because we're also using attributes to control the visibility if the fields in the inspector no matter which editor class we inherited from.

One thing to note, is any class that inherited from controller finder, could have an abstract base editor it needs to inherit from as well.

File: Assets/HoloToolkit/Input/Scripts/Utilities/AttachToController.cs [hunk 1]
```diff
@@ -13,27 +13,19 @@ namespace HoloToolkit.Unity.InputModule
...
-        protected new InteractionSourceHandedness handedness = InteractionSourceHandedness.Left;
-#endif
-        [SerializeField]
-        protected new MotionControllerInfo.ControllerElementEnum element = MotionControllerInfo.ControllerElementEnum.PointingPose;
-
         public bool SetChildrenInactiveWhenDetached = true;
 
         [SerializeField]
-        protected Vector3 positionOffset = Vector3.zero;
+        protected Vector3 PositionOffset = Vector3.zero;
```
Comment (keveleigh) [inline Assets/HoloToolkit/Input/Scripts/Utilities/AttachToController.cs]: From what I can tell, we've mostly been using lower camel case for protected names in the Toolkit.

File: Assets/HoloToolkit/Input/Scripts/Utilities/ControllerFinder.cs [hunk 2]
```diff
@@ -16,33 +16,42 @@ namespace HoloToolkit.Unity.InputModule
...
+    public abstract class ControllerFinder : MonoBehaviour
     {
-        #region public members
-        public MotionControllerInfo.ControllerElementEnum Element { get { return element; } }
-        public Transform ElementTransform { get { return elementTransform; } private set { elementTransform = value; } }
-        #endregion
+        public MotionControllerInfo.ControllerElementEnum Element
+        {
+            get { return element; }
+            set { element = value; }
```
Comment (keveleigh) [inline Assets/HoloToolkit/Input/Scripts/Utilities/ControllerFinder.cs]: The old version did not have a `set`.

File: Assets/HoloToolkit/Input/Scripts/Utilities/AttachToController.cs (hunk 1 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/AttachToController.cs]: Just following [MSDN naming conventions](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-fields)

File: Assets/HoloToolkit/Input/Scripts/Utilities/ControllerFinder.cs (hunk 2 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/ControllerFinder.cs]: Indeed, I added this intentionally.

Comment (keveleigh) [reply Assets/HoloToolkit/Input/Scripts/Utilities/ControllerFinder.cs]: Why? What does changing the `Element` at runtime do?

**Comment by StephenHodgson** [comment]
> Can we solve this problem by making Element and Handedness public, thus exposing them in the Inspector for anything inheriting this? What do we lose in that case?

That's what I originally did in the first PR, but @radicalad [said he didn't want these fields exposed in the editor](https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1613#discussion_r161838863).

> SolverHandler extends ControllerFinder (for the controller finding ability - go figure) but handles the logic of when to get controllers differently, basically if you set the SolverHandler's enum to "head" it will bypass ControllerFinder etc.

File: Assets/HoloToolkit/Input/Scripts/Utilities/ControllerFinder.cs (hunk 2 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/ControllerFinder.cs]: Potentially you could update the logic being performed in the Solver Handler, or change it's position, without having to destroy and create a new instance of the component/object.

**Comment by StephenHodgson** [comment]
>This is a class we expect others to inherit from, so now they all need custom inspectors?

Not every class will need a custom inspector. For example, all the solvers that inherit from Solver Handler, do not need it.

**Comment by StephenHodgson** [comment]
@Railboy I added a base editor class to inherit from for easier accessibility for future classes.

**Comment by keveleigh** [comment]
> all the solvers that inherit from Solver Handler

I'm not talking about Solver Handler though. I'm specifically talking about classes that inherit directly from `ControllerFinder`.

> Besides, what's so wrong with using editor scripts?

I didn't say anything was wrong with using editor scripts. What's wrong is requiring editor scripts to be written for any class that inherits from a provided abstract class in the Toolkit. Custom editor scripts for MixedRealityCameraParent, etc, are great, but having them be a requirement to see everything possible from an inherited class seems broken to me.

**Comment by keveleigh** [comment]
> basically if you set the SolverHandler's enum to "head" it will bypass ControllerFinder etc.

This sounds like SolverHandler should have a custom editor script to hide these values if the enum is set to "head" in the Inspector, instead of hiding them for everybody.

File: Assets/HoloToolkit/Input/Scripts/Utilities/AttachToController.cs (hunk 1 above)
Comment (keveleigh) [reply Assets/HoloToolkit/Input/Scripts/Utilities/AttachToController.cs]: Consistency seems more important, but we should change them all if we want to follow those naming conventions.

**Comment by StephenHodgson** [comment]
>having them be a requirement to see everything possible from an inherited class seems broken to me.

They're not a requirement, but they do help if you want to have a good separation of concerns for each editor class.

**Comment by keveleigh** [comment]
> They're not a requirement

If I inherit from `ControllerFinder` without a custom editor, the main two settings (`Element` and `Handedness`) won't show up in the inspector, right? That makes the Inspector settings unusable.

**Comment by StephenHodgson** [comment]
> This sounds like SolverHandler should have a custom editor script to hide these values if the enum is set to "head" in the Inspector, instead of hiding them for everybody.

See https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1659#issuecomment-359881956

File: Assets/HoloToolkit/Input/Scripts/Utilities/AttachToController.cs (hunk 1 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/Input/Scripts/Utilities/AttachToController.cs]: Well as far as I can tell, I'm the single biggest contributor and I follow the MSDN guidelines. 
So, it might be better to follow industry standard and fix this in a separate issue.

**Comment by keveleigh** [comment]
>I decided to go with controller finder because these fields seem to be optional.

What's the purpose of `ControllerFinder` if these fields are optional? 

>the same would have also been true if I went and made a custom inspector for the solver handlers

Do we expect anybody to inherit from `SolverHandler`? `Solver` is the abstract class.

>imo, hiding fields and and using the new keywords is a bigger cause for concern.

I don't think we should hide anything. It should all be public in the base class.

>See https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1659#issuecomment-359881956

I don't see anything in there relating to the second point you quoted.

**Comment by StephenHodgson** [comment]
>I don't think we should hide anything. It should all be public in the base class.

fields should never be public and breaks encapsulation rules.

**Comment by keveleigh** [comment]
>Besides the Properties are public and gives access to modifying these fields if necessary.

But doesn't expose them in the editor for any class that inherits, which is the problem we're solving.

**Comment by StephenHodgson** [comment]
> But doesn't expose them in the editor for any class that inherits, which is the problem we're solving.

Which is why we have an editor class for it.

**Comment by radicalad** [comment]
> This time I simply made ControllerFinder Abstract so no one could use it directly on a GameObject. I couldn't think of any reason to really have it unless you needed to inherit anyway. (Mostly a helper).

I'm late to the party, but based on everything I've read, @StephenHodgson you're correct in that Controller finder isn't necessarily helpful by itself - that was why I had initially hidden the variables for the editor.

> This sounds like SolverHandler should have a custom editor script to hide these values if the enum is set to "head" in the Inspector, instead of hiding them for everybody.

I completely agree that SolverHandler should have the custom editor, it is unlikely it will be extended as it just handles the update loop. The real meat is in extending Sovler. This will minimize the editor overhad for anyone extending AttachToController OR ControllerFinder.

**Comment by StephenHodgson** [comment]
>I completely agree that SolverHandler should have the custom editor

@radicalad Cool, yeah I think we're all in agreement here. Just finishing up the custom editor for the solver handler now.

**Comment by StephenHodgson** [comment]
@radicalad just waiting for a reply on those missing script references in the Solver Example Scene for a final review of this PR

File: Assets/HoloToolkit/Input/Scripts/Utilities/AttachToController.cs (hunk 1 above)
Comment (keveleigh) [reply Assets/HoloToolkit/Input/Scripts/Utilities/AttachToController.cs]: From a *very* quick, non-scientific search, I found 17 files that use PascalCase, 17 files that use camelCase (not counting the SWIG-generated files, which all use camelCase), and 2 files that use underscores.

**Comment by StephenHodgson** [comment]
Okay, this PR is good for review.
