### PR TITLE
IL2CPP SpectatorView Fixes

### LINKED ISSUE #2125: May18 branch does not Build IL2CPP APPX
## Overview
When building the APPX package in Visual Studio the build fails to resolve external symbols for the Spectator View assemblies:

```
error LNK2001: unresolved external symbol _IsARKitSessionConfigurationSupported@0
error LNK2001: unresolved external symbol _IsARKitWorldTrackingSessionConfigurationSupported@0
error LNK2001: unresolved external symbol _unity_CreateNativeARSession@0
error LNK2001: unresolved external symbol _session_SetSessionCallbacks@24
error LNK2001: unresolved external symbol _session_SetPlaneAnchorCallbacks@16
error LNK2001: unresolved external symbol _session_SetUserAnchorCallbacks@16
error LNK2001: unresolved external symbol _StartWorldTrackingSession@20
error LNK2001: unresolved external symbol _StartWorldTrackingSessionWithOptions@24
error LNK2001: unresolved external symbol _StartSession@16
error LNK2001: unresolved external symbol _StartSessionWithOptions@20
error LNK2001: unresolved external symbol _PauseSession@4
error LNK2001: unresolved external symbol _HitTest@28
error LNK2001: unresolved external symbol _GetLastHitTestResult@4
error LNK2001: unresolved external symbol _GetVideoTextureHandles@0
error LNK2001: unresolved external symbol _GetAmbientIntensity@0
error LNK2001: unresolved external symbol _GetTrackingQuality@0
error LNK2001: unresolved external symbol _GetARPointCloud@8
error LNK2001: unresolved external symbol _SetCameraNearFar@8
error LNK2001: unresolved external symbol _CapturePixelData@12
error LNK2001: unresolved external symbol _SessionAddUserAnchor@72
error LNK2001: unresolved external symbol _SessionRemoveUserAnchor@8
```
Also two stack overflow warnings:
```
 warning C4717: 'ReplayKitRecorder_set_Controls_m1308905516': recursive on all control paths, function will cause runtime stack overflow
 warning C4717: 'ReplayKitRecorder_get_Controls_m576547881': recursive on all control paths, function will cause runtime stack overflow
```

## Unity Editor Version
2017.4.3f1 & 2018.1.0f2

## Mixed Reality Toolkit Release Version
a2871ff511690107422802f87a427def1b60666e

### LINKED ISSUE #2126: Invalid IL detected warnings in UnityEngine.Internal
## Overview
When building against the .NET scripting backend and generating a Master build of the toolkit, there's many warnings about invalid IL and unresolved p/invoke method calls in Spectator View.

```
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14546(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.HResult Windows.Foundation.IAsyncInfo.get_ErrorCode()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14592(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'System.Void Windows.Foundation.IClosable.Close()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14596(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.DateTime Windows.Foundation.IPropertyValue.GetDateTime()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14601(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Point Windows.Foundation.IPropertyValue.GetPoint()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14602(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Rect Windows.Foundation.IPropertyValue.GetRect()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14604(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Size Windows.Foundation.IPropertyValue.GetSize()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14606(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.TimeSpan Windows.Foundation.IPropertyValue.GetTimeSpan()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14611(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'System.Byte Windows.Foundation.IReference<System.Byte>.Value.get()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14612(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'System.Guid Windows.Foundation.IReference<System.Guid>.Value.get()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14613(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'System.UInt32 Windows.Foundation.IReference<System.UInt32>.Value.get()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14614(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'System.UInt64 Windows.Foundation.IReference<System.UInt64>.Value.get()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14615(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.DateTime Windows.Foundation.IReference<Windows.Foundation.DateTime>.Value.get()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14618(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<Windows.Media.Core.TimedMetadataTrack> Windows.Media.Core.ITimedMetadataTrackProvider.get_TimedMetadataTracks()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14619(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<Windows.Media.IMediaMarker> Windows.Media.SpeechSynthesis.ISpeechSynthesisStream.get_Markers()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14626(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'System.Void Windows.Media.SpeechSynthesis.SpeechSynthesisStream.Close()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14631(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<Windows.Media.IMediaMarker> Windows.Media.SpeechSynthesis.SpeechSynthesisStream.get_Markers()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14634(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<Windows.Media.Core.TimedMetadataTrack> Windows.Media.SpeechSynthesis.SpeechSynthesisStream.get_TimedMetadataTracks()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14686(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.IReference<System.Guid> Windows.Networking.Connectivity.ConnectionProfile.get_ServiceProviderGuid()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14689(System.Int64, System.Int64*)' at IL offset 0x25 referring to invalid Windows Runtime method 'Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<Windows.Networking.Connectivity.AttributedNetworkUsage>> Windows.Networking.Connectivity.ConnectionProfile.GetAttributedNetworkUsageAsync(Windows.Foundation.DateTime, Windows.Foundation.DateTime, Windows.Networking.Connectivity.NetworkUsageStates)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14691(System.Int64, System.Int64*)' at IL offset 0x25 referring to invalid Windows Runtime method 'Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<Windows.Networking.Connectivity.ConnectivityInterval>> Windows.Networking.Connectivity.ConnectionProfile.GetConnectivityIntervalsAsync(Windows.Foundation.DateTime, Windows.Foundation.DateTime, Windows.Networking.Connectivity.NetworkUsageStates)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14694(System.Int64, System.Int64*)' at IL offset 0x1B referring to invalid Windows Runtime method 'Windows.Networking.Connectivity.DataUsage Windows.Networking.Connectivity.ConnectionProfile.GetLocalUsage(Windows.Foundation.DateTime, Windows.Foundation.DateTime)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14695(System.Int64, System.Int64*)' at IL offset 0x20 referring to invalid Windows Runtime method 'Windows.Networking.Connectivity.DataUsage Windows.Networking.Connectivity.ConnectionProfile.GetLocalUsage(Windows.Foundation.DateTime, Windows.Foundation.DateTime, Windows.Networking.Connectivity.RoamingStates)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14697(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<System.String> Windows.Networking.Connectivity.ConnectionProfile.GetNetworkNames()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14698(System.Int64, System.Int64*)' at IL offset 0x2A referring to invalid Windows Runtime method 'Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<Windows.Networking.Connectivity.NetworkUsage>> Windows.Networking.Connectivity.ConnectionProfile.GetNetworkUsageAsync(Windows.Foundation.DateTime, Windows.Foundation.DateTime, Windows.Networking.Connectivity.DataUsageGranularity, Windows.Networking.Connectivity.NetworkUsageStates)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14699(System.Int64, System.Int64*)' at IL offset 0x25 referring to invalid Windows Runtime method 'Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<Windows.Networking.Connectivity.ProviderNetworkUsage>> Windows.Networking.Connectivity.ConnectionProfile.GetProviderNetworkUsageAsync(Windows.Foundation.DateTime, Windows.Foundation.DateTime, Windows.Networking.Connectivity.NetworkUsageStates)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14700(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.IReference<System.Byte> Windows.Networking.Connectivity.ConnectionProfile.GetSignalBars()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14701(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.IReference<System.UInt32> Windows.Networking.Connectivity.DataPlanStatus.get_DataLimitInMegabytes()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14703(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.IReference<System.UInt64> Windows.Networking.Connectivity.DataPlanStatus.get_InboundBitsPerSecond()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14704(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.IReference<System.UInt32> Windows.Networking.Connectivity.DataPlanStatus.get_MaxTransferSizeInMegabytes()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14705(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.IReference<Windows.Foundation.DateTime> Windows.Networking.Connectivity.DataPlanStatus.get_NextBillingCycle()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14706(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.IReference<System.UInt64> Windows.Networking.Connectivity.DataPlanStatus.get_OutboundBitsPerSecond()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14707(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.DateTime Windows.Networking.Connectivity.DataPlanUsage.get_LastSyncTime()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14721(System.Int64, System.Int64*)' at IL offset 0x1B referring to invalid Windows Runtime method 'Windows.Networking.Connectivity.DataUsage Windows.Networking.Connectivity.IConnectionProfile.GetLocalUsage(Windows.Foundation.DateTime, Windows.Foundation.DateTime)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14722(System.Int64, System.Int64*)' at IL offset 0x20 referring to invalid Windows Runtime method 'Windows.Networking.Connectivity.DataUsage Windows.Networking.Connectivity.IConnectionProfile.GetLocalUsage(Windows.Foundation.DateTime, Windows.Foundation.DateTime, Windows.Networking.Connectivity.RoamingStates)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14724(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<System.String> Windows.Networking.Connectivity.IConnectionProfile.GetNetworkNames()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14727(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.IReference<System.Guid> Windows.Networking.Connectivity.IConnectionProfile2.get_ServiceProviderGuid()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14730(System.Int64, System.Int64*)' at IL offset 0x25 referring to invalid Windows Runtime method 'Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<Windows.Networking.Connectivity.ConnectivityInterval>> Windows.Networking.Connectivity.IConnectionProfile2.GetConnectivityIntervalsAsync(Windows.Foundation.DateTime, Windows.Foundation.DateTime, Windows.Networking.Connectivity.NetworkUsageStates)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14732(System.Int64, System.Int64*)' at IL offset 0x2A referring to invalid Windows Runtime method 'Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<Windows.Networking.Connectivity.NetworkUsage>> Windows.Networking.Connectivity.IConnectionProfile2.GetNetworkUsageAsync(Windows.Foundation.DateTime, Windows.Foundation.DateTime, Windows.Networking.Connectivity.DataUsageGranularity, Windows.Networking.Connectivity.NetworkUsageStates)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14733(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.IReference<System.Byte> Windows.Networking.Connectivity.IConnectionProfile2.GetSignalBars()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14734(System.Int64, System.Int64*)' at IL offset 0x25 referring to invalid Windows Runtime method 'Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<Windows.Networking.Connectivity.AttributedNetworkUsage>> Windows.Networking.Connectivity.IConnectionProfile3.GetAttributedNetworkUsageAsync(Windows.Foundation.DateTime, Windows.Foundation.DateTime, Windows.Networking.Connectivity.NetworkUsageStates)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14735(System.Int64, System.Int64*)' at IL offset 0x25 referring to invalid Windows Runtime method 'Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<Windows.Networking.Connectivity.ProviderNetworkUsage>> Windows.Networking.Connectivity.IConnectionProfile4.GetProviderNetworkUsageAsync(Windows.Foundation.DateTime, Windows.Foundation.DateTime, Windows.Networking.Connectivity.NetworkUsageStates)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14736(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.IReference<System.UInt32> Windows.Networking.Connectivity.IDataPlanStatus.get_DataLimitInMegabytes()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14738(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.IReference<System.UInt64> Windows.Networking.Connectivity.IDataPlanStatus.get_InboundBitsPerSecond()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14739(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.IReference<System.UInt32> Windows.Networking.Connectivity.IDataPlanStatus.get_MaxTransferSizeInMegabytes()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14740(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.IReference<Windows.Foundation.DateTime> Windows.Networking.Connectivity.IDataPlanStatus.get_NextBillingCycle()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14741(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.IReference<System.UInt64> Windows.Networking.Connectivity.IDataPlanStatus.get_OutboundBitsPerSecond()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14742(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.DateTime Windows.Networking.Connectivity.IDataPlanUsage.get_LastSyncTime()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14747(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.IReference<System.Byte> Windows.Networking.Connectivity.IIPInformation.get_PrefixLength()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14759(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.IReference<System.Byte> Windows.Networking.Connectivity.IPInformation.get_PrefixLength()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14788(System.Int64, System.Int64*)' at IL offset 0x2A referring to invalid Windows Runtime method 'System.Void Windows.Networking.Sockets.IStreamSocket3.TransferOwnership(System.String, Windows.Networking.Sockets.SocketActivityContext, Windows.Foundation.TimeSpan)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14799(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVector<Windows.Security.Cryptography.Certificates.ChainValidationResult> Windows.Networking.Sockets.IStreamSocketControl2.get_IgnorableServerCertificateErrors()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14817(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<Windows.Security.Cryptography.Certificates.ChainValidationResult> Windows.Networking.Sockets.IStreamSocketInformation2.get_ServerCertificateErrors()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14819(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<Windows.Security.Cryptography.Certificates.Certificate> Windows.Networking.Sockets.IStreamSocketInformation2.get_ServerIntermediateCertificates()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14820(System.Int64, System.Int64*)' at IL offset 0x17 referring to invalid Windows Runtime method 'Windows.Foundation.EventRegistrationToken Windows.Networking.Sockets.IStreamSocketListener.add_ConnectionReceived(Windows.Foundation.TypedEventHandler<Windows.Networking.Sockets.StreamSocketListener, Windows.Networking.Sockets.StreamSocketListenerConnectionReceivedEventArgs>)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14825(System.Int64, System.Int64*)' at IL offset 0x12 referring to invalid Windows Runtime method 'System.Void Windows.Networking.Sockets.IStreamSocketListener.remove_ConnectionReceived(Windows.Foundation.EventRegistrationToken)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14847(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'System.Void Windows.Networking.Sockets.StreamSocket.Close()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14859(System.Int64, System.Int64*)' at IL offset 0x15 referring to invalid Windows Runtime method 'Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<Windows.Networking.EndpointPair>> Windows.Networking.Sockets.StreamSocket.GetEndpointPairsAsync(Windows.Networking.HostName, System.String)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14860(System.Int64, System.Int64*)' at IL offset 0x1A referring to invalid Windows Runtime method 'Windows.Foundation.IAsyncOperation<Windows.Foundation.Collections.IVectorView<Windows.Networking.EndpointPair>> Windows.Networking.Sockets.StreamSocket.GetEndpointPairsAsync(Windows.Networking.HostName, System.String, Windows.Networking.HostNameSortOptions)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14863(System.Int64, System.Int64*)' at IL offset 0x2A referring to invalid Windows Runtime method 'System.Void Windows.Networking.Sockets.StreamSocket.TransferOwnership(System.String, Windows.Networking.Sockets.SocketActivityContext, Windows.Foundation.TimeSpan)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14866(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVector<Windows.Security.Cryptography.Certificates.ChainValidationResult> Windows.Networking.Sockets.StreamSocketControl.get_IgnorableServerCertificateErrors()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14892(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<Windows.Security.Cryptography.Certificates.ChainValidationResult> Windows.Networking.Sockets.StreamSocketInformation.get_ServerCertificateErrors()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14894(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<Windows.Security.Cryptography.Certificates.Certificate> Windows.Networking.Sockets.StreamSocketInformation.get_ServerIntermediateCertificates()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14896(System.Int64, System.Int64*)' at IL offset 0x17 referring to invalid Windows Runtime method 'Windows.Foundation.EventRegistrationToken Windows.Networking.Sockets.StreamSocketListener.add_ConnectionReceived(Windows.Foundation.TypedEventHandler<Windows.Networking.Sockets.StreamSocketListener, Windows.Networking.Sockets.StreamSocketListenerConnectionReceivedEventArgs>)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14902(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'System.Void Windows.Networking.Sockets.StreamSocketListener.Close()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14907(System.Int64, System.Int64*)' at IL offset 0x12 referring to invalid Windows Runtime method 'System.Void Windows.Networking.Sockets.StreamSocketListener.remove_ConnectionReceived(Windows.Foundation.EventRegistrationToken)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14922(System.Int64, System.Int64*)' at IL offset 0x17 referring to invalid Windows Runtime method 'Windows.Foundation.IAsyncOperation<Windows.Security.Cryptography.Certificates.CertificateChain> Windows.Security.Cryptography.Certificates.Certificate.BuildChainAsync(Windows.Foundation.Collections.IIterable<Windows.Security.Cryptography.Certificates.Certificate>)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14923(System.Int64, System.Int64*)' at IL offset 0x25 referring to invalid Windows Runtime method 'Windows.Foundation.IAsyncOperation<Windows.Security.Cryptography.Certificates.CertificateChain> Windows.Security.Cryptography.Certificates.Certificate.BuildChainAsync(Windows.Foundation.Collections.IIterable<Windows.Security.Cryptography.Certificates.Certificate>, Windows.Security.Cryptography.Certificates.ChainBuildingParameters)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14924(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<System.String> Windows.Security.Cryptography.Certificates.Certificate.get_EnhancedKeyUsages()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14940(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.DateTime Windows.Security.Cryptography.Certificates.Certificate.get_ValidFrom()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14941(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.DateTime Windows.Security.Cryptography.Certificates.Certificate.get_ValidTo()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14946(System.Int64, System.Int64*)' at IL offset 0xD referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<Windows.Security.Cryptography.Certificates.Certificate> Windows.Security.Cryptography.Certificates.CertificateChain.GetCertificates(System.Boolean)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14974(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVector<System.String> Windows.Security.Cryptography.Certificates.ChainBuildingParameters.get_EnhancedKeyUsages()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14975(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVector<Windows.Security.Cryptography.Certificates.Certificate> Windows.Security.Cryptography.Certificates.ChainBuildingParameters.get_ExclusiveTrustRoots()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14978(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.DateTime Windows.Security.Cryptography.Certificates.ChainBuildingParameters.get_ValidationTimestamp()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14983(System.Int64, System.Int64*)' at IL offset 0x12 referring to invalid Windows Runtime method 'System.Void Windows.Security.Cryptography.Certificates.ChainBuildingParameters.put_ValidationTimestamp(Windows.Foundation.DateTime)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14988(System.Int64, System.Int64*)' at IL offset 0x17 referring to invalid Windows Runtime method 'Windows.Foundation.IAsyncOperation<Windows.Security.Cryptography.Certificates.CertificateChain> Windows.Security.Cryptography.Certificates.ICertificate.BuildChainAsync(Windows.Foundation.Collections.IIterable<Windows.Security.Cryptography.Certificates.Certificate>)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14989(System.Int64, System.Int64*)' at IL offset 0x25 referring to invalid Windows Runtime method 'Windows.Foundation.IAsyncOperation<Windows.Security.Cryptography.Certificates.CertificateChain> Windows.Security.Cryptography.Certificates.ICertificate.BuildChainAsync(Windows.Foundation.Collections.IIterable<Windows.Security.Cryptography.Certificates.Certificate>, Windows.Security.Cryptography.Certificates.ChainBuildingParameters)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14990(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<System.String> Windows.Security.Cryptography.Certificates.ICertificate.get_EnhancedKeyUsages()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14997(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.DateTime Windows.Security.Cryptography.Certificates.ICertificate.get_ValidFrom()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke14998(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.DateTime Windows.Security.Cryptography.Certificates.ICertificate.get_ValidTo()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15012(System.Int64, System.Int64*)' at IL offset 0xD referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<Windows.Security.Cryptography.Certificates.Certificate> Windows.Security.Cryptography.Certificates.ICertificateChain.GetCertificates(System.Boolean)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15040(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVector<System.String> Windows.Security.Cryptography.Certificates.IChainBuildingParameters.get_EnhancedKeyUsages()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15041(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVector<Windows.Security.Cryptography.Certificates.Certificate> Windows.Security.Cryptography.Certificates.IChainBuildingParameters.get_ExclusiveTrustRoots()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15044(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.DateTime Windows.Security.Cryptography.Certificates.IChainBuildingParameters.get_ValidationTimestamp()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15049(System.Int64, System.Int64*)' at IL offset 0x12 referring to invalid Windows Runtime method 'System.Void Windows.Security.Cryptography.Certificates.IChainBuildingParameters.put_ValidationTimestamp(Windows.Foundation.DateTime)'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15054(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<System.String> Windows.Security.Cryptography.Certificates.ISubjectAlternativeNameInfo.get_DistinguishedName()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15055(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<System.String> Windows.Security.Cryptography.Certificates.ISubjectAlternativeNameInfo.get_DnsName()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15056(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<System.String> Windows.Security.Cryptography.Certificates.ISubjectAlternativeNameInfo.get_EmailName()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15057(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<System.String> Windows.Security.Cryptography.Certificates.ISubjectAlternativeNameInfo.get_IPAddress()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15058(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<System.String> Windows.Security.Cryptography.Certificates.ISubjectAlternativeNameInfo.get_PrincipalName()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15059(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<System.String> Windows.Security.Cryptography.Certificates.ISubjectAlternativeNameInfo.get_Url()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15060(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVector<System.String> Windows.Security.Cryptography.Certificates.ISubjectAlternativeNameInfo2.get_DistinguishedNames()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15061(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVector<System.String> Windows.Security.Cryptography.Certificates.ISubjectAlternativeNameInfo2.get_DnsNames()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15062(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVector<System.String> Windows.Security.Cryptography.Certificates.ISubjectAlternativeNameInfo2.get_EmailNames()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15064(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVector<System.String> Windows.Security.Cryptography.Certificates.ISubjectAlternativeNameInfo2.get_IPAddresses()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15065(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVector<System.String> Windows.Security.Cryptography.Certificates.ISubjectAlternativeNameInfo2.get_PrincipalNames()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15066(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVector<System.String> Windows.Security.Cryptography.Certificates.ISubjectAlternativeNameInfo2.get_Urls()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15067(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<System.String> Windows.Security.Cryptography.Certificates.SubjectAlternativeNameInfo.get_DistinguishedName()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15068(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVector<System.String> Windows.Security.Cryptography.Certificates.SubjectAlternativeNameInfo.get_DistinguishedNames()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15069(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<System.String> Windows.Security.Cryptography.Certificates.SubjectAlternativeNameInfo.get_DnsName()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15070(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVector<System.String> Windows.Security.Cryptography.Certificates.SubjectAlternativeNameInfo.get_DnsNames()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15071(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<System.String> Windows.Security.Cryptography.Certificates.SubjectAlternativeNameInfo.get_EmailName()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15072(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVector<System.String> Windows.Security.Cryptography.Certificates.SubjectAlternativeNameInfo.get_EmailNames()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15074(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<System.String> Windows.Security.Cryptography.Certificates.SubjectAlternativeNameInfo.get_IPAddress()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15075(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVector<System.String> Windows.Security.Cryptography.Certificates.SubjectAlternativeNameInfo.get_IPAddresses()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15076(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<System.String> Windows.Security.Cryptography.Certificates.SubjectAlternativeNameInfo.get_PrincipalName()'. 
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15077(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVector<System.String> Windows.Security.Cryptography.Certificates.SubjectAlternativeNameInfo.get_PrincipalNames()'.
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15078(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<System.String> Windows.Security.Cryptography.Certificates.SubjectAlternativeNameInfo.get_Url()'.
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15079(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVector<System.String> Windows.Security.Cryptography.Certificates.SubjectAlternativeNameInfo.get_Urls()'.
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15101(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<System.Guid> Windows.Networking.Connectivity.IWwanConnectionProfileDetails2.get_PurposeGuids()'.
warning : ILTransform_0027: Invalid IL detected in method 'System.Int64 UnityEngine.Internal.$MethodUtility.$Invoke15105(System.Int64, System.Int64*)' at IL offset 0xB referring to invalid Windows Runtime method 'Windows.Foundation.Collections.IVectorView<System.Guid> Windows.Networking.Connectivity.WwanConnectionProfileDetails.get_PurposeGuids()'.
warning : ILTransform_0000:       MCG : warning MCG0000: [MarshalAs(UnmanagedType=(Default), ElementType=(Default))] with type 'UnityEngine.XR.iOS.UnityARHitTestResult' is invalid.This signature is located on 'UnityEngine.XR.iOS.UnityARHitTestResult UnityEngine.XR.iOS.UnityARSessionNativeInterface.GetLastHitTestResult(System.Int32)'.Additional information: Returning non-blittable struct 'UnityEngine.XR.iOS.UnityARHitTestResult' is not supported in P/invoke.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'IsARKitSessionConfigurationSupported!__Internal' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'IsARKitWorldTrackingSessionConfigurationSupported!__Internal' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'unity_CreateNativeARSession!__Internal' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'session_SetSessionCallbacks!__Internal' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'session_SetPlaneAnchorCallbacks!__Internal' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'session_SetUserAnchorCallbacks!__Internal' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'StartWorldTrackingSession!__Internal' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'StartWorldTrackingSessionWithOptions!__Internal' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'StartSession!__Internal' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'StartSessionWithOptions!__Internal' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'PauseSession!__Internal' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'HitTest!__Internal' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'GetLastHitTestResult!__Internal' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'GetVideoTextureHandles!__Internal' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'GetAmbientIntensity!__Internal' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'GetTrackingQuality!__Internal' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'GetARPointCloud!__Internal' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'SetCameraNearFar!__Internal' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'CapturePixelData!__Internal' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'SessionAddUserAnchor!__Internal' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'SessionRemoveUserAnchor!__Internal' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'InitalizeMarkerDetector!SpectatorViewPlugin' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'TerminateMarkerDetector!SpectatorViewPlugin' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'DetectMarkers!SpectatorViewPlugin' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'GetNumMarkersDetected!SpectatorViewPlugin' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'GetDetectedMarkerIds!SpectatorViewPlugin' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'GetDetectedMarkerPose!SpectatorViewPlugin' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
warning : ILTransform_0000:       MCG : warning MCG0006: Unresolved P/Invoke method 'CheckOpenCVWrapperHasLoaded!SpectatorViewPlugin' in assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because it is not available in UWP applications. Please either use an another API , or use [DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP application APIs.
```

## Unity Editor Version
2017.4.3f1 & 2018.1.0f2

## Mixed Reality Toolkit Release Version
a2871ff511690107422802f87a427def1b60666e

### PR DESCRIPTION
**Pull request by TobyGilbert-ms**
Overview
---
- Fixes for SpectatorView when building with IL2CPP.   This involved wrapping the ARKit Unity plugin to only compile on iOS and in editor.

Changes
---
- Fixes #2125 
- Fixes #2126

### CODE REVIEW

File: Assets/HoloToolkit/SpectatorView/Scripts/Networking/NewDeviceDiscovery.cs [hunk 1]
```diff
@@ -38,7 +35,7 @@ public MarkerDetectionHololens MarkerDetectionHololens
 
         private void Awake()
         {
-#if NETFX_CORE
+#if WINDOWS_UWP
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/SpectatorView/Scripts/Networking/NewDeviceDiscovery.cs]: I wonder what the difference is between `UNITY_WSA` and `WINDOWS_UWP`

Comment (keveleigh) [reply Assets/HoloToolkit/SpectatorView/Scripts/Networking/NewDeviceDiscovery.cs]: I've used `#WINDOWS_UWP` like `#UNITY_WSA && !UNITY_EDITOR`, useful when you're using platform, non-Unity APIs.

Comment (StephenHodgson) [reply Assets/HoloToolkit/SpectatorView/Scripts/Networking/NewDeviceDiscovery.cs]: So is it a logical replacement?

Should we update the usages of `#UNITY_WSA && !UNITY_EDITOR` in other places?

Comment (davidkline-ms) [reply Assets/HoloToolkit/SpectatorView/Scripts/Networking/NewDeviceDiscovery.cs]: We probably should, over time.

File: Assets/HoloToolkit/SpectatorView/Scripts/SpatialSync/MarkerDetectionHololens.cs [hunk 2]
```diff
@@ -1,13 +1,11 @@
 ﻿// Copyright (c) Microsoft Corporation. All rights reserved.
 // Licensed under the MIT License. See LICENSE in the project root for license information.using UnityEngine;
 
+using System;
 using System.Collections.Generic;
+using System.IO;
```
Comment (davidkline-ms) [inline Assets/HoloToolkit/SpectatorView/Scripts/SpatialSync/MarkerDetectionHololens.cs]: System.IO wasn't needed before?

File: Assets/HoloToolkit/SpectatorView/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARAnchor.cs [hunk 3]
```diff
@@ -1,4 +1,5 @@
-﻿using System;
+﻿#if UNITY_IOS
```
Comment (davidkline-ms) [inline Assets/HoloToolkit/SpectatorView/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARAnchor.cs]: no "|| UNITY_EDITOR"?

File: Assets/HoloToolkit/SpectatorView/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARCamera.cs [hunk 4]
```diff
@@ -1,4 +1,5 @@
-﻿using System.Collections;
+﻿#if UNITY_IOS
```
Comment (davidkline-ms) [inline Assets/HoloToolkit/SpectatorView/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARCamera.cs]: no "|| UNITY_EDITOR"?

File: Assets/HoloToolkit/SpectatorView/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARErrorCode.cs [hunk 5]
```diff
@@ -1,4 +1,5 @@
-﻿using System;
+﻿#if UNITY_IOS
```
Comment (davidkline-ms) [inline Assets/HoloToolkit/SpectatorView/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARErrorCode.cs]: no "|| UNITY_EDITOR"?

File: Assets/HoloToolkit/SpectatorView/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARFrame.cs [hunk 6]
```diff
@@ -1,4 +1,5 @@
-﻿using System;
+﻿#if UNITY_IOS
```
Comment (davidkline-ms) [inline Assets/HoloToolkit/SpectatorView/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARFrame.cs]: no "|| UNITY_EDITOR"?

File: Assets/HoloToolkit/SpectatorView/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARRect.cs [hunk 7]
```diff
@@ -1,4 +1,5 @@
-﻿using System;
+﻿#if UNITY_IOS
```
Comment (davidkline-ms) [inline Assets/HoloToolkit/SpectatorView/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARRect.cs]: no "|| UNITY_EDITOR"?

File: Assets/HoloToolkit/SpectatorView/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARLightEstimate.cs [hunk 8]
```diff
@@ -1,4 +1,5 @@
-﻿using System;
+﻿#if UNITY_IOS
```
Comment (davidkline-ms) [inline Assets/HoloToolkit/SpectatorView/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARLightEstimate.cs]: no "|| UNITY_EDITOR"?

File: Assets/HoloToolkit/SpectatorView/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARSize.cs [hunk 9]
```diff
@@ -1,4 +1,5 @@
-﻿using System;
+﻿#if UNITY_IOS
```
Comment (davidkline-ms) [inline Assets/HoloToolkit/SpectatorView/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARSize.cs]: no "|| UNITY_EDITOR"?

File: Assets/HoloToolkit/SpectatorView/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARTrackingQuality.cs [hunk 10]
```diff
@@ -1,4 +1,5 @@
-﻿using System;
+﻿#if UNITY_IOS
```
Comment (davidkline-ms) [inline Assets/HoloToolkit/SpectatorView/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARTrackingQuality.cs]: no "|| UNITY_EDITOR"?

File: Assets/HoloToolkit/SpectatorView/Scripts/Networking/NewDeviceDiscovery.cs (hunk 1 above)
Comment (StephenHodgson) [reply Assets/HoloToolkit/SpectatorView/Scripts/Networking/NewDeviceDiscovery.cs]: Kev, could we add this to best practices and coding guidelines?
I like this table.

File: Assets/HoloToolkit/SpectatorView/UnityARKitPlugin/ARKitRemote/SerializableObjects.cs [hunk 11]
```diff
@@ -318,4 +319,5 @@ public class serializableFromEditorMessage
         public serializableARKitInit arkitConfigMsg;
 
     };
-}
\ No newline at end of file
+}
+#endif
```
[the remark this answers is not in the document]
Comment (TobyGilbert-ms) [reply Assets/HoloToolkit/SpectatorView/UnityARKitPlugin/ARKitRemote/SerializableObjects.cs]: Resolved

File: Assets/HoloToolkit/SpectatorView/UnityARKitPlugin/ARKitRemote/ConnectToEditor.cs [hunk 12]
```diff
@@ -139,3 +140,4 @@ public void DisconnectFromEditor()
     }
 
 }
+#endif
```
[the remark this answers is not in the document]
Comment (TobyGilbert-ms) [reply Assets/HoloToolkit/SpectatorView/UnityARKitPlugin/ARKitRemote/ConnectToEditor.cs]: Resolved

File: Assets/HoloToolkit/SpectatorView/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARCamera.cs [hunk 13]
```diff
@@ -48,3 +49,4 @@ 3. Roll  (the z component) is the rotation about the node's z-axis (in radians)
     
     }
 }
+#endif
```
[the remark this answers is not in the document]
Comment (TobyGilbert-ms) [reply Assets/HoloToolkit/SpectatorView/UnityARKitPlugin/Plugins/iOS/UnityARKit/NativeInterface/ARCamera.cs]: Resolved

**Comment by StephenHodgson** [comment]
Those errors are with the .NET scripting backend and mater build.

**Comment by davidkline-ms** [comment]
These warnings MIGHT be due to the native dll not shipping with the core MRTK?

**Comment by davidkline-ms** [comment]
These changes are good. Let's just investigate the pinvoke warnings.

**Comment by StephenHodgson** [comment]
But wasn't the point of this PR to fix those warnings?

**Comment by davidkline-ms** [comment]
Yes it is. Which is why we need to investigate them :)

**Comment by davidkline-ms** [comment]
I'm investigating the warnings now

**Comment by davidkline-ms** [comment]
Testing a fix now

**Comment by davidkline-ms** [comment]
I have a fix for the pinvoke warnings. I still get the Invalid IL detected (UnityEngine.Internal…). Let's approve Toby's changes and I will open a separate PR with mine.
