### PR TITLE
Execution order/priority system for TransformConstraint

### LINKED ISSUE #9531: Rotation Axis Constraint Ignored By Title Bar
## Describe the bug

The `Rotation Axis Constraint` component is sometimes ignored for the "Grab to manipulate the entire scene" panel title bar. This is particularly annoying as the entire scene pitches up and down to face the camera (verified to happen in build in Hololens 2). Switching to/from `Manual Constraint Selection` (the act of hitting the button itself) magically makes the constraint work as intended.

## To reproduce

1. Open any example scene with a "Grab to manipulate the entire scene" title bar (`HandInteractionExamples` for example).
image

2. Use far proximity manipulation to move the title bar up and down / forward and back.
3. Notice the panel and scene is pitching up and down on X axis to satisfy the `Face User Constraint`, but not the rotation constraint.
grab

## Expected behavior

"Grab to manipulate the entire scene" has a Rotation Axis Constraint which should only allow Y axis yaw rotation

## "Solution"
1. In the `Constraint Manager` in the TitleBar change the constraint selection mode. The act of hitting one of the buttons seems to correct the issue.
2. Use far proximity manipulation to move the title bar up and down / forward and back.
3. Notice the panel and scene now respect the constraint and only rotate on the Y axis.

## Setup

- Unity 2019.4.21f1
- MRTK v2.6.0

## Target platform

- HoloLens
- HoloLens 2

## Additional context

Something is extra cursed about this issue. After cycling between manual and automatic mode, in some scenes the issue is fixed even after restarting the project. In other scenes it *always* happens, and I have to set the selection mode to manual.

### PR DESCRIPTION
**Pull request by Zee2**
## Overview
Currently, our TransformConstraints execute in a non-deterministic order. They are registered in a `HashSet` on the `ConstraintManager`, which for-eaches over the `HashSet` to compute the constraints. `HashSet` is an unordered collection, resulting in non-deterministic evaluation of the constraints.

This is not an issue when the constraints are configured to not affect each other, but there are some situations where multiple constraints are attached to an `ObjectManipulator` that do affect each other. The most notable example is the situation identified by #9531, where we attach both a `RotationAxisConstraint` and a `FaceUserConstraint` to the container of the scene. This is intended to allow users to move the scene around to better fit their workspace, while still facing the user for ergonomics/UX. The rotation constraint is intended to only allow the scene to rotate around the Y-axis (yaw) to face the user, but not allow the scene to pitch up and down/roll.

This intended behavior is only achieved when the `RotationAxisConstraint` happens to execute _after_ the `FaceUserConstraint`. If the `RotationAxisConstraint` happens to execute _before_ the `FaceUserConstraint`, the `FaceUserConstraint` will still rotate the object and override any rotation constraining that the `RotationAxisConstraint` did. 

The ordering of these constraints is currently non-deterministic, as described above, resulting in the constraints often being evaluated in the wrong order, as #9531 reported.

To fix this, an `ExecutionPriority` property has been added to the `TransformConstraint` superclass. Constraints with lower values will be executed before higher values. Constraints with equal values will be tie-broken arbitrarily. (This ensures backwards-compatibility; existing constraints will all default to an execution priority of 0, and will be executed with arbitrary ordering, just like before.)

`ConstraintManager` now internally uses a standard `List` to store constraints. Duplicate detection and the maintaining of the execution priority sorting order is performed with a helper function, `ConstraintUtils.AddWithPriority`. An efficient binary search-based insert-with-priority system allows us to insert/register new constraints with a given priority without needing to re-sort the collection of constraints. When execution priorities are modified at runtime, the collection must be resorted, but given the small number of constraints even possible to add to any given object, and the rarity of users needing to modify any priorities at runtime, this is not a performance worry.

| :warning: Why not use a `SortedSet`, you may ask? :warning:|
|---|
|The answer: the comparer that `SortedSet` uses to determine the ordering of the set is also used by `SortedSet` to check for duplicates. This (questionable) design decision means that `SortedSet` cannot be used to contain two unique constraints that happen to have the same priority. Not sure why it's not possible to use separate uniqueness-keys vs ordering comparer.... but that's just how the cookie crumbles. SortedList is also out, because it doesn't allow you to use a key function, only a distinct <Key,Value> pair.|

In addition, the manual-selection functionality has been slightly revised, so that it can also follow the proper execution order. Before, the manual-selection mode of the `ConstraintManager` simply for-eached an entirely distinct list of constraints. To maintain execution order here, too, we'd have to keep the separate `SelectedConstraints` list sorted, as well. This is unnecessary. We can simply for-each the same list, just as we do in automatic mode, but early-out if the current constraint is not part of our selected list. 

Of course, the prefab for the title bars in the example scenes had to be modified ever so slightly to set the execution orders on the constraints, to fully fix #9531. The prefab has been edited/serialized in 2018.4 LTS.

## Changes
- Fixes: #9531
- `TransformConstraint` now exposes `ExecutionPriority`. Lower numbers execute before higher numbers.
- `ConstraintManager` now maintains execution priority order in both automatic and manual selection modes.
- The custom inspector has been updated to show execution priority next to the entry in the list of constraints. The inspector does not necessarily show them in execution order; this is because the custom inspector has some complex logic that requires consistent indices to delete entries correctly. Future improvements may enhance the custom inspector to support reordering/resorting.
- Title bar prefabs for example scenes have been updated to use the execution priority to ensure #9531 no longer happens.
- Test has been added to improve test coverage, including the use of multiple conflicting constraints, swapping their execution priorities, and ensuring their execution priorities are correctly reflected in the outcome of the evalution.

### CODE REVIEW

File: Assets/MRTK/SDK/Features/Input/Handlers/Constraints/TransformConstraint.cs [hunk 1]
```diff
@@ -41,6 +41,27 @@ public ManipulationProximityFlags ProximityType
...
+        /// Execution order priority of this constraint. Lower numbers will be executed before higher numbers.
+        /// </summary>
+        public int ExecutionPriority
+        {
+            get => executionOrder;
+            set {
+                executionOrder = value;
+
+                // Notify all ConstraintManagers to re-sort these priorities.
+                foreach(var mgr in gameObject.GetComponents<ConstraintManager>())
```
Comment (keveleigh) [inline Assets/MRTK/SDK/Features/Input/Handlers/Constraints/TransformConstraint.cs:58]: Would this list be something we could cache in `Awake`, `Start`, or `OnEnable`? Or would we expect managers to be added/removed at runtime?

Also, do we expect there to be multiple managers on one GameObject?

File: Assets/MRTK/SDK/Features/Utilities/ConstraintExecOrderComparer.cs [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+using Microsoft.MixedReality.Toolkit.UI;
+
+namespace Microsoft.MixedReality.Toolkit.Utilities
+{
+    /// <summary>
+    /// Defines a comparer to sort TransformConstraints by their
+    /// requested execution order, or any other priority
+    /// mechanism that a subclass utilizes.
+    /// </summary>
+    public class ConstraintExecOrderComparer : IComparer<TransformConstraint>
```
Comment (keveleigh) [inline Assets/MRTK/SDK/Features/Utilities/ConstraintExecOrderComparer.cs:15]: Could this be `internal` too, like `ConstraintUtils`?

File: Assets/MRTK/SDK/Features/Input/Handlers/Constraints/TransformConstraint.cs (hunk 1 above)
Comment (Zee2) [reply Assets/MRTK/SDK/Features/Input/Handlers/Constraints/TransformConstraint.cs:58]: Yes, this can be cached. I'll look into this.

Yes, we do expect multiple managers to be present. Not sure why, but there is explicit support for them in our tests and the code.

File: Assets/MRTK/SDK/Features/Utilities/ConstraintExecOrderComparer.cs (hunk 2 above)
Comment (Zee2) [reply Assets/MRTK/SDK/Features/Utilities/ConstraintExecOrderComparer.cs:15]: If we make it `internal`, the custom inspector GUI will not be able to access the comparer. I made this futureproof, for if/when we want to improve the custom inspector to also sort/manage the ordering of the constraints.

File: Assets/MRTK/SDK/Features/Input/Handlers/Constraints/TransformConstraint.cs (hunk 1 above)
Comment (Zee2) [reply Assets/MRTK/SDK/Features/Input/Handlers/Constraints/TransformConstraint.cs:58]: I didn't cache it here because I do not expect users to edit priorities at runtime very often, if at all. I can add it though!

Comment (keveleigh) [reply Assets/MRTK/SDK/Features/Input/Handlers/Constraints/TransformConstraint.cs:58]: > I didn't cache it here because I do not expect users to edit priorities at runtime very often, if at all

That seems reasonable! If this is a super low freq call, we can probably leave it as-is.

That does bring up an additional question: is there a use-case for changing this value at runtime? Or should we just make it an edit-time configuration (like the way Unity handles custom script execution order. I don't believe that can be changed at runtime)

Comment (Zee2) [reply Assets/MRTK/SDK/Features/Input/Handlers/Constraints/TransformConstraint.cs:58]: I had similar thoughts. But given that the existing constraint system seems geared up to support modifying/altering/doing basically everything with constraints at runtime already, I didn't want to introduce a new mechanism that _didn't_ support runtime editing. I figured that if the entire constraint system was already set up to support runtime editing, I should follow that pattern, because it might have been made that way for a reason.

File: Assets/MRTK/SDK/Features/Utilities/ConstraintExecOrderComparer.cs (hunk 2 above)
Comment (CDiaz-MS) [reply Assets/MRTK/SDK/Features/Utilities/ConstraintExecOrderComparer.cs:15]: Have you tried InternalsVisibleTo? https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.internalsvisibletoattribute?view=net-5.0

File: Assets/MRTK/SDK/Features/Input/Handlers/Constraints/TransformConstraint.cs (hunk 1 above)
Comment (Zee2) [reply Assets/MRTK/SDK/Features/Input/Handlers/Constraints/TransformConstraint.cs:58]: Given the minimal amount of code to support runtime exec order editing, I figured it's a good benefit at very little cost.

Comment (Zee2) [reply Assets/MRTK/SDK/Features/Input/Handlers/Constraints/TransformConstraint.cs:58]: Oh, here's a use case. Setting up constraints in code. If we made it a readonly value, you couldn't set exec order in code when you're setting up your constraints at runtime.

Comment (Zee2) [reply Assets/MRTK/SDK/Features/Input/Handlers/Constraints/TransformConstraint.cs:58]: Going to keep this as-is and resolve.

File: Assets/MRTK/SDK/Features/Utilities/ConstraintUtils.cs [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+        /// break duplicate-checking with SortedSet, as well as SortedSet not being
+        /// able to handle runtime-changing exec priorities.
+        /// </summary>
+        /// <param name="constraintList">Sorted list of existing priorites</param>
+        /// <param name="constraint">Constraint to add</param>
+        /// <param name="comparer">ConstraintExecOrderComparer for comparing two constraint priorities</param>
+        internal static void AddWithPriority(ref List<TransformConstraint> constraintList, TransformConstraint constraint, ConstraintExecOrderComparer comparer)
+        {
+            if(constraintList.Contains(constraint))
+            {
```
Comment (CDiaz-MS) [inline Assets/MRTK/SDK/Features/Utilities/ConstraintUtils.cs:27]:
```suggestion
        {
            if (constraintList.Contains(constraint))
            {
```

File: Assets/MRTK/SDK/Features/Utilities/ConstraintUtils.cs [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+                return;
+            }
+
+            if(constraintList.Count == 0 || comparer.Compare(constraintList[constraintList.Count-1], constraint) < 0)
```
Comment (CDiaz-MS) [inline Assets/MRTK/SDK/Features/Utilities/ConstraintUtils.cs:31]:
```suggestion

            if (constraintList.Count == 0 || comparer.Compare(constraintList[constraintList.Count-1], constraint) < 0)
```

File: Assets/MRTK/SDK/Features/Utilities/ConstraintUtils.cs [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+            {
+                constraintList.Add(constraint);
+                return;
+            }
+            else if(comparer.Compare(constraintList[0], constraint) > 0)
+            {
```
Comment (CDiaz-MS) [inline Assets/MRTK/SDK/Features/Utilities/ConstraintUtils.cs:37]:
```suggestion
            }
            else if (comparer.Compare(constraintList[0], constraint) > 0)
            {
```

File: Assets/MRTK/SDK/Features/Utilities/ConstraintUtils.cs [hunk 6]
```diff
@@ -0,0 +1,54 @@
...
+                constraintList.Insert(0, constraint);
+                return;
+            }
+            else
+            {
+                int idx = constraintList.BinarySearch(constraint, comparer);
+                if(idx < 0)
+                {
```
Comment (CDiaz-MS) [inline Assets/MRTK/SDK/Features/Utilities/ConstraintUtils.cs:45]:
```suggestion
                int idx = constraintList.BinarySearch(constraint, comparer);
                if (idx < 0)
                {
```

**Review by CDiaz-MS — APPROVED** [review]
Couple of nits, this is a great improvement to the constraint manager.

File: Assets/MRTK/SDK/Features/Utilities/ConstraintExecOrderComparer.cs (hunk 2 above)
Comment (Zee2) [reply Assets/MRTK/SDK/Features/Utilities/ConstraintExecOrderComparer.cs:15]: @CDiaz-MS I didn't know we were using this in editor code. I figured it was a tests-only thing.

File: Assets/MRTK/SDK/Features/Input/Handlers/Constraints/TransformConstraint.cs (hunk 1 above)
Comment (keveleigh) [reply Assets/MRTK/SDK/Features/Input/Handlers/Constraints/TransformConstraint.cs:58]: Works for me!

File: Assets/MRTK/SDK/Features/Utilities/ConstraintExecOrderComparer.cs (hunk 2 above)
Comment (Zee2) [reply Assets/MRTK/SDK/Features/Utilities/ConstraintExecOrderComparer.cs]: @CDiaz-MS fixed.
