### PR TITLE
Fix spam of ReflectionTypeLoadExceptions in some scenarios in Unity Editor.  Fixes #5419.

### LINKED ISSUE #5419: Constant spam of ReflectTypeLoadException errors
## Describe the bug
A constant error spam (5 errors per second) originating from the MRTK editor UI that makes the app unusable in the editor and drastically slows Unity's performance. 

image

Looks like this is the callstack:

```
ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
  at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 
  at Microsoft.MixedReality.Toolkit.Utilities.Facades.ServiceFacadeEditor+<>c.<InitializeServiceInspectorLookup>b__17_0 (System.Reflection.Assembly assembly) [0x00000] in <ff1d1f21579742b3b5d8b352022b1ce8>:0 
  at System.Linq.Parallel.SelectManyQueryOperator`3+SelectManyQueryOperatorEnumerator`1[TLeftInput,TRightInput,TOutput,TLeftKey].MoveNext (TOutput& currentElement, System.Linq.Parallel.Pair`2[TLeftKey,System.Int32]& currentKey) [0x00061] in <1b13ba6391c74847bbc3eddc86df7eee>:0 
  at System.Linq.Parallel.SelectQueryOperator`2+SelectQueryOperatorEnumerator`1[TInput,TOutput,TKey].MoveNext (TOutput& currentElement, TKey& currentKey) [0x00008] in <1b13ba6391c74847bbc3eddc86df7eee>:0 
  at System.Linq.Parallel.WhereQueryOperator`1+WhereQueryOperatorEnumerator`1[TInputOutput,TKey].MoveNext (TInputOutput& currentElement, TKey& currentKey) [0x00051] in <1b13ba6391c74847bbc3eddc86df7eee>:0 
  at System.Linq.Parallel.SelectQueryOperator`2+SelectQueryOperatorEnumerator`1[TInput,TOutput,TKey].MoveNext (TOutput& currentElement, TKey& currentKey) [0x00008] in <1b13ba6391c74847bbc3eddc86df7eee>:0 
  at System.Linq.Parallel.PipelineSpoolingTask`2[TInputOutput,TIgnoreKey].SpoolingWork () [0x00042] in <1b13ba6391c74847bbc3eddc86df7eee>:0 
  at System.Linq.Parallel.SpoolingTaskBase.Work () [0x0005d] in <1b13ba6391c74847bbc3eddc86df7eee>:0 
  at System.Linq.Parallel.QueryTask.BaseWork (System.Object unused) [0x00015] in <1b13ba6391c74847bbc3eddc86df7eee>:0 
  at System.Linq.Parallel.QueryTask+<>c.<.cctor>b__10_0 (System.Object o) [0x00000] in <1b13ba6391c74847bbc3eddc86df7eee>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x00025] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 
  at System.Threading.Tasks.Task.Execute () [0x00010] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 
Rethrow as AggregateException: One or more errors occurred.
  at System.Linq.Parallel.QueryTaskGroupState.QueryEnd (System.Boolean userInitiatedDispose) [0x00081] in <1b13ba6391c74847bbc3eddc86df7eee>:0 
  at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1[T].MoveNextSlowPath () [0x001c2] in <1b13ba6391c74847bbc3eddc86df7eee>:0 
  at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1[T].MoveNext () [0x00054] in <1b13ba6391c74847bbc3eddc86df7eee>:0 
  at System.Linq.Parallel.QueryOpeningEnumerator`1[TOutput].MoveNext () [0x0002b] in <1b13ba6391c74847bbc3eddc86df7eee>:0 
  at Microsoft.MixedReality.Toolkit.Utilities.Facades.ServiceFacadeEditor.InitializeServiceInspectorLookup () [0x00109] in <ff1d1f21579742b3b5d8b352022b1ce8>:0 
  at Microsoft.MixedReality.Toolkit.Utilities.Facades.ServiceFacadeEditor.DrawGizmos (Microsoft.MixedReality.Toolkit.Utilities.Facades.ServiceFacade facade, UnityEditor.GizmoType type) [0x0002f] in <ff1d1f21579742b3b5d8b352022b1ce8>:0 
UnityEditor.Handles:Internal_FinishDrawingCamera()
UnityEditor.Handles:Internal_FinishDrawingCamera(Camera) (at C:\buildslave\unity\build\Editor\Mono\Handles.bindings.cs:50)
UnityEditor.Handles:DrawCameraStep2(Camera, DrawCameraMode) (at C:\buildslave\unity\build\Editor\Mono\Handles.cs:1341)
UnityEditor.SceneView:OnGUI() (at C:\buildslave\unity\build\Editor\Mono\SceneView\SceneView.cs:1946)
System.Reflection.MonoMethod:InternalInvoke()
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MethodBase:Invoke(Object, Object[])
UnityEditor.HostView:Invoke(String, Object) (at C:\buildslave\unity\build\Editor\Mono\HostView.cs:342)
UnityEditor.HostView:Invoke(String) (at C:\buildslave\unity\build\Editor\Mono\HostView.cs:336)
UnityEditor.HostView:InvokeOnGUI(Rect, Rect) (at C:\buildslave\unity\build\Editor\Mono\HostView.cs:302)
UnityEditor.DockArea:DrawView(Rect, Rect, Boolean, Boolean, Boolean) (at C:\buildslave\unity\build\Editor\Mono\GUI\DockArea.cs:361)
UnityEditor.DockArea:OldOnGUI() (at C:\buildslave\unity\build\Editor\Mono\GUI\DockArea.cs:320)
UnityEngine.Experimental.UIElements.IMGUIContainer:DoOnGUI(Event, Matrix4x4, Rect, Boolean) (at C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:244)
UnityEngine.Experimental.UIElements.IMGUIContainer:HandleIMGUIEvent(Event, Matrix4x4, Rect) (at C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:438)
UnityEngine.Experimental.UIElements.IMGUIContainer:HandleIMGUIEvent() (at C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:412)
UnityEngine.Experimental.UIElements.ImmediateStylePainter:DrawImmediate(Action) (at C:\buildslave\unity\build\Modules\UIElements\ImmediateStylePainter.cs:113)
UnityEngine.Experimental.UIElements.IMGUIContainer:DoRepaint(IStylePainter) (at C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:98)
UnityEngine.Experimental.UIElements.VisualElement:Repaint(IStylePainter) (at C:\buildslave\unity\build\Modules\UIElements\VisualElement.cs:862)
UnityEngine.Experimental.UIElements.VisualTreeRepaintUpdater:PaintSubTree(VisualElement, Matrix4x4, Boolean, Boolean, Rect) (at C:\buildslave\unity\build\Modules\UIElements\VisualTreeRepaintUpdater.cs:310)
UnityEngine.Experimental.UIElements.VisualTreeRepaintUpdater:PaintSubTreeChildren(VisualElement, Matrix4x4, Boolean, Boolean, Rect) (at C:\buildslave\unity\build\Modules\UIElements\VisualTreeRepaintUpdater.cs:328)
UnityEngine.Experimental.UIElements.VisualTreeRepaintUpdater:PaintSubTree(VisualElement, Matrix4x4, Boolean, Boolean, Rect) (at C:\buildslave\unity\build\Modules\UIElements\VisualTreeRepaintUpdater.cs:314)
UnityEngine.Experimental.UIElements.VisualTreeRepaintUpdater:Update() (at C:\buildslave\unity\build\Modules\UIElements\VisualTreeRepaintUpdater.cs:35)
UnityEngine.Experimental.UIElements.VisualTreeUpdater:UpdateVisualTree() (at C:\buildslave\unity\build\Modules\UIElements\VisualTreeUpdater.cs:70)
UnityEngine.Experimental.UIElements.Panel:Repaint(Event) (at C:\buildslave\unity\build\Modules\UIElements\Panel.cs:507)
UnityEngine.Experimental.UIElements.UIElementsUtility:DoDispatch(BaseVisualElementPanel) (at C:\buildslave\unity\build\Modules\UIElements\UIElementsUtility.cs:230)
UnityEngine.Experimental.UIElements.UIElementsUtility:ProcessEvent(Int32, IntPtr) (at C:\buildslave\unity\build\Modules\UIElements\UIElementsUtility.cs:68)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at C:\buildslave\unity\build\Modules\IMGUI\GUIUtility.cs:179)
```

```
GUI Error: You are pushing more GUIClips than you are popping. Make sure they are balanced.
UnityEngine.DebugLogHandler:Internal_Log()
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
UnityEngine.Experimental.UIElements.IMGUIContainer:DoOnGUI(Event, Matrix4x4, Rect, Boolean) (at C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:361)
UnityEngine.Experimental.UIElements.IMGUIContainer:HandleIMGUIEvent(Event, Matrix4x4, Rect) (at C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:435)
UnityEngine.Experimental.UIElements.IMGUIContainer:HandleIMGUIEvent() (at C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:412)
UnityEngine.Experimental.UIElements.ImmediateStylePainter:DrawImmediate(Action) (at C:\buildslave\unity\build\Modules\UIElements\ImmediateStylePainter.cs:113)
UnityEngine.Experimental.UIElements.IMGUIContainer:DoRepaint(IStylePainter) (at C:\buildslave\unity\build\Modules\UIElements\IMGUIContainer.cs:98)
UnityEngine.Experimental.UIElements.VisualElement:Repaint(IStylePainter) (at C:\buildslave\unity\build\Modules\UIElements\VisualElement.cs:862)
UnityEngine.Experimental.UIElements.VisualTreeRepaintUpdater:PaintSubTree(VisualElement, Matrix4x4, Boolean, Boolean, Rect) (at C:\buildslave\unity\build\Modules\UIElements\VisualTreeRepaintUpdater.cs:310)
UnityEngine.Experimental.UIElements.VisualTreeRepaintUpdater:PaintSubTreeChildren(VisualElement, Matrix4x4, Boolean, Boolean, Rect) (at C:\buildslave\unity\build\Modules\UIElements\VisualTreeRepaintUpdater.cs:328)
UnityEngine.Experimental.UIElements.VisualTreeRepaintUpdater:PaintSubTree(VisualElement, Matrix4x4, Boolean, Boolean, Rect) (at C:\buildslave\unity\build\Modules\UIElements\VisualTreeRepaintUpdater.cs:314)
UnityEngine.Experimental.UIElements.VisualTreeRepaintUpdater:Update() (at C:\buildslave\unity\build\Modules\UIElements\VisualTreeRepaintUpdater.cs:35)
UnityEngine.Experimental.UIElements.VisualTreeUpdater:UpdateVisualTree() (at C:\buildslave\unity\build\Modules\UIElements\VisualTreeUpdater.cs:70)
UnityEngine.Experimental.UIElements.Panel:Repaint(Event) (at C:\buildslave\unity\build\Modules\UIElements\Panel.cs:507)
UnityEngine.Experimental.UIElements.UIElementsUtility:DoDispatch(BaseVisualElementPanel) (at C:\buildslave\unity\build\Modules\UIElements\UIElementsUtility.cs:230)
UnityEngine.Experimental.UIElements.UIElementsUtility:ProcessEvent(Int32, IntPtr) (at C:\buildslave\unity\build\Modules\UIElements\UIElementsUtility.cs:68)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at C:\buildslave\unity\build\Modules\IMGUI\GUIUtility.cs:179)
```

## Expected behavior

No errors

## Screenshots

image

## Your Setup (please complete the following information)

- Unity Version [2018.3.10f1]
- MRTK Version [2.0.0-20190718.5]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2

## Additional context

The issue went away when we upgraded the project to Unity 2108.4.4f1; the latest LTS. Its not clear exactly what in Unity2018.3.10.

### PR DESCRIPTION
**Pull request by AdamMitchell-ms**
## Overview
In one consuming app, I observed a constant stream of ReflectionTypeLoadExceptions in the Editor.  To resolve this issue, I've implemented fix suggested in [a stackoverflow post](https://stackoverflow.com/questions/7889228/how-to-prevent-reflectiontypeloadexception-when-calling-assembly-gettypes).  Namely, to use an extension to catch the exception and return the types which loaded successfully.

Unknown to me: what causes this exception to get thrown in the first place?  Does it indicate some further issue that should be resolved?  In the mean time, this unblocks me.

## Changes
- Fixes: #5419.

### CODE REVIEW

**Comment by AdamMitchell-ms** [comment]
@davidkline-ms , Do you have any objection to this fix/workaround?  From your post on #5419, it sounds like you may have more info about the root cause than I have.

**Comment by wiwei** [comment]
@AdamMitchel-ms I think that the background here was that there was some offline conversation that the problem in that linked issue was no longer hitting after updating to a newer version of Unity, though the underlying issue was never actually clearly resolved. I think that some other folks have hit this as well outside of the MRTK core team intermittently (and some have had some success by just closing Unity and opening it again).

I think that if you import DLLs that weren't built in Unity this will also happen (i.e. Unity can't resolve the types so this happens).

Also just from generally looking online it looks like this is just unfortunately the shape of the GetTypes() API, so this should be a fine workaround.

File: Assets/MixedRealityToolkit/Inspectors/Utilities/AssemblyExtensions.cs [hunk 1]
```diff
@@ -0,0 +1,25 @@
+﻿// Copyright (c) Microsoft Corporation. All rights reserved.
+// Licensed under the MIT License. See LICENSE in the project root for license information.﻿
+
+using System;
+using System.Collections.Generic;
+using System.Linq;
+using System.Reflection;
+
+namespace Microsoft.MixedReality.Toolkit.Utilities
```
Comment (wiwei) [inline Assets/MixedRealityToolkit/Inspectors/Utilities/AssemblyExtensions.cs]: Note that this is probably better located in this folder and in this namespace:

https://github.com/microsoft/MixedRealityToolkit-Unity/tree/mrtk_development/Assets/MixedRealityToolkit/Extensions

Just to be consistent with the rest of the extension.

If this is truly editor-only (I'm not sure about this, but just listing this as an option in case it's relevant), it can go here:

https://github.com/microsoft/MixedRealityToolkit-Unity/tree/mrtk_development/Assets/MixedRealityToolkit/Extensions/EditorClassExtensions

Comment (AdamMitchell-ms) [reply Assets/MixedRealityToolkit/Inspectors/Utilities/AssemblyExtensions.cs]: Ok, moved it next to the other extension classes and updated the namespace.

Comment (AdamMitchell-ms) [reply Assets/MixedRealityToolkit/Inspectors/Utilities/AssemblyExtensions.cs]: @wiwei , addressed your comment.
Can you
`/azp run`
for me?

**Comment by keveleigh** [comment]
Looks like the failure is due to code validation:

```
An empty doccomment was found in F:\aipmragent_work\1\s\Assets\MixedRealityToolkit\Extensions\AssemblyExtensions.cs at line 15 
Delete the line or add a description 
        /// <param name="this"></param>
An empty doccomment was found in F:\aipmragent_work\1\s\Assets\MixedRealityToolkit\Extensions\AssemblyExtensions.cs at line 16 
Delete the line or add a description 
        /// <returns></returns>
```

**Comment by AdamMitchell-ms** [comment]
> Looks like the failure is due to code validation:
> 
> ```
> An empty doccomment was found in F:\aipmragent_work\1\s\Assets\MixedRealityToolkit\Extensions\AssemblyExtensions.cs at line 15 
> Delete the line or add a description 
>         /// <param name="this"></param>
> An empty doccomment was found in F:\aipmragent_work\1\s\Assets\MixedRealityToolkit\Extensions\AssemblyExtensions.cs at line 16 
> Delete the line or add a description 
>         /// <returns></returns>
> ```

I'll remove those lines.

**Comment by AdamMitchell-ms** [comment]
Ok, Just pushed up a fix.  Can someone run the build again for me?

@keveleigh or @wiwei

**Comment by julenka** [comment]
@adammitchell-ms it looks like there are some conflicts. Can you resolve and then I'll re-run /azp?

**Comment by AdamMitchell-ms** [comment]
@keveleigh or @julenka , can you re-queue the build?  The failure in BoundingBoxTests.ScaleViaNearInteration, which I believe was a transient unrelated issue.

**Comment by AdamMitchell-ms** [comment]
Oh yeah, and also I did resolve the conflict.

**Comment by davidkline-ms** [comment]
>  Do you have any objection to this fix/workaround?

No objections :)
