### PR TITLE
Fix profile switching related issues

### LINKED ISSUE #4289: Changing ActiveProfile at runtime does not work
(Ported to GitHub, reference 21522491)

Issue encountered using MRTK V2.0.0 RC1 Refresh

There's a property on MRTK.Instance called ActiveProfile, which supposedly will
swap out the profile and reset the configuration, but when I attempted to call
this I ran into a bunch of the below errors, and fixing just the camera related
errors exposed a lot more.  I managed to "fix" these locally by actively by
hunting for objects that weren't cleaned up and fixing them up.  Below is most
of the set of changes I had to make to allow swapping active profiles.

**Changes I made to get this working in my project:**

- [x]  MixedRealityToolkit.cs:UpdateAllServices

    - [x]  Removal of activeSystems, and registeredMixedRealityServices in foreach
        loop was causing loop to fail due to the collection changing.  Added a
        ToList() on each to fix.

    [davidkline-ms] addressing with try/catch(InvalidOperationException) for better performance.

- [x]  UIRaycastCamera

    - [x]  Had to change destroy call to DestroyImmediate in FocusProvider.cs from
        Destroy, as we needed to clean up references in a single frame.

    - [ ]  Added IsNull check in MixedRealityInputModule.cs:
        GetMousePointerEventDataForMrtkPointer to check for a destroyed
        RaycastCamera, and find the new one in the scene if so.  Also since
        there is some delay I added a short circuit return for when
        RaycastCamera was null.

- [ ]  ShellHandRayPointer

    - [ ]  Any hand ray or controller pointer could become stale when swapping
        profiles, because we do not disable the linerenderer 100% of the time
        when setting a shell hand ray pointer inactive.  Had to add a foreach
        loop to OnPostSceneQuery in the !IsActive branch to manually disable all
        linerenderers.

- [x] Gaze Cursor

    - [x] Had to add setting the GazeCursor in GazeProvider.OnEnable, since it was not swapping gaze cursors when swapping profiles.

[davidkline-ms] Solving using DestroyImmediate to ensure correct re-creating.

- [ ]  WindowsMixedRealityDeviceManager: Disable()

    - [ ]  Had to set gestureRecognizer, and NavigationRecognizer to null after
        dispose.  We were trying to ref the disposed instances.

- [ ] GestureRecognizreExtensions

    - [ ]  Had to add null check for recognizer to avoid accessing disposed or
        destroyed instance.

- [ ]  Disabling the gaze cursor in the input profile does not work

    - [ ]  Added a force override for force disabling the gaze cursor in BaseCursor

- [ ]  InputSimulationService::OnHandDataChanged

    - [ ]  Added null checks for second handDataProvider since calling
        UpdateHandInputSource on Left would cause handDataProvider to be
        destroyed, so UpdateHandInputSource on the right hand would throw a null
        ref

**Issues I encountered but did not solve**:

-   Gaze cursor behavior is wonky after swapping input profiles.  Gaze cursor
    would not become active until the first time the user air taps.

-   Gaze provider sometimes falls back to gaze when swapping to eye tracking.

There's already a UIRaycastCamera in the scene. It will be ignored, so please
delete it to avoid confusion.

UnityEngine.Debug:LogError(Object, Object)  
Microsoft.MixedReality.Toolkit.Input.FocusProvider:Initialize() (at
Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs:416)  
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeAllServices() (at
Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:931)  
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator()
(at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:477)  
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ResetConfiguration(MixedRealityToolkitConfigurationProfile)
(at Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs:116) 

 

MissingReferenceException: The object of type 'Camera' has been destroyed but
you are still trying to access it.  
Your script should either check if it is null or you should not destroy the
object.  
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputModule.GetMousePointerEventDataForMrtkPointer
(Microsoft.MixedReality.Toolkit.Input.MixedRealityInputModule+PointerData
pointerData) (at
Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputModule.cs:176)  
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputModule.GetMousePointerEventData
(System.Int32 pointerId) (at
Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputModule.cs:164)  
UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent (System.Int32
id) (at
C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/InputModules/StandaloneInputModule.cs:504)  
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputModule.Process () (at
Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputModule.cs:117)  
UnityEngine.EventSystems.EventSystem.Update () (at
C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/EventSystem.cs:377)

### LINKED ISSUE #5185: Can't switch MRTK profile at runtime
## The bug
Scenario: single Unity project for multi-platform application. You cannot change the MRTK profile at runtime. For example, if you want to run something like: 

`if(MixedRealityToolkit.Instance.ActiveProfile != SomeProfile)
{
      MixedRealityToolkit.Instance.ActiveProfile = SomeProfile;
}`

It's ineffective. Am I wrong with these lines of code?

## Expected behavior
Dynamically change the MRTK profile at runtime.

##  Setup

- Unity Version: 2018.3.12f1
- MRTK 2.0.0 RC1

## Target Platform 
UWP:
- Desktop
- HoloLens
- HoloLens 2
- WMR immersive

### LINKED ISSUE #6061: Active Profile Switching - Unity UI is not responding
## Describe the bug
Unity UI examples in the HandInteractionExample scene do not respond to the input when the scene is loaded through Examples Hub using the Scene System. It works fine when opened as a single scene. 

## To reproduce
1. Open MRTKExamplesHub
2. Run
3. Select Hand Interaction Examples menu (first one from the left)
4. Interact with Unity UI examples on the right side of the scene

## Expected behavior
Can interact with Unity UI 

## Screenshots
2019-09-24 11_46_13-Unity 2018 4 7f1 Personal - MRTKExamplesHub unity - MixedRealityToolkit-Unity -
2019-09-24 11_45_30-Unity 2018 4 7f1 Personal - MRTKExamplesHub unity - MixedRealityToolkit-Unity -

## Your Setup (please complete the following information)
- Unity Version [2018.4.7f1]
- MRTK Version [prelease 2.1.0 stabilization]

## Target Platform (please complete the following information)
Editor and HoloLens 2 device.

### LINKED ISSUE #8737: Changing MRTK profiles at runtime before MRTK initialization does not work
## Describe the bug

[This part in documentation](https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.5.0/Documentation/MixedRealityConfigurationGuide.html#swapping-profiles-prior-to-mrtk-initialization) says that it's possible to change the MRTK profile before MRTK initialization. I created a script that sets active profile to another profile than in the MRTK object in my scene. Then I set the script to a higher priority than MRTK in script execution order. Then when pressing Play in Unity Editor the following errors are thrown and MRTK profile remains the same:

```
There's already a IMixedRealityInputSystem.Mixed Reality Input System registered!
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterServiceInternal(Type, IMixedRealityService) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:893)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterServiceInternal(IMixedRealityInputSystem) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:919)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterServiceInternal(Boolean, Type, SupportedPlatforms, Object[]) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:275)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterService(Type, SupportedPlatforms, Object[]) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:196)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator() (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:410)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeNewProfile(MixedRealityToolkitConfigurationProfile) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:123)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Update() (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:689)
``` 

``` 
Failed to start the Input System!
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator() (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:412)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeNewProfile(MixedRealityToolkitConfigurationProfile) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:123)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Update() (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:689)
``` 

``` 
There's already a IMixedRealityFocusProvider.Focus Provider registered!
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterServiceInternal(Type, IMixedRealityService) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:893)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterServiceInternal(IMixedRealityFocusProvider) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:919)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterServiceInternal(Boolean, Type, SupportedPlatforms, Object[]) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:275)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterService(Type, SupportedPlatforms, Object[]) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:196)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator() (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:416)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeNewProfile(MixedRealityToolkitConfigurationProfile) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:123)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Update() (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:689)
``` 

``` 
Failed to register the focus provider! The input system will not function without it.
UnityEngine.Debug:LogError(Object)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator() (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:418)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeNewProfile(MixedRealityToolkitConfigurationProfile) (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:123)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Update() (at Assets/MRTK/Core/Services/MixedRealityToolkit.cs:689)
``` 

## To reproduce

1. Create Unity scene with MRTK standard assets
2. Create a script that changes the MRTK profile like in [this example](https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.5.0/Documentation/MixedRealityConfigurationGuide.html#swapping-profiles-prior-to-mrtk-initialization).
3. Set the script to a higher priority as MRTK in Unity script execution order.
4. Press Play in Unity
5. See the errors above printed
6. See that MRTK profile has not changed

## Expected behavior

The MRTK profile should be changed.

## Your setup (please complete the following information)

- Unity 2019.4.11f1
- MRTK 2.5.0

## Target platform (please complete the following information)

- HoloLens 1
- HoloLens 2

## Additional context

It would be nice to only have one scene that can be build for both HoloLens 1 and HoloLens 2. Currently I am using two equal scenes with different profile configurations for HoloLens 1 and HoloLens 2. Every change in a scene must be manually copied to the other scene and vice versa.

### PR DESCRIPTION
**Pull request by MaxWang-MS**
## Overview
This PR builds on #8260 and addresses a number of profile switching related issues:
- Currently the [prior MRTK initialization profile swapping](https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.5.0/Documentation/MixedRealityConfigurationGuide.html#swapping-profiles-prior-to-mrtk-initialization) does not work as intend. This PR adds a new static method to achieve that goal.
- The runtime profile switching feature has some issues related to Unity UI (UGUI not responding after profile switch) due to the lifecycle of input module being not completely dependent on the input system in certain cases. This PR makes sure the input module behaves correctly after profile switching.

## Changes
- Fixes #4289, fixes #5185, fixes #6061, fixes #8737 

## Verification
The PR should be tested using both Legacy XR and XRSDK pipelines as during development pipeline specific issues were identified. I have tested both pipelines in editor play mode, HL2 remoting and running on HL2.

After switching to this branch, please download [this package](https://github.com/microsoft/MixedRealityToolkit-Unity/files/5382357/ProfileSwitchTestPackage.zip) to test the PR. After opening ProfileSwitchTestScene, use the three buttons above the piano to switch profiles (left: default, middle: HL1, right: HL2). I included test profiles for both legacy XR and XRSDK pipelines, and by default legacy XR profiles are in use. To switch pipelines, click on each of the three buttons, scroll to the bottom in inspector and change the destinationProfile field in the ProfileSwitchTestScript compoent. The scene also by default tests prior initialization profile switching, as before playing the MRTK instance has the default profile but the changeProfileBeforeMRTKInit bool is checked for the ProfileSwitchTestScript attached to the rightmost button of the three so that when the scene is played HL2 profile is used. You are more than welcome to play around with the profiles, but the most significant difference between the three profiles is the locations of the profiler (left, middle and right corresponding to the location of buttons). Besides playing with the normal GameObjects in front of you, please make sure to test the Unity UI 2D/3D buttons on the right as they were causing problems in the past.

## Todo

- [x] Update release note
- [x] Update the profile switch section of the doc site

## Known issue
When using XRSDK, an attempt to switch profile at runtime via near interaction (press a pressable button) may cause the button to be triggered multiple times. In general, the use of near interaction to trigger profile switch should be disallowed unless a mechanism of temporarily disabling near interaction after the interaction is used. Otherwise, the state of the near interaction GameObject may lead to unexpected behavior.

### CODE REVIEW

File: Assets/MRTK/Core/Services/MixedRealityToolkit.cs [hunk 1]
```diff
@@ -81,11 +83,16 @@ public bool IsActiveInstance
         /// The public property of the Active Profile, ensuring events are raised on the change of the configuration
         /// </summary>
         /// <remarks>
-        /// When setting the ActiveProfile during runtime, the destroy of the currently running services will happen after the last LateUpdate()
+        /// <br>If changing the Active profile prior to the initialization (i.e. Awake()) of <see cref="MixedRealityToolkit"/> is desired,
```
Comment (wiwei) [inline Assets/MRTK/Core/Services/MixedRealityToolkit.cs:86]: Nit: We don't really use <br> in doccomments elsewhere, if only because they tend to make more noise when reading in code (even if they make the generated docs a little more useful)

File: Assets/MRTK/Core/Services/MixedRealityToolkit.cs [hunk 2]
```diff
@@ -109,6 +116,23 @@ public MixedRealityToolkitConfigurationProfile ActiveProfile
...
+        /// <br>If changing the Active profile during runtime is desired, modify <see cref="ActiveProfile"/> of the active instance directly.</br>
+        /// <br>This function requires the calller script to be executed earlier than <see cref="MixedRealityToolkit"/> script, which can be achieved by setting 
+        /// <see href="https://docs.unity3d.com/Manual/class-MonoManager.html">Script Execution Order settings</see>.</br>
+        /// <br>You are strongly recommended to see 
+        /// <see href="https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/MixedRealityConfigurationGuide.html#changing-profiles-at-runtime">here</see> 
+        /// for more information on profile switching.</br>
+        /// </remarks>
+        public static void SetProfileBeforeInitialization(MixedRealityToolkitConfigurationProfile profile)
+        {
+            MixedRealityToolkit toolkit = FindObjectOfType<MixedRealityToolkit>();
```
Comment (wiwei) [inline Assets/MRTK/Core/Services/MixedRealityToolkit.cs:132]: Should this log an error/warning if this is being called after Awake()?

File: Assets/MRTK/Core/Services/MixedRealityToolkit.cs [hunk 3]
```diff
@@ -109,6 +116,23 @@ public MixedRealityToolkitConfigurationProfile ActiveProfile
             }
         }
 
+        /// <summary>
+        /// Set the active profile prior to the initialization (i.e. Awake()) of <see cref="MixedRealityToolkit"/>
+        /// </summary>
+        /// <remarks>
+        /// <br>If changing the Active profile during runtime is desired, modify <see cref="ActiveProfile"/> of the active instance directly.</br>
+        /// <br>This function requires the calller script to be executed earlier than <see cref="MixedRealityToolkit"/> script, which can be achieved by setting
```
Comment (wiwei) [inline Assets/MRTK/Core/Services/MixedRealityToolkit.cs:124]:
```suggestion
        /// <br>This function requires the caller script to be executed earlier than <see cref="MixedRealityToolkit"/> script, which can be achieved by setting 
```

File: Assets/MRTK/Providers/XRSDK/XRSDKDeviceManager.cs [hunk 4]
```diff
@@ -125,6 +125,17 @@ public override void Update()
             }
         }
 
+        /// <inheritdoc/>
+        public override void Disable()
+        {
+            var controllersCopy = ActiveControllers.ToReadOnlyCollection();
+            foreach (var controller in controllersCopy)
+            {
+                CoreServices.InputSystem?.RaiseSourceLost(controller.Value.InputSource, controller.Value);
```
Comment (wiwei) [inline Assets/MRTK/Providers/XRSDK/XRSDKDeviceManager.cs:134]: Nit: It might be helpful to helper-ify these two lines since they are both critical in running during any remove operation (see lines 118-119 as well).

The risk is without in, someone could forget to have one of the lines (or if there's another change later that adds another operation here that's required, peopel might not update all of the occurneces)

File: Assets/MRTK/Services/InputSystem/MixedRealityInputSystem.cs [hunk 5]
```diff
@@ -171,11 +174,13 @@ public override void Initialize()
...
                 DebugUtilities.LogVerbose("MixedRealityInputModule added to main camera");
                 // There is no input module attached to the camera, add one.
-                CameraCache.Main.gameObject.AddComponent<MixedRealityInputModule>();
+                inputModule = CameraCache.Main.gameObject.AddComponent<MixedRealityInputModule>();
                 isInputModuleAdded = true;
             }
             else if ((inputModules.Length == 1) && (inputModules[0] is MixedRealityInputModule))
-            { /* Nothing to do, a MixedRealityInputModule was applied in the editor. */ }
+            {
+                inputModule = inputModules[0] as MixedRealityInputModule;
```
Comment (wiwei) [inline Assets/MRTK/Services/InputSystem/MixedRealityInputSystem.cs:182]: What's the change here from before (i.e. why this used to be a no-op, but now is doing something?)

**Review by wiwei — COMMENTED** [review]
Are there any test cases we can add to enshrine these fixes so that they don't regress in the future?

File: Assets/MRTK/Services/InputSystem/MixedRealityInputSystem.cs (hunk 5 above)
Comment (MaxWang-MS) [reply Assets/MRTK/Services/InputSystem/MixedRealityInputSystem.cs:182]: The code here is saving the reference so that we don't need to look for the script later.

File: Assets/MRTK/Core/Services/MixedRealityToolkit.cs (hunk 2 above)
Comment (MaxWang-MS) [reply Assets/MRTK/Core/Services/MixedRealityToolkit.cs:132]: I thought about it as well but as far as I know Unity does not have a built in way of marking whether the Awake of a script has been called or not. I can use a bool to track it but was not sure whether that solution would be elegant enough.

**Comment by MaxWang-MS** [comment]
> Are there any test cases we can add to enshrine these fixes so that they don't regress in the future?

Unfortunately after some research I think adding test cases is not feasible right now. For the UGUI related issue, there has been report of UGUI related tests not passing in batch mode, which is also the problem I encountered when trying to add a test for the case. #5887 reported the issue, but it was recently closed as I discovered I was able to unskip the previously skipped TriggerButtonFarInteraction test for UGUI buttons (already merged in #8790). After taking a closer look it seems the problem is no longer affecting us there because an Interactable script has been added to the pressable button UnityUI prefab instead of the UGUI issue in batch mode being resolved.
For the prior initialization profile switching case, a potential test will involve scene loading, which due to some complications is not achievable with a low cost.

File: Assets/MRTK/Core/Services/MixedRealityToolkit.cs (hunk 2 above)
Comment (wiwei) [reply Assets/MRTK/Core/Services/MixedRealityToolkit.cs:132]: Fine either way, just curious what the thought process was

**Review by wiwei — APPROVED** [review]

File: Assets/MRTK/Services/InputSystem/MixedRealityInputSystem.cs [hunk 6]
```diff
@@ -247,6 +252,21 @@ public override void Enable()
             InputEnabled?.Invoke();
         }
 
+        public override void LateUpdate()
+        {
+            // Check whether manual initialization of input module is needed.
+            // The check is only required once after input system is created.
+            if (!isInputModuleAdded && !inputModuleChecked)
+            {
+                if (inputModule.ManualInitializationRequired)
```
Comment (davidkline-ms) [inline Assets/MRTK/Services/InputSystem/MixedRealityInputSystem.cs:261]: should we verify that inputModule is not null here?

**Review by davidkline-ms — COMMENTED** [review]
overall looks good. one question re: null checking the input module

File: Assets/MRTK/Services/InputSystem/MixedRealityInputSystem.cs (hunk 6 above)
Comment (MaxWang-MS) [reply Assets/MRTK/Services/InputSystem/MixedRealityInputSystem.cs:261]: My understanding is that inputModule cannot be null there unless there is something wrong with other code that leads to that scenario, so I left out the null check.

File: Documentation/MixedRealityConfigurationGuide.md [hunk 7]
```diff
@@ -359,23 +353,99 @@ using UnityEngine;
...
+        }
+        MixedRealityToolkit.Instance.ActiveProfile = ProfileToUse;
+        StartCoroutine(UpdateCanvasCameraReference());
+    }
+
+    private IEnumerator UpdateCanvasCameraReference()
+    {
+        // Wait for the profile change to complete
+        yield return null; // Skip the frame the profile swap started
+        yield return null; // Skip the next frame as well as the UI camera creation may still be in process
```
Comment (keveleigh) [inline Documentation/MixedRealityConfigurationGuide.md:434]: Similar to how you've updated the input module to persist between profiles, I wonder if we want the UI raycast camera to also persist? Since it's a Unity component, I'm not sure it has any dependencies itself on the active MRTK instance. The FocusProvider already has code to find an existing raycast camera on startup:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/e07020b0e84340be604956a543cb54ce88e28d4f/Assets/MRTK/Services/InputSystem/FocusProvider.cs#L693-L701

Would we want to suppress its clean-up during a profile switch, like you did with the input module?

Comment (MaxWang-MS) [reply Documentation/MixedRealityConfigurationGuide.md:434]: The cleanup time behavior of UI camera is currently different than the input module mainly because we expect the module to be in the scene when we start playing the scene but UI camera is always created by MRTK at start. As it is created by MRTK it may be logical to make it go away during the destroy process. We could take the other route, but it will take much time to fully retest the PR (all combinations of pipeline/hardware/remote vs on device etc.)

Comment (keveleigh) [reply Documentation/MixedRealityConfigurationGuide.md:434]: That works. I think it'd be worth filing an issue to see if we can handle that camera better during a reload, but this code snippet and doc should be sufficient until then.

File: Documentation/MixedRealityConfigurationGuide.md [hunk 8]
```diff
@@ -359,23 +353,99 @@ using UnityEngine;
...
+            }
+        }
+        MixedRealityToolkit.Instance.ActiveProfile = ProfileToUse;
+        StartCoroutine(UpdateCanvasCameraReference());
+    }
+
+    private IEnumerator UpdateCanvasCameraReference()
+    {
+        // Wait for the profile change to complete
+        yield return null; // Skip the frame the profile swap started
```
Comment (keveleigh) [inline Documentation/MixedRealityConfigurationGuide.md:433]: Instead of waiting some number of frames explicitly, could this be something like

```c#
while (MixedRealityToolkit.Instance.ActiveProfile != ProfileToUse)
{
    yield return null;
}
```

since it looks like the backing `activeProfile` doesn't get set immediately

File: Documentation/MixedRealityConfigurationGuide.md [hunk 9]
```diff
@@ -359,23 +353,99 @@ using UnityEngine;
...
+using Microsoft.MixedReality.Toolkit;
+using Microsoft.MixedReality.Toolkit.Input.Utilities;
+using System.Collections;
+using System.Collections.Generic;
+using UnityEngine;
+
+public class ActiveProfileSwapper : MonoBehaviour
+{
+    
+    public MixedRealityToolkitConfigurationProfile ProfileToUse;
```
Comment (keveleigh) [inline Documentation/MixedRealityConfigurationGuide.md:408]: We might want this to be private with the SerializeField tag, so the code snippets follow the MRTK coding guidelines

**Review by keveleigh — APPROVED** [review]

File: Documentation/MixedRealityConfigurationGuide.md (hunk 8 above)
Comment (MaxWang-MS) [reply Documentation/MixedRealityConfigurationGuide.md:433]: `activeProfile` is actually set before all the new services are set up so we have to leave the yield returns here for now.

**Comment by jelmerS2** [comment]
Is there any guide as of how to use this? 
I'm following this: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/MixedRealityConfigurationGuide.html#swapping-profiles-prior-to-mrtk-initialization

I set script execution order correctly, as far as I understand it. Still I get the following errors:
There's already a IMixedRealityInputSystem.Mixed Reality Input System registered!
Failed to start the Input System!
There's already a IMixedRealityFocusProvider.Focus Provider registered!
Failed to register the focus provider! The input system will not function without it.

Some guiding would be apprectiated :)

**Comment by MaxWang-MS** [comment]
@jelmerS2 Please see the answer [here](https://github.com/microsoft/MixedRealityToolkit-Unity/discussions/9154#discussioncomment-297254).
