### PR TITLE
Input System back port from Dev branch

### LINKED ISSUE #1027: Input System should easily handle update from 2017.1 to 2017.2
We should think of a way for our Input System to be forward compatible to keep older projects on the cutting edge.

### LINKED ISSUE #1037: uGUI related does not work well with Unity 2017.2
"KeyboardTest.unity" This does not work on Unity 2017.2, will it work?
uGUI related does not work well with Unity 2017.2

### LINKED ISSUE #1077: Remove RegisterPointableCanvas
We shouldn't have to add a component to be able to point at a uGUI canvas.

### PR DESCRIPTION
**Pull request by StephenHodgson**
Changes
---
- Fixes #1027 Porting Input System changes from Dev branch.
- Should make it easier to update older projects to updated Unity APIs and Input System.
- Marking all removed public methods and classes as obsolete where we can.
- Updated all the test scenes.
- Updated all the Unit Tests and they all pass.
- Fixes #1077
- Fixes #1037
- Adds better scene setup support via config menu options
image

Breaking Changes
---
- `TryGetPosition` is now `TryGetPointerPosition`
- `TryGetOrientation` is now `TryGetPointerRotation`
- All other changes should throw `Obsolete` warnings with suggested updates.

### CODE REVIEW

File: Assets/HoloToolkit/Input/Scripts/Gaze/GazeManager.cs [hunk 1]
```diff
@@ -210,6 +292,7 @@ private GameObject RaycastPhysics()
         /// <summary>
         /// Perform a Unity UI Raycast, compare with the latest 3D raycast, and overwrite the hit object info if the UI gets focus
         /// </summary>
+        [Obsolete]
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/Input/Scripts/Gaze/GazeManager.cs]: Unsure how much of this will get removed, or just moved to the `FocusManager`.

File: Assets/HoloToolkit/Input/Scripts/Focus/RegisterPointableCanvas.cs [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+
+using System.Collections;
+using UnityEngine;
+
+namespace HoloToolkit.Unity.InputModule
+{
+    /// <summary>
+    /// Script to register a Canvas component so it's capable of being focused at for 'point and commit' scenarios.
+    /// </summary>
+    public class RegisterPointableCanvas :
```
Comment (StephenHodgson) [inline Assets/HoloToolkit/Input/Scripts/Focus/RegisterPointableCanvas.cs]: We really shouldn't need to register our canvas'.  Looking for a way to remove this.

**Comment by DDReaper** [comment]
Agree with leaving in old methods and marking them as obsolete to avoid breaking backwards compatibility for now.
However, seeing tons of obsolete messages in the core HoloToolKit scripts and the examples.  These really should be cleaned up, else users are going to have issue cleaning up their projects if the console is already flooded with MRTK warnings.

**Comment by StephenHodgson** [comment]
Warnings are better than errors! 😅

But I agree, I'm not anywhere near close to finished with this PR.

**Comment by StephenHodgson** [comment]
Okay, this PR is ready to be tested.

**Comment by DDReaper** [comment]
OK, will check this shortly

**Comment by StephenHodgson** [comment]
> "UnityException: Speech recognition is not supported on this machine."

Be sure you have the "Get to know me" enabled in your OS settings.
