### PR TITLE
Fixed MixedRealityManager bugs

### LINKED ISSUE #2748: vNEXT: Unable to find managers.
Overview
---
When adding speech input handler, we get a null ref about being unable to fine the speech system.

**To Reproduce**
1. Open any scene
2. add a Speech Input Handler to any game object
3. View error

### PR DESCRIPTION
**Pull request by StephenHodgson**
- The ternary operator was a bit difficult to read, so I simplified it and removed the redundant else.
- Also added the teleport system to core managers.
- Fixed #2748
- Improved Speech Handler to be more resilient when missing Mixed Reality Manager or Speech System.

### CODE REVIEW

**Comment by StephenHodgson** [comment]
I'd like to also fix #2748

File: Assets/MixedRealityToolkit/_Core/Managers/MixedRealityManager.cs [hunk 1]
```diff
@@ -896,6 +913,17 @@ private void GetComponentByTypeAndName(Type type, string managerName, out IMixed
 
             manager = null;
 
+            if (isMixedRealityManagerInitializing)
+            {
+                Debug.LogWarning("Unable to get manager a manager while initializing!");
```
Comment (keveleigh) [inline Assets/MixedRealityToolkit/_Core/Managers/MixedRealityManager.cs]: duplicate "manager" (or some other issue, depending on what you meant to write)

File: Assets/MixedRealityToolkit/_Core/Managers/MixedRealityManager.cs [hunk 2]
```diff
@@ -896,6 +913,17 @@ private void GetComponentByTypeAndName(Type type, string managerName, out IMixed
...
+                return;
+            }
+
+            if (mixedRealityComponentsCount != MixedRealityComponents.Count)
```
Comment (keveleigh) [inline Assets/MixedRealityToolkit/_Core/Managers/MixedRealityManager.cs]: Why do we keep a count reference that's expected to stay equal to `MixedRealityComponents.Count`? Seems like duplicate data.
