### PR TITLE
Bounds override fix

### LINKED ISSUE #7997: BoundingBox resizes collider OnDisable
## Describe the bug

When I'm using boxPadding, it seems to treat the rig creation differently than rig destroy. Everytime the object turns off, the bounding box size is reduced (linear). 

## To reproduce

1. Create an interactable object
2. add a box padding
3. Turn the object on and off and watch the collider slowly shrink

## Expected behavior

The permanent collider used as override should not be changed. It seems that you are growing the targetbounds on creation, but shrinking the bounds override. 

## Your setup (please complete the following information)

- Unity Version 2019.3.1f1
- MRTK Version v2.3

## Target platform (please complete the following information)

- HoloLens

### PR DESCRIPTION
**Pull request by Zee2**
## Overview
In `BoundingBox`, you can set a `boundsOverride` collider which essentially provides a "proxy object" to provide the bounds to the `BoundingBox`. There is an optional `boxPadding` that can be applied to this collider, to space out the `BoundingBox` around the object.

Unfortunately, this padding is achieved by destructively resizing the provided `boundsOverride` `BoxCollider`.

In the existing code, there is a line that is intended to compensate for this destructive resizing operation; in `DestroyRig` the code resizes the `boundsOverride` in the _negative_ direction of the padding, effectively cancelling out the previous padding operation.

However, `DestroyRig` is actually called first when we are creating the rig (it's actually included inside `CreateRig`, ironically!), in addition to being called when we destroy the rig; it seems as though the original author of the code believed that `DestroyRig` was only called when the rig was being torn down (honest assumption, and shouldn't cause issues most of the time!)

This has the ill effect, however, of resizing the `boundsOverride` one too many times when you repeatedly set the `BoundingBox` to be Active/Inactive. If you continue activating/deactivating the `BoundingBox` gameobject, the bounds will continue to grow/shrink to a very large (and incorrect) size!

This PR fixes this behavior in the following way: instead of applying negative padding to "cancel out" the resizing operation, it simply resets the `boundsOverride` to whatever size it had when the `BoundingBox` was enabled, and when `CreateRig()` was called.

This resolves #7997 :)

## Changes
- Resolves #7997 by preventing unwanted `boundsOverride` resizing behavior when toggling the status of the root `BoundingBox` object.
- Adds a `Vector3? initialBoundsOverrideSize` which is used to record the size of the `boundsOverride` when the rig is constructed.
- Adds code in `DestroyRig` to reset the `boundsOverride` size to the recorded `initialBoundsOverrideSize` when destroying/tearing down the rig.
- Adds unit test that covers the issue reported in #7997.

## Verification
- An additional test has been added to verify that changing `boundsOverride` size and toggling the active status of the `BoundingBox` does not destructively modify the `boundsOverride` size.

### CODE REVIEW

File: Assets/MRTK/SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs [hunk 1]
```diff
@@ -1317,7 +1330,12 @@ private void DestroyRig()
             }
             else
             {
-                boundsOverride.size -= boxPadding;
+                // If we have previously logged an initial bounds size,
+                // reset the boundsOverride BoxCollider to the initial size.
+                // This is because the CalculateBoxPadding
+                if (initialBoundsOverrideSize.HasValue){
```
[the remark this answers is not in the document]
Comment (Zee2) [reply Assets/MRTK/SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs]: Resolved with `dotnet-format`

File: Assets/MRTK/SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs [hunk 2]
```diff
@@ -1196,6 +1202,13 @@ public void SetScaleLimits(float min, float max, bool relativeToInitialState = t
         /// </summary>
         public void CreateRig()
         {
+            // Record what the initial size of the bounds override
+            // was when we constructed the rig, so we can restore
+            // it after we destructively edit the size with the
+            // BoxPadding (#7997)
+            if (boundsOverride != null){
```
[the remark this answers is not in the document]
Comment (Zee2) [reply Assets/MRTK/SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs]: Resolved with `dotnet-format`

**Comment by Zee2** [comment]
@thalbern please resolve your change requests, at your convenience :) I have fixed the style issues and have applied the changes to `BoundsControl` as well.

File: Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/BoundsControl.cs [hunk 3]
```diff
@@ -462,6 +468,15 @@ public void CreateRig()
                 return;
             }
 
+            // Record what the initial size of the bounds override
+            // was when we constructed the rig, so we can restore
+            // it after we destructively edit the size with the
+            // BoxPadding (#7997)
```
Comment (wiwei) [inline Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/BoundsControl.cs:474]: Do you know if issue numbers persist across forks (i.e. if this gets forked/moved does this still remain relevant - I assume not) - if not it might be better to have a full link to the issue (to preserve the project/org/issuenumber context)

File: Assets/MRTK/SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs [hunk 4]
```diff
@@ -1,11 +1,11 @@
 ﻿// Copyright (c) Microsoft Corporation. All rights reserved.
 // Licensed under the MIT License. See LICENSE in the project root for license information.
 
-using Microsoft.MixedReality.Toolkit.Input;
-using Microsoft.MixedReality.Toolkit.Utilities;
 using System;
 using System.Collections.Generic;
 using System.Runtime.CompilerServices;
+using Microsoft.MixedReality.Toolkit.Input;
```
Comment (wiwei) [inline Assets/MRTK/SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs:7]: Nit: Move this back up to keep using statements alphabetical

Comment (CDiaz-MS) [reply Assets/MRTK/SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs:7]: Quick VS tip

You can sort the using in VS with this:
image

File: Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/BoundsControl.cs (hunk 3 above)
Comment (Zee2) [reply Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/BoundsControl.cs:474]: Ok, fixed.

File: Assets/MRTK/SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs (hunk 4 above)
Comment (Zee2) [reply Assets/MRTK/SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs:7]: Heads up, `dotnet-format` doesn't seem to agree.

`dotnet-format` aggressively recommends putting System* namespaces first, then alphabetically sorting the rest of the namespaces.
