### PR TITLE
Fix mesh when using app-based holographic remoting

### LINKED ISSUE #10245: If the Unity splash screen is disabled for an OpenXR hololens 2 app where spatial awareness is enabled, the spatial mesh is not built.
## Describe the bug

If the Unity splash screen is disabled for an OpenXR hololens 2 app where spatial awareness is enabled, the spatial mesh is not built. In the same project, if the splash screen is enabled, the spatial mesh is built and functions properly.

## To reproduce

1. Create an MRTK app in Unity for hololens 2 with spatial awareness enabled by following the MRTK project setup instructions  [here](https://docs.microsoft.com/en-us/learn/modules/learn-mrtk-tutorials/1-3-exercise-configure-unity-for-windows-mixed-reality).
2. Switch to UWP build platform, then build and run the app on hololens 2.
3. See that spatial awareness and the spatial mesh are running properly
4. Disable the unity splash screen in the project settings
5. Build and run the app again
6. See that the spatial awareness is not functioning properly and the spatial mesh is not created

To make it easy to reproduce this error, I have created a nearly-empty MRTK project repository on github.

The only modifications to this project as compared to the MRTK tutorial instructions are:
* Cloned the default hololens 2 MRTK configuration to enable spatial mesh and set mesh visibility to occlusion
* Added an ErrorManager that receives any exceptions thrown and displays them on a camera-anchored canvas

The repository for that project is [here](https://github.com/larryNexus/mrtk-testing).

## Expected behavior

Disabling the Unity splash screen should not affect the proper functioning of the MRTK spatial awareness mesh.

## Your setup

- Unity Version: 2020.3.17 and 2020.3.8
- MRTK Version: 2.7.2
- MRTK OpenXR: 1.0.1, 1.0.3
- com.unity.xr.openxr 1.2.8

## Target platform (please complete the following information)

- HoloLens 2, ARM or ARM64

### PR DESCRIPTION
**Pull request by keveleigh**
## Overview

Updates our XRSDK-based mesh observers to:

1. Properly refresh their mesh subsystem when XR is initialized _after_ MRTK is initialized
2. Ensure that more than one observer is not running when the "generic" observer is used with a more specific observer (like the one specific to OpenXR)
3. Ensured that we don't try to use a mesh subsystem that isn't actively running. This was leading to 
3. Ensured that we don't try to set values on the mesh subsystem unless the app is running (the underlying bug here would probably also be solved by fix 3)

## Changes
- Fixes: #10293, fixes https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10244, might fix #10245 (but I couldn't get a repro)

### CODE REVIEW

File: Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs [hunk 1]
```diff
@@ -73,30 +111,16 @@ private async void EnableIfLoaderBecomesActive()
...
+            ? meshSubsystem :
 #if XR_MANAGEMENT_ENABLED
-                || XRGeneralSettings.Instance == null || XRGeneralSettings.Instance.Manager == null || XRGeneralSettings.Instance.Manager.activeLoader == null
-#endif // XR_MANAGEMENT_ENABLED
-                ) { return; }
-
-#if XR_MANAGEMENT_ENABLED
-            meshSubsystem = XRGeneralSettings.Instance.Manager.activeLoader.GetLoadedSubsystem<XRMeshSubsystem>();
+            meshSubsystem = IsActiveLoader ?? false
+                ? XRGeneralSettings.Instance.Manager.activeLoader.GetLoadedSubsystem<XRMeshSubsystem>()
```
Comment (MaxWang-MS) [inline Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs:118]: Do we need to null check here?

File: Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs [hunk 2]
```diff
@@ -41,7 +41,44 @@ public class GenericXRSDKSpatialMeshObserver :
             BaseMixedRealityProfile profile = null) : base(spatialAwarenessSystem, name, priority, profile)
         { }
 
-        protected virtual bool? IsActiveLoader => true;
+        private IReadOnlyList<GenericXRSDKSpatialMeshObserver> observersCache;
```
Comment (MaxWang-MS) [inline Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs:44]: I am slightly worried about using a cache here. Could it handle the situation of someone enabling a new observer during runtime?

File: Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs (hunk 1 above)
Comment (keveleigh) [reply Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs:118]: Albeit somewhat indirectly, `IsActiveLoader` should ensure that all of these entries are non-null before we get to this point: https://github.com/microsoft/MixedRealityToolkit-Unity/blob/3fbcd97462914be306319ea8ca09b9817b9a7fc5/Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs#L51-L53

File: Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs (hunk 2 above)
Comment (keveleigh) [reply Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs:44]: you're right that it currently doesn't. however, in that case, I'd assume that the observers and system have already been spun up, in which case it's in the developer's hands to properly manage which ones should be enabled or not when they add a new one. these observers only really use this value to determine if they should start, but not if they should continue running.

the downside to not using a cache outweighs the benefits in my opinion, as unfortunately the method for accessing all observers allocates a list on every call.

**Review by davidkline-ms — APPROVED** [review]

**Review by MaxWang-MS — APPROVED** [review]
