### PR TITLE
Fixing BoundsControl auto-flatten and scale handle orientation

### LINKED ISSUE #10009: BoundsControl does not flatten correctly with auto flatten axis
## Describe the bug
`BoundsControl`, when flattened onto a slate or other flat object with the flatten axis set to Auto, does not properly collapse rotate handles, and instead has rotate and scale handles superimposed, resulting in inconsistent manipulations of flattened `BoundsControl`s.

## To reproduce

1. Load the HandInteractionExamples example scene
2. Run the scene
3. Examine the slate demonstrating "BoundingBox" (really, `BoundsControl`) flattening behavior
4. Observe that rotate handles are still active, "inside" the scale handles

## Expected behavior
Rotate handles on corners and scale handles should not both be present. Either one or the other should be active, preferably scale handles only for shell parity.

## Screenshots

Screenshot

## Your setup
- Unity 2019.4.28f1, but present on all versions presumably
- MRTK `main` branch at time of posting

## Target platform
All

## Additional context
This issue seems to have been present ever since BoundsControl was originally refactored/graduated. It is present in all 2.6.x and 2.7.x releases.

### PR DESCRIPTION
**Pull request by Zee2**
## Overview
Since a while ago (at least 2.6.x) BoundsControl's `FlattenAuto` mode has been broken, such that per-axis handles are not properly disabling themselves when flattened. This has resulted in "doubled up" handles, where there are rotation handles "inside" scale handles, causing inconsistent manipulations.

This was the result of FlattenAuto being passed as the "current flattening axis" to the per-axis handles, which actually need a proper axis in order to determine which handles to disable. When "FlattenAuto" was passed instead of an actual axis, the handles did not know what to do, and as a result did not actually disable any handles.

This is because the per-axis handles used `VisualUtils.GetFlattenedIndices`, which, when given `FlattenAuto` as the axis, would simply not return any flattened indices.

**This was not caught by automated testing. There was a test coverage gap, as `FlattenAuto` was never tested in any BoundsControl test.** A new test is added that verifies per-axis handle flattening behavior when `FlattenAuto` is set.

The main fix is in the form of a new property, `actualFlattenedAxis`, which has a getter that evaluates the `FlattenAuto` policy against the current target bounds, and returns the actual flattened axis which can be fed to any handle, visual, or any other dependency. 

This PR also fixes a small issue with the scale handles not being properly rotated for slates.

## Changes
- Adds `actualFlattenedAxis` getter to `BoundsControl` which resolves the actual flattened axis from a `FlattenAuto` policy at get-time
- `BoundsControl` now passes `actualFlattenedAxis` to all dependent visuals and handles
- `ScaleHandles` now properly calculates handle realignment for flattened/slate scenarios
- Order of BoundsControl init calls is edited; `CreateRig` is now called before `SetActivationFlags`. This allows the target bounds to be determined before activation flags/events are triggered, which is necessary to avoid handle rebuilding before the target bounds have been calculated (and therefore a sticky situation where handles were trying to re-flatten against a target bounds that did not yet exist!)
- New test is added to resolve gap in test coverage.
- Fixes #10009

## Verification
A new test has been added that checks per-axis handle behaviors when `FlattenAuto` is used and the target object has been shrunk on one axis.

### CODE REVIEW

File: Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs [hunk 1]
```diff
@@ -564,6 +564,21 @@ public ElasticsManager ElasticsManager
         private Vector3[] boundsCorners = new Vector3[8];
         public Vector3[] BoundsCorners { get; private set; }
 
+        // Current actual flattening axis, derived from FlattenAuto, if set
+        private FlattenModeType actualFlattenAxis {
```
Comment (keveleigh) [inline Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs:568]: nit on the casing here: we've tended to use PascalCase for all properties, regardless of their access modifiers.

https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/contributing/coding-guidelines?view=mrtkunity-2021-05#naming-conventions

File: Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs [hunk 2]
```diff
@@ -1235,16 +1250,15 @@ private void TransformTarget(HandleType transformType)
                     // If non-uniform scaling or uniform scaling only on the non-flattened axes
                     if (ScaleHandlesConfig.ScaleBehavior != HandleScaleMode.Uniform || !UniformScaleOnFlattenedAxis)
                     {
-                        FlattenModeType determinedType = FlattenAxis == FlattenModeType.FlattenAuto ? VisualUtils.DetermineAxisToFlatten(TargetBounds.bounds.extents) : FlattenAxis;
-                        if (determinedType == FlattenModeType.FlattenX)
+                        if (actualFlattenAxis == FlattenModeType.FlattenX)
```
Comment (keveleigh) [inline Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs:1253]: Could `actualFlattenAxis` be cached here, similar to how it was before? That way we're not calling into the property (and thus potentially calling into `VisualUtils.DetermineAxisToFlatten`) every time? Or do we expect that each call here might be slightly different (and/or the call is negligible perf-wise)?

File: Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs (hunk 1 above)
Comment (Zee2) [reply Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs:568]: Thanks, fixed.

File: Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs (hunk 2 above)
Comment (Zee2) [reply Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs]: Ah, good catch. The perf is negligible but every little bit matters! Fixed, it's now cached for each entry in those if-statements.

File: Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs [hunk 3]
```diff
@@ -564,6 +564,21 @@ public ElasticsManager ElasticsManager
         private Vector3[] boundsCorners = new Vector3[8];
         public Vector3[] BoundsCorners { get; private set; }
 
+        // Current actual flattening axis, derived from FlattenAuto, if set
+        private FlattenModeType ActualFlattenAxis {
```
Comment (davidkline-ms) [inline Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs:568]: Question: Why "Actual"FlattenAxis?

File: Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ScaleHandles.cs [hunk 4]
```diff
@@ -200,21 +194,52 @@ protected Quaternion GetRotationRealignment(int handleIndex)
...
 
-            // Flip the handle if it's on the underside of the bounds.
-            Quaternion flip = Quaternion.Euler(0, 0, handlePos.y > 0 ? 0 : 90);
+            if(isFlattened)
+            {
+                Vector3 axis = Vector3.forward;
+                switch(currentFlattenAxis)
+                {
+                    case FlattenModeType.FlattenAuto:
+                        Debug.LogError("ScaleHandles should never receive FlattenAuto. BoundsControl should pass actualFlattenAxis");
```
Comment (davidkline-ms) [inline Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ScaleHandles.cs:203]: ActualFlattenAxis instead of actualFlattenAxis?

File: Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs (hunk 3 above)
Comment (Zee2) [reply Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs:568]: Answer: `flattenAxis` can be `FlattenAuto`, which is not actually an axis. `FlattenAuto` resolves to either X, Y, or Z depending on the particular dimensions of the target bounds. The per-axis handles require an _actual_ axis to flatten on, not an "auto" axis, so now `BoundsControl` "resolves" the flatten axis into an actual, real axis. Hence "actual" flatten axis :)

File: Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ScaleHandles.cs (hunk 4 above)
Comment (Zee2) [reply Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ScaleHandles.cs]: Resolved

File: Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs [hunk 5]
```diff
@@ -1476,14 +1491,14 @@ private void ResetVisuals()
...
             bool isVisible = (active == true && wireframeOnly == false);
 
-            rotationHandles.Reset(isVisible, flattenAxis);
-            links.Reset(active, flattenAxis);
-            scaleHandles.Reset(isVisible, flattenAxis);
-            translationHandles.Reset(isVisible, flattenAxis);
+            rotationHandles.Reset(isVisible, ActualFlattenAxis);
+            links.Reset(active, ActualFlattenAxis);
+            scaleHandles.Reset(isVisible, ActualFlattenAxis);
+            translationHandles.Reset(isVisible, ActualFlattenAxis);
```
Comment (keveleigh) [inline Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs:1501]: small suggestion, if we want to cache `ActualFlattenAxis` throughout this block as well

File: Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs [hunk 6]
```diff
@@ -1235,16 +1250,16 @@ private void TransformTarget(HandleType transformType)
...
                         {
                             scaleFactor.x = 1;
                         }
-                        if (determinedType == FlattenModeType.FlattenY)
+                        if (currentActualFlattenAxis == FlattenModeType.FlattenY)
                         {
                             scaleFactor.y = 1;
                         }
-                        if (determinedType == FlattenModeType.FlattenZ)
+                        if (currentActualFlattenAxis == FlattenModeType.FlattenZ)
```
Comment (keveleigh) [inline Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs:1262]: Could these be `else if`s?

**Review by keveleigh — APPROVED** [review]
Some nit-level feedback, so overall approving!
